
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SpellcrafterFortressBridgeAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SpellcrafterFortressBridgeAddonDeed();
			}
		}

		[ Constructable ]
		public SpellcrafterFortressBridgeAddon()
		{



			AddComplexComponent( (BaseAddon) this, 1872, -2, -2, 5, 1443, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 1872, -2, -1, 5, 1443, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 1872, -1, -2, 5, 1443, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 1872, -1, -1, 5, 1443, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1872, 0, -2, 5, 1443, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 1872, 0, -1, 5, 1443, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 1872, 1, -2, 5, 1443, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1872, 1, -1, 5, 1443, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1872, 2, -2, 5, 1443, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1872, 2, -1, 5, 1443, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1872, 3, -2, 5, 1443, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 1872, 3, -1, 5, 1443, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 1872, 4, -2, 5, 1443, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1872, 4, -1, 5, 1443, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1874, 5, -2, 5, 1443, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 1874, 5, -1, 5, 1443, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1874, 3, -2, 10, 1443, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 1874, 3, -1, 10, 1443, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1872, 2, -2, 10, 1443, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1872, 2, -1, 10, 1443, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 1872, -1, -2, 10, 1443, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 1872, -1, -1, 10, 1443, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 1872, 0, -2, 10, 1443, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 1872, 0, -1, 10, 1443, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 1872, 1, -2, 10, 1443, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 1872, 1, -1, 10, 1443, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 1872, -1, -2, 15, 1443, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 1872, -1, -1, 15, 1443, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 1872, 0, -2, 15, 1443, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 1872, 0, -1, 15, 1443, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 1872, 1, -2, 15, 1443, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 1872, 1, -1, 15, 1443, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 1874, 2, -2, 15, 1443, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 1874, 2, -1, 15, 1443, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 1872, -2, -2, 15, 1443, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 1872, -2, -1, 15, 1443, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 1872, -2, -2, 10, 1443, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 1872, -2, -1, 10, 1443, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 1872, -1, -2, 10, 1443, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 1872, -1, -1, 10, 1443, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 1872, -4, -2, 10, 1443, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 1872, -4, -1, 10, 1443, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 1872, -3, -2, 10, 1443, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 1872, -3, -1, 10, 1443, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 1872, -3, -2, 5, 1443, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 1872, -3, -1, 5, 1443, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 1872, -3, -1, 15, 1443, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 18113, -1, -2, 20, 1443, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 18113, 0, -2, 20, 1443, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 18113, 2, -2, 17, 1443, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 18113, 3, -2, 12, 1443, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 1872, -4, -1, 15, 1443, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 1872, -4, -2, 15, 1443, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 1872, -3, -2, 15, 1443, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 1872, -4, -2, 5, 1443, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 1872, -4, -1, 5, 1443, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 17708, 4, -2, 45, 1443, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 17707, 4, -1, 57, 1443, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 17708, -2, -2, 49, 1443, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 17708, 1, -2, 45, 1443, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 17707, -2, -1, 57, 1443, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 17707, 1, -1, 53, 1443, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 17709, 1, -2, 17, 1443, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 17709, -2, -2, 20, 1443, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 17709, 4, -2, 10, 1443, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 17308, 4, -3, 5, 1443, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 17308, 2, -3, 5, 1443, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 17308, -1, -3, 5, 1443, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 17308, -4, -3, 5, 1443, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 1872, 1, 0, 5, 1443, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 1872, -2, 0, 5, 1443, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 1872, -2, 1, 5, 1443, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 1872, -2, 2, 5, 1443, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 1872, -2, 3, 5, 1443, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 1872, -1, 0, 5, 1443, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 1872, -1, 1, 5, 1443, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 1872, -1, 2, 5, 1443, -1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 1872, -1, 3, 5, 1443, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 1872, 0, 0, 5, 1443, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 1872, 0, 1, 5, 1443, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 1872, 0, 2, 5, 1443, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 1872, 0, 3, 5, 1443, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 1872, 1, 0, 5, 1443, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 1872, 1, 1, 5, 1443, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 1872, 1, 2, 5, 1443, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 1872, 1, 3, 5, 1443, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 1872, 2, 0, 5, 1443, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 1872, 2, 1, 5, 1443, -1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 1872, 2, 2, 5, 1443, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 1872, 2, 3, 4, 1443, -1, "", 1);// 90
			AddComplexComponent( (BaseAddon) this, 1872, 3, 0, 5, 1443, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 1872, 3, 1, 5, 1443, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 1872, 3, 2, 5, 1443, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 1872, 3, 3, 5, 1443, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 1872, 4, 0, 5, 1443, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 1872, 4, 1, 5, 1443, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 1872, 4, 2, 5, 1443, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 1872, 4, 3, 5, 1443, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 1874, 5, 0, 5, 1443, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 1874, 5, 1, 5, 1443, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 1874, 5, 2, 5, 1443, -1, "", 1);// 101
			AddComplexComponent( (BaseAddon) this, 1874, 5, 3, 5, 1443, -1, "", 1);// 102
			AddComplexComponent( (BaseAddon) this, 1874, 3, 0, 10, 1443, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 1874, 3, 1, 10, 1443, -1, "", 1);// 104
			AddComplexComponent( (BaseAddon) this, 1874, 3, 2, 10, 1443, -1, "", 1);// 105
			AddComplexComponent( (BaseAddon) this, 1874, 3, 3, 10, 1443, -1, "", 1);// 106
			AddComplexComponent( (BaseAddon) this, 1872, 2, 0, 10, 1443, -1, "", 1);// 107
			AddComplexComponent( (BaseAddon) this, 1872, 2, 1, 10, 1443, -1, "", 1);// 108
			AddComplexComponent( (BaseAddon) this, 1872, 2, 2, 10, 1443, -1, "", 1);// 109
			AddComplexComponent( (BaseAddon) this, 1872, 2, 3, 10, 1443, -1, "", 1);// 110
			AddComplexComponent( (BaseAddon) this, 1872, -1, 0, 10, 1443, -1, "", 1);// 111
			AddComplexComponent( (BaseAddon) this, 1872, -1, 1, 10, 1443, -1, "", 1);// 112
			AddComplexComponent( (BaseAddon) this, 1872, -1, 2, 10, 1443, -1, "", 1);// 113
			AddComplexComponent( (BaseAddon) this, 1872, -1, 3, 10, 1443, -1, "", 1);// 114
			AddComplexComponent( (BaseAddon) this, 1872, 0, 0, 10, 1443, -1, "", 1);// 115
			AddComplexComponent( (BaseAddon) this, 1872, 0, 1, 10, 1443, -1, "", 1);// 116
			AddComplexComponent( (BaseAddon) this, 1872, 0, 2, 10, 1443, -1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 1872, 0, 3, 10, 1443, -1, "", 1);// 118
			AddComplexComponent( (BaseAddon) this, 1872, 1, 0, 10, 1443, -1, "", 1);// 119
			AddComplexComponent( (BaseAddon) this, 1872, 1, 1, 10, 1443, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 1872, 1, 2, 10, 1443, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 1872, 1, 3, 10, 1443, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 1872, -1, 0, 15, 1443, -1, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 1872, -1, 1, 15, 1443, -1, "", 1);// 124
			AddComplexComponent( (BaseAddon) this, 1872, -1, 2, 15, 1443, -1, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 1872, -1, 3, 15, 1443, -1, "", 1);// 126
			AddComplexComponent( (BaseAddon) this, 1872, 0, 0, 15, 1443, -1, "", 1);// 127
			AddComplexComponent( (BaseAddon) this, 1872, 0, 1, 15, 1443, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 1872, 0, 2, 15, 1443, -1, "", 1);// 129
			AddComplexComponent( (BaseAddon) this, 1872, 0, 3, 15, 1443, -1, "", 1);// 130
			AddComplexComponent( (BaseAddon) this, 1872, 1, 0, 15, 1443, -1, "", 1);// 131
			AddComplexComponent( (BaseAddon) this, 1872, 1, 1, 15, 1443, -1, "", 1);// 132
			AddComplexComponent( (BaseAddon) this, 1872, 1, 2, 15, 1443, -1, "", 1);// 133
			AddComplexComponent( (BaseAddon) this, 1872, 1, 3, 15, 1443, -1, "", 1);// 134
			AddComplexComponent( (BaseAddon) this, 1874, 2, 0, 15, 1443, -1, "", 1);// 135
			AddComplexComponent( (BaseAddon) this, 1874, 2, 1, 15, 1443, -1, "", 1);// 136
			AddComplexComponent( (BaseAddon) this, 1874, 2, 2, 15, 1443, -1, "", 1);// 137
			AddComplexComponent( (BaseAddon) this, 1874, 2, 3, 15, 1443, -1, "", 1);// 138
			AddComplexComponent( (BaseAddon) this, 1872, -2, 0, 15, 1443, -1, "", 1);// 139
			AddComplexComponent( (BaseAddon) this, 1872, -2, 1, 15, 1443, -1, "", 1);// 140
			AddComplexComponent( (BaseAddon) this, 1872, -2, 2, 15, 1443, -1, "", 1);// 141
			AddComplexComponent( (BaseAddon) this, 1872, -2, 3, 15, 1443, -1, "", 1);// 142
			AddComplexComponent( (BaseAddon) this, 1872, -2, 0, 10, 1443, -1, "", 1);// 143
			AddComplexComponent( (BaseAddon) this, 1872, -2, 1, 10, 1443, -1, "", 1);// 144
			AddComplexComponent( (BaseAddon) this, 1872, -2, 2, 10, 1443, -1, "", 1);// 145
			AddComplexComponent( (BaseAddon) this, 1872, -2, 3, 10, 1443, -1, "", 1);// 146
			AddComplexComponent( (BaseAddon) this, 1872, -1, 0, 10, 1443, -1, "", 1);// 147
			AddComplexComponent( (BaseAddon) this, 1872, -1, 1, 10, 1443, -1, "", 1);// 148
			AddComplexComponent( (BaseAddon) this, 1872, -1, 2, 10, 1443, -1, "", 1);// 149
			AddComplexComponent( (BaseAddon) this, 1872, -1, 3, 10, 1443, -1, "", 1);// 150
			AddComplexComponent( (BaseAddon) this, 1872, -4, 0, 10, 1443, -1, "", 1);// 151
			AddComplexComponent( (BaseAddon) this, 1872, -4, 1, 10, 1443, -1, "", 1);// 152
			AddComplexComponent( (BaseAddon) this, 1872, -4, 2, 10, 1443, -1, "", 1);// 153
			AddComplexComponent( (BaseAddon) this, 1872, -4, 3, 10, 1443, -1, "", 1);// 154
			AddComplexComponent( (BaseAddon) this, 1872, -3, 0, 10, 1443, -1, "", 1);// 155
			AddComplexComponent( (BaseAddon) this, 1872, -3, 1, 10, 1443, -1, "", 1);// 156
			AddComplexComponent( (BaseAddon) this, 1872, -3, 2, 10, 1443, -1, "", 1);// 157
			AddComplexComponent( (BaseAddon) this, 1872, -3, 3, 10, 1443, -1, "", 1);// 158
			AddComplexComponent( (BaseAddon) this, 1872, -3, 0, 5, 1443, -1, "", 1);// 159
			AddComplexComponent( (BaseAddon) this, 1872, -3, 1, 5, 1443, -1, "", 1);// 160
			AddComplexComponent( (BaseAddon) this, 1872, -3, 2, 5, 1443, -1, "", 1);// 161
			AddComplexComponent( (BaseAddon) this, 1872, -3, 3, 5, 1443, -1, "", 1);// 162
			AddComplexComponent( (BaseAddon) this, 1872, -3, 0, 15, 1443, -1, "", 1);// 163
			AddComplexComponent( (BaseAddon) this, 1872, -3, 1, 15, 1443, -1, "", 1);// 164
			AddComplexComponent( (BaseAddon) this, 1872, -3, 2, 15, 1443, -1, "", 1);// 165
			AddComplexComponent( (BaseAddon) this, 1872, -3, 3, 15, 1443, -1, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 18113, -1, 3, 20, 1443, -1, "", 1);// 167
			AddComplexComponent( (BaseAddon) this, 18113, 0, 3, 20, 1443, -1, "", 1);// 168
			AddComplexComponent( (BaseAddon) this, 18113, 3, 3, 12, 1443, -1, "", 1);// 169
			AddComplexComponent( (BaseAddon) this, 18113, 2, 3, 17, 1443, -1, "", 1);// 170
			AddComplexComponent( (BaseAddon) this, 1872, -4, 3, 15, 1443, -1, "", 1);// 171
			AddComplexComponent( (BaseAddon) this, 1872, -4, 0, 15, 1443, -1, "", 1);// 172
			AddComplexComponent( (BaseAddon) this, 1872, -4, 1, 15, 1443, -1, "", 1);// 173
			AddComplexComponent( (BaseAddon) this, 1872, -4, 2, 15, 1443, -1, "", 1);// 174
			AddComplexComponent( (BaseAddon) this, 1872, -4, 0, 5, 1443, -1, "", 1);// 175
			AddComplexComponent( (BaseAddon) this, 1872, -4, 1, 5, 1443, -1, "", 1);// 176
			AddComplexComponent( (BaseAddon) this, 1872, -4, 2, 5, 1443, -1, "", 1);// 177
			AddComplexComponent( (BaseAddon) this, 1872, -4, 3, 5, 1443, -1, "", 1);// 178
			AddComplexComponent( (BaseAddon) this, 17706, 4, 3, 46, 1443, -1, "", 1);// 179
			AddComplexComponent( (BaseAddon) this, 17707, 4, 2, 57, 1443, -1, "", 1);// 180
			AddComplexComponent( (BaseAddon) this, 17707, 4, 1, 57, 1443, -1, "", 1);// 181
			AddComplexComponent( (BaseAddon) this, 17707, 4, 0, 57, 1443, -1, "", 1);// 182
			AddComplexComponent( (BaseAddon) this, 17706, 1, 3, 45, 1443, -1, "", 1);// 183
			AddComplexComponent( (BaseAddon) this, 17706, -2, 3, 47, 1443, -1, "", 1);// 184
			AddComplexComponent( (BaseAddon) this, 17707, 1, 2, 54, 1443, -1, "", 1);// 185
			AddComplexComponent( (BaseAddon) this, 17707, -2, 2, 56, 1443, -1, "", 1);// 186
			AddComplexComponent( (BaseAddon) this, 17707, 1, 1, 54, 1443, -1, "", 1);// 187
			AddComplexComponent( (BaseAddon) this, 17707, -2, 1, 57, 1443, -1, "", 1);// 188
			AddComplexComponent( (BaseAddon) this, 17707, 1, 0, 53, 1443, -1, "", 1);// 189
			AddComplexComponent( (BaseAddon) this, 17707, -2, 0, 57, 1443, -1, "", 1);// 190
			AddComplexComponent( (BaseAddon) this, 17709, -2, 3, 20, 1443, -1, "", 1);// 191
			AddComplexComponent( (BaseAddon) this, 17709, 1, 3, 20, 1443, -1, "", 1);// 192
			AddComplexComponent( (BaseAddon) this, 17709, 4, 3, 10, 1443, -1, "", 1);// 193
			AddComplexComponent( (BaseAddon) this, 17298, -3, 4, 9, 1443, -1, "", 1);// 194
			AddComplexComponent( (BaseAddon) this, 17298, -1, 4, 8, 1443, -1, "", 1);// 195
			AddComplexComponent( (BaseAddon) this, 17298, 1, 4, 8, 1443, -1, "", 1);// 196
			AddComplexComponent( (BaseAddon) this, 17298, 3, 4, 7, 1443, -1, "", 1);// 197
			AddComplexComponent( (BaseAddon) this, 17319, -3, 4, 0, 1443, -1, "", 1);// 198
			AddComplexComponent( (BaseAddon) this, 17319, -1, 4, 0, 1443, -1, "", 1);// 199
			AddComplexComponent( (BaseAddon) this, 17319, 1, 4, 0, 1443, -1, "", 1);// 200
			AddComplexComponent( (BaseAddon) this, 17319, 3, 4, 0, 1443, -1, "", 1);// 201

		}

		public SpellcrafterFortressBridgeAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SpellcrafterFortressBridgeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SpellcrafterFortressBridgeAddon();
			}
		}

		[Constructable]
		public SpellcrafterFortressBridgeAddonDeed()
		{
			Name = "SpellcrafterFortressBridge";
		}

		public SpellcrafterFortressBridgeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}