
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class JediRoof2Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {20267, 1, -1, 0}, {20291, -2, 2, 0}, {20295, 2, 2, 0}// 1	2	3	
			, {20256, -1, -2, 0}, {20294, 1, 2, 0}, {20281, -3, 1, 0}// 4	5	6	
			, {20250, 2, -3, 0}, {20249, 1, -3, 0}, {20277, 2, 0, 0}// 7	8	9	
			, {20245, -3, -3, 0}, {20246, -2, -3, 0}, {20251, 3, -3, 0}// 10	11	12	
			, {20260, 3, -2, 0}, {20263, -3, -1, 0}, {20272, -3, 0, 0}// 13	14	15	
			, {20259, 2, -2, 0}, {20238, -1, -4, 0}, {20257, 0, -2, 0}// 16	17	18	
			, {20254, -3, -2, 0}, {20286, 2, 1, 0}, {20289, -4, 2, 0}// 19	20	21	
			, {20276, 1, 0, 0}, {20258, 1, -2, 0}, {20255, -2, -2, 0}// 22	23	24	
			, {20287, 3, 1, 0}, {20240, 1, -4, 0}, {20278, 3, 0, 0}// 25	26	27	
			, {20284, 0, 1, 0}, {20239, 0, -4, 0}, {20244, -4, -3, 0}// 28	29	30	
			, {20283, -1, 1, 0}, {20253, -4, -2, 0}, {20241, 2, -4, 0}// 31	32	33	
			, {20242, 3, -4, 0}, {20299, -3, 3, 0}, {20266, 0, -1, 0}// 34	35	36	
			, {20274, -1, 0, 0}, {20247, -1, -3, 0}, {20310, -1, 4, 0}// 37	38	39	
			, {20298, -4, 3, 0}, {20290, -3, 2, 0}, {20302, 0, 3, 0}// 40	41	42	
			, {20303, 1, 3, 0}, {20300, -2, 3, 0}, {20248, 0, -3, 0}// 43	44	45	
			, {20282, -2, 1, 0}, {20269, 3, -1, 0}, {20237, -2, -4, 0}// 46	47	48	
			, {20262, -4, -1, 0}, {20271, -4, 0, 0}, {20264, -2, -1, 0}// 49	50	51	
			, {20275, 0, 0, 0}, {20292, -1, 2, 0}, {20280, -4, 1, 0}// 52	53	54	
			, {20293, 0, 2, 0}, {20235, -4, -4, 0}, {20311, 5, 4, 0}// 55	56	57	
			, {20236, -3, -4, 0}, {20309, -2, 4, 0}, {20308, -3, 4, 0}// 58	59	60	
			, {20301, -1, 3, 0}, {20307, -4, 4, 0}, {20268, 2, -1, 0}// 61	62	63	
			, {20285, 1, 1, 0}, {20265, -1, -1, 0}, {20273, -2, 0, 0}// 64	65	66	
			, {20270, 4, -1, 0}, {20261, 4, -2, 0}, {20252, 4, -3, 0}// 67	68	69	
			, {20243, 4, -4, 0}// 70	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new JediRoof2AddonDeed();
			}
		}

		[ Constructable ]
		public JediRoof2Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public JediRoof2Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class JediRoof2AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new JediRoof2Addon();
			}
		}

		[Constructable]
		public JediRoof2AddonDeed()
		{
			Name = "JediRoof2";
		}

		public JediRoof2AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}