////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class GrailEntranceAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1900, 0, -5, 100}, {1900, 1, -5, 100}, {1183, 0, -5, 0}// 4	6	10	
			, {1183, 1, -5, 0}, {1900, 0, -3, 100}, {366, 1, 1, 80}// 11	17	18	
			, {1900, 0, 3, 100}, {405, 2, 3, 55}, {351, 1, 2, 40}// 19	22	23	
			, {1901, 3, 4, 105}, {1900, 2, 4, 55}, {404, 2, -3, 55}// 24	25	30	
			, {1900, 2, -4, 55}, {351, 1, 3, 80}, {1902, 2, -1, 53}// 34	35	36	
			, {1900, 0, 2, 0}, {1902, 2, 0, 53}, {1900, 3, 5, 100}// 38	39	42	
			, {1900, 1, 5, 100}, {1900, 3, -4, 100}, {353, 1, 1, 60}// 45	46	48	
			, {1900, 1, -4, 100}, {400, 0, 2, 31}, {351, 1, 4, 40}// 49	50	51	
			, {1900, 0, 5, 100}, {1900, 0, -2, 100}, {1902, 2, 1, 53}// 54	55	57	
			, {1900, 1, -3, 100}, {1900, 0, -1, 100}, {1910, 2, 2, 53}// 58	60	61	
			, {1900, 0, 0, 100}, {1900, 2, -3, 50}, {1900, 3, -3, 100}// 62	65	67	
			, {401, 0, 0, 31}, {1900, 3, 4, 100}, {1900, 0, 4, 100}// 69	70	71	
			, {1900, 3, -2, 100}, {351, -1, 2, 40}, {1900, 1, 3, 100}// 72	74	75	
			, {351, 1, -2, 40}, {351, -1, 3, 40}, {351, -1, 1, 40}// 76	77	78	
			, {1900, 0, 1, 100}, {352, 0, 2, 20}, {389, 0, 1, 35}// 79	83	84	
			, {1900, 0, 2, 100}, {351, 0, 2, 80}, {351, 1, 0, 40}// 88	89	100	
			, {1183, 2, 5, 0}, {1903, 3, -2, 105}, {351, 1, 4, 0}// 101	102	106	
			, {1902, 1, 0, 100}, {351, 1, 4, 80}, {353, -1, -3, 20}// 109	111	113	
			, {389, 0, 0, 35}, {351, 1, -4, 40}, {1912, 2, -2, 53}// 116	120	123	
			, {351, -1, 0, 60}, {351, -2, -3, 60}, {1183, -1, -4, 0}// 136	138	139	
			, {1183, -1, -3, 0}, {1183, -1, -2, 0}, {1183, -1, -1, 0}// 140	141	142	
			, {1183, -1, 0, 0}, {1183, -1, 1, 0}, {1183, -1, 2, 0}// 143	144	145	
			, {1183, -1, 3, 0}, {1183, -1, 4, 0}, {1183, 0, -4, 0}// 146	147	148	
			, {1183, 0, -3, 0}, {1183, 0, 2, 0}, {1183, 0, 3, 0}// 149	154	155	
			, {1183, 0, 4, 0}, {1183, 0, 5, 0}, {1183, 1, -4, 0}// 156	157	159	
			, {1183, 1, -3, 0}, {1183, 1, 3, 0}, {1183, 1, 4, 0}// 160	163	164	
			, {1183, 1, 5, 0}, {1183, 2, -3, 0}, {1183, 2, -2, 0}// 165	167	168	
			, {1183, 2, 2, 0}, {1183, 2, 4, 0}, {351, -1, 2, 0}// 169	171	173	
			, {1900, 3, 6, 100}, {351, -1, -1, 40}, {351, -1, -1, 80}// 178	180	181	
			, {404, 2, -3, 75}, {1910, 1, 1, 100}, {1912, 1, -1, 100}// 182	183	184	
			, {351, 1, 1, 40}, {351, -1, 2, 20}, {351, -1, 0, 40}// 190	194	195	
			, {351, -1, -2, 20}, {351, -1, -2, 80}, {351, -1, 1, 60}// 196	198	199	
			, {351, -1, 4, 40}, {351, 0, 1, 80}, {1900, 1, 4, 100}// 202	204	206	
			, {351, -1, 0, 0}, {351, -1, -2, 40}, {1900, 0, -4, 100}// 209	210	212	
			, {405, 2, 3, 75}, {351, 1, -4, 0}, {351, -1, 2, 60}// 214	217	218	
		};

		public override BaseAddonDeed Deed
		{
			get
			{
				return new GrailEntranceAddonDeed();
			}
		}

		[ Constructable ]
		public GrailEntranceAddon()
		{
            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );

			AddComplexComponent( (BaseAddon) this, 12268, 2, -5, 0, 350, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 351, 1, -5, 0, 1510, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 405, 2, -5, 55, 1511, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 1900, 2, -5, 50, 1511, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 351, 1, -5, 20, 1510, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 351, 1, -5, 80, 1510, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 405, 2, -5, 75, 1511, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1183, 2, -5, 0, 1118, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 351, 1, -5, 40, 1512, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 351, 1, -5, 60, 1512, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 6086, 3, -5, 0, 1118, -1, "Sand", 1);// 15
			AddComplexComponent( (BaseAddon) this, 353, 1, -1, 60, 1510, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 5023, 1, -3, 0, 1510, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 6087, 3, 4, 0, 1118, -1, "Sand", 1);// 21
			AddComplexComponent( (BaseAddon) this, 1900, 2, -2, 50, 1511, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 12268, 2, 5, 0, 350, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 352, 0, -3, 40, 1510, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 1900, 2, 1, 50, 1511, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 6087, 3, -2, 0, 1118, -1, "Sand", 1);// 31
			AddComplexComponent( (BaseAddon) this, 352, 0, -3, 0, 1512, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 6092, 3, 3, 0, 1118, -1, "Sand", 1);// 33
			AddComplexComponent( (BaseAddon) this, 6918, 1, -3, 105, 1510, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 6086, 3, 2, 0, 1118, -1, "Sand", 1);// 40
			AddComplexComponent( (BaseAddon) this, 5024, 2, -4, 0, 1510, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 351, 1, 3, 0, 1512, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 1900, 2, -1, 50, 1511, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 1900, 2, -4, 50, 1511, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 6086, 3, -2, 0, 1118, -1, "Sand", 1);// 52
			AddComplexComponent( (BaseAddon) this, 351, 1, -4, 80, 1510, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 351, 0, 0, 80, 1512, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 1900, 2, 4, 50, 1511, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 351, 1, -1, 40, 1510, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 4646, 2, -4, 63, 1512, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 6087, 3, 2, 0, 1119, -1, "Sand", 1);// 66
			AddComplexComponent( (BaseAddon) this, 351, 1, 4, 60, 1512, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 404, 2, 5, 75, 1511, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 404, 2, 5, 55, 1511, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 353, 1, -1, 80, 1510, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 6087, 1, -2, 1, 1118, -1, "Sand", 1);// 82
			AddComplexComponent( (BaseAddon) this, 6092, 3, 1, 0, 1119, -1, "Sand", 1);// 85
			AddComplexComponent( (BaseAddon) this, 367, 1, 0, 80, 1510, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 7023, 0, -2, 0, 46, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 1900, 2, 0, 50, 1511, -1, "", 1);// 90
			AddComplexComponent( (BaseAddon) this, 351, -1, 1, 20, 3000, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 350, 1, 5, 80, 1510, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 351, -1, 0, 20, 3000, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 5024, 2, 3, 0, 1510, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 350, 1, -3, 80, 1512, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 6913, 0, -3, 105, 45, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 350, 1, 5, 60, 1510, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 12268, 2, -2, 0, 351, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 5023, 1, 4, 0, 1510, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 1900, 2, 2, 50, 1511, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 5022, 2, -3, 0, 1512, -1, "", 1);// 104
			AddComplexComponent( (BaseAddon) this, 11538, 1, 0, 60, 1512, -1, "", 1);// 105
			AddComplexComponent( (BaseAddon) this, 350, 1, 5, 0, 1510, -1, "", 1);// 107
			AddComplexComponent( (BaseAddon) this, 4648, 1, 0, 104, 1510, -1, "", 1);// 108
			AddComplexComponent( (BaseAddon) this, 351, -1, 1, 0, 2743, -1, "", 1);// 110
			AddComplexComponent( (BaseAddon) this, 7020, 2, 4, 60, 46, -1, "", 1);// 112
			AddComplexComponent( (BaseAddon) this, 5022, 2, 4, 0, 1512, -1, "", 1);// 114
			AddComplexComponent( (BaseAddon) this, 352, 0, 5, 0, 1510, -1, "", 1);// 115
			AddComplexComponent( (BaseAddon) this, 351, 1, 3, 40, 1512, -1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 351, 1, 3, 20, 1512, -1, "", 1);// 118
			AddComplexComponent( (BaseAddon) this, 351, 1, -4, 60, 1512, -1, "", 1);// 119
			AddComplexComponent( (BaseAddon) this, 351, 1, -4, 20, 1510, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 351, -1, -1, 0, 3000, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 350, 1, -3, 20, 1512, -1, "", 1);// 124
			AddComplexComponent( (BaseAddon) this, 350, 1, -3, 40, 1510, -1, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 6079, 2, 0, 0, 1119, -1, "Sand", 1);// 126
			AddComplexComponent( (BaseAddon) this, 352, 0, -3, 60, 1512, -1, "", 1);// 127
			AddComplexComponent( (BaseAddon) this, 352, 0, -3, 80, 1512, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 352, 0, 5, 80, 1510, -1, "", 1);// 129
			AddComplexComponent( (BaseAddon) this, 350, 1, 5, 20, 1510, -1, "", 1);// 130
			AddComplexComponent( (BaseAddon) this, 350, 1, -3, 60, 1510, -1, "", 1);// 131
			AddComplexComponent( (BaseAddon) this, 6079, 1, 1, 0, 1118, -1, "Sand", 1);// 132
			AddComplexComponent( (BaseAddon) this, 351, 1, 4, 20, 1512, -1, "", 1);// 133
			AddComplexComponent( (BaseAddon) this, 6079, 2, -1, 0, 1118, -1, "Sand", 1);// 134
			AddComplexComponent( (BaseAddon) this, 351, -1, -2, 0, 1510, -1, "", 1);// 135
			AddComplexComponent( (BaseAddon) this, 351, -1, -1, 60, 1512, -1, "", 1);// 137
			AddComplexComponent( (BaseAddon) this, 1183, 0, -2, 0, 1119, -1, "", 1);// 150
			AddComplexComponent( (BaseAddon) this, 1183, 0, -1, 0, 1118, -1, "", 1);// 151
			AddComplexComponent( (BaseAddon) this, 1183, 0, 0, 0, 1118, -1, "", 1);// 152
			AddComplexComponent( (BaseAddon) this, 1183, 0, 1, 0, 1118, -1, "", 1);// 153
			AddComplexComponent( (BaseAddon) this, 6092, 3, -1, 0, 1118, -1, "Sand", 1);// 158
			AddComplexComponent( (BaseAddon) this, 1183, 1, -2, 0, 1119, -1, "", 1);// 161
			AddComplexComponent( (BaseAddon) this, 1183, 1, 2, 0, 1510, -1, "", 1);// 162
			AddComplexComponent( (BaseAddon) this, 1183, 2, -4, 0, 1119, -1, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 1183, 2, 3, 0, 1119, -1, "", 1);// 170
			AddComplexComponent( (BaseAddon) this, 6079, 1, 0, 0, 1119, -1, "Sand", 1);// 172
			AddComplexComponent( (BaseAddon) this, 6079, 2, 1, 0, 1119, -1, "Sand", 1);// 174
			AddComplexComponent( (BaseAddon) this, 352, 0, 3, 0, 1511, -1, "", 1);// 175
			AddComplexComponent( (BaseAddon) this, 12269, 2, 2, 0, 351, -1, "", 1);// 176
			AddComplexComponent( (BaseAddon) this, 351, -1, -2, 60, 1512, -1, "", 1);// 177
			AddComplexComponent( (BaseAddon) this, 6087, 0, -1, 0, 1118, -1, "Sand", 1);// 179
			AddComplexComponent( (BaseAddon) this, 352, 0, 5, 60, 1510, -1, "", 1);// 185
			AddComplexComponent( (BaseAddon) this, 352, 0, -3, 20, 1512, -1, "", 1);// 186
			AddComplexComponent( (BaseAddon) this, 6092, 3, -4, 0, 1119, -1, "Sand", 1);// 187
			AddComplexComponent( (BaseAddon) this, 1900, 2, 3, 50, 1511, -1, "", 1);// 188
			AddComplexComponent( (BaseAddon) this, 6092, 3, -3, 0, 1118, -1, "Sand", 1);// 189
			AddComplexComponent( (BaseAddon) this, 351, -1, -1, 20, 3000, -1, "", 1);// 191
			AddComplexComponent( (BaseAddon) this, 351, 1, 3, 60, 1512, -1, "", 1);// 192
			AddComplexComponent( (BaseAddon) this, 6086, 3, 4, 0, 1118, -1, "Sand", 1);// 193
			AddComplexComponent( (BaseAddon) this, 352, 0, 5, 20, 1510, -1, "", 1);// 197
			AddComplexComponent( (BaseAddon) this, 350, 1, 5, 40, 1510, -1, "", 1);// 200
			AddComplexComponent( (BaseAddon) this, 350, 1, -3, 0, 1510, -1, "", 1);// 201
			AddComplexComponent( (BaseAddon) this, 6081, 0, -2, 0, 1118, -1, "Sand", 1);// 203
			AddComplexComponent( (BaseAddon) this, 6087, 3, 5, 0, 1118, -1, "Sand", 1);// 205
			AddComplexComponent( (BaseAddon) this, 7020, 1, 6, 20, 1450, -1, "", 1);// 207
			AddComplexComponent( (BaseAddon) this, 5019, 2, 4, 63, 1512, -1, "", 1);// 208
			AddComplexComponent( (BaseAddon) this, 352, 0, 5, 40, 1510, -1, "", 1);// 211
			AddComplexComponent( (BaseAddon) this, 6079, 1, -1, 0, 1119, -1, "Sand", 1);// 213
			AddComplexComponent( (BaseAddon) this, 1900, 2, 5, 50, 1511, -1, "", 1);// 215
			AddComplexComponent( (BaseAddon) this, 6092, 3, 0, 0, 1118, -1, "Sand", 1);// 216
		}

		public GrailEntranceAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class GrailEntranceAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new GrailEntranceAddon();
			}
		}

		[Constructable]
		public GrailEntranceAddonDeed()
		{
			Name = "GrailEntrance";
		}

		public GrailEntranceAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}