
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class BBRooftopAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4676, -5, -5, 2}, {6025, -5, 0, 2}, {6024, -5, -2, 3}// 2	3	4	
			, {6013, -8, 0, 2}, {6013, -5, -5, 2}, {6023, -6, -2, 2}// 7	9	10	
			, {6024, -5, -2, 2}, {4998, -5, -1, 1}, {12278, -6, -5, 2}// 11	13	14	
			, {6013, -8, -2, 2}, {4998, -6, -2, 0}, {6013, -4, 0, 2}// 15	16	17	
			, {3142, -4, -3, 2}, {11539, -4, -5, 7}, {6019, -5, 0, 2}// 19	20	22	
			, {4998, -5, -2, 0}, {6021, -6, -1, 2}, {6013, -7, -3, 2}// 23	24	25	
			, {6020, -5, -2, 2}, {6021, -6, 0, 2}, {4998, -5, 0, 1}// 26	27	28	
			, {6013, -8, -3, 2}, {6013, -4, -2, 2}, {6013, -4, -3, 2}// 30	31	32	
			, {3310, -5, -4, 2}, {6013, -7, -2, 2}, {6013, -8, -1, 2}// 35	36	37	
			, {12278, -4, -5, 2}, {4998, -6, 0, 1}, {11539, -6, -5, 7}// 38	39	41	
			, {6013, -4, -1, 2}, {6013, -7, 0, 2}, {6013, -6, -3, 2}// 44	45	46	
			, {6019, -5, -1, 2}, {3142, -7, -3, 2}, {6013, -4, -7, 2}// 47	49	50	
			, {6013, -4, -6, 2}, {6013, -4, -5, 2}, {6013, -8, -6, 2}// 51	54	55	
			, {6013, -4, -4, 2}, {6013, -8, -7, 2}, {6013, -4, -8, 2}// 56	57	59	
			, {6013, -5, -8, 2}, {6013, -8, -4, 2}, {6013, -7, -5, 2}// 61	63	64	
			, {6013, -7, -7, 2}, {6013, -7, -6, 2}, {6013, -8, -5, 2}// 65	66	67	
			, {6013, -5, -7, 2}, {6013, -6, -6, 2}, {6013, -6, -7, 2}// 68	69	70	
			, {6013, -7, -4, 2}, {6013, -6, -4, 2}, {6013, -6, -5, 2}// 71	72	73	
			, {6013, -4, -5, 2}, {6013, -5, -6, 2}, {6013, -5, -4, 2}// 74	77	78	
			, {4998, -6, -1, 1}, {6013, -7, -1, 2}, {6013, -5, -3, 2}// 79	80	81	
			, {6023, -6, -2, 3}, {6013, -6, 6, 2}, {6018, -4, 6, 2}// 82	84	85	
			, {6018, -4, 5, 2}, {6013, -6, 6, 2}, {4998, -5, 3, 1}// 87	88	90	
			, {6021, -6, 5, 2}, {6013, -8, 8, 2}, {6022, -6, 4, 2}// 91	92	93	
			, {6013, -4, 3, 2}, {4998, -6, 6, 2}, {6019, -5, 3, 2}// 95	96	97	
			, {6018, -4, 5, 2}, {6021, -6, 3, 2}, {4998, -5, 5, 2}// 99	100	101	
			, {6013, -4, 5, 2}, {4998, -6, 1, 0}, {4998, -5, 2, 0}// 102	103	104	
			, {6025, -5, 4, 2}, {6013, -8, 2, 2}, {4998, -4, 5, 2}// 105	106	107	
			, {4998, -6, 2, 0}, {6019, -5, 2, 2}, {4998, -5, 1, 0}// 108	109	110	
			, {6024, -5, 3, 2}, {6022, -6, 6, 2}, {6013, -4, 1, 2}// 111	112	113	
			, {6021, -6, 4, 2}, {6019, -5, 1, 2}, {6019, -5, 2, 2}// 114	115	116	
			, {6013, -6, 8, 2}, {4998, -6, 3, 0}, {6025, -5, 6, 3}// 118	119	121	
			, {6022, -4, 5, 2}, {6020, -4, 4, 2}, {6021, -6, 5, 2}// 122	123	124	
			, {6022, -6, 6, 2}, {6020, -5, 1, 2}, {6013, -7, 8, 2}// 127	130	131	
			, {6025, -5, 2, 3}, {4998, -4, 4, 2}, {6023, -6, 1, 2}// 132	133	135	
			, {6013, -8, 4, 2}, {6013, -4, 8, 2}, {11536, -7, 3, 2}// 137	138	139	
			, {6024, -5, 5, 2}, {6013, -6, 7, 2}, {6013, -4, 7, 3}// 140	141	142	
			, {6013, -8, 6, 2}, {6013, -8, 5, 2}, {6013, -8, 3, 2}// 143	144	145	
			, {6013, -7, 3, 2}, {6013, -5, 8, 2}, {6013, -7, 2, 2}// 149	151	153	
			, {4998, -5, 6, 2}, {6013, -4, 2, 2}, {6013, -7, 1, 2}// 154	155	156	
			, {4998, -6, 5, 1}, {6013, -8, 5, 2}, {6013, -8, 1, 2}// 157	158	160	
			, {4998, -5, 4, 1}, {6021, -6, 1, 2}, {6013, -7, 6, 2}// 161	162	164	
			, {6023, -4, 4, 2}, {6013, -6, 5, 2}, {6013, -5, 8, 2}// 165	166	167	
			, {6025, -5, 7, 2}, {6013, -5, 5, 2}, {6013, -7, 7, 2}// 168	169	170	
			, {6013, -7, 4, 2}, {6019, -5, 3, 2}, {6013, -8, 7, 2}// 171	172	174	
			, {4998, -6, 4, 0}, {6013, -7, 5, 2}, {6013, -4, 4, 2}// 175	177	178	
			, {6023, -6, 5, 3}, {6013, -3, -1, 2}, {6013, -3, 0, 2}// 183	185	186	
			, {6013, -3, -2, 2}, {6013, -3, -3, 2}, {6013, 2, 0, 2}// 188	189	190	
			, {6013, 3, 0, 2}, {6013, -2, -1, 2}, {6013, -2, -2, 2}// 192	193	194	
			, {6013, -2, -3, 2}, {6013, 9, 0, 2}, {6013, -1, -1, 2}// 198	199	200	
			, {6013, 5, 0, 2}, {6013, -2, 0, 2}, {6013, -1, -3, 2}// 202	203	204	
			, {6013, 6, 0, 2}, {6013, -2, -7, 2}, {6013, -3, -4, 2}// 205	206	207	
			, {6013, -1, -7, 2}, {6013, -2, -8, 2}, {6013, -3, -5, 2}// 208	209	210	
			, {6013, -2, -6, 2}, {6013, -3, -7, 2}, {6013, -1, -8, 2}// 211	213	216	
			, {6013, -3, -6, 2}, {6013, -2, -4, 2}, {6013, -1, -6, 2}// 218	219	220	
			, {6013, -2, -5, 2}, {6013, -1, -5, 2}, {6013, -3, -8, 2}// 221	223	224	
			, {6013, -1, -4, 2}, {6013, -1, -2, 2}, {6018, 1, 5, 2}// 225	227	228	
			, {6024, 6, 4, 2}, {6025, -2, 5, 3}, {6018, -2, 5, 2}// 229	230	232	
			, {6013, 1, 8, 2}, {6013, -3, 6, 2}, {3150, -2, 7, 2}// 233	234	235	
			, {6018, 5, 5, 3}, {6013, 7, 3, 2}, {6018, -1, 5, 3}// 236	237	240	
			, {6013, -2, 7, 2}, {6013, -3, 1, 2}, {6021, 2, 4, 2}// 242	243	245	
			, {6013, 6, 8, 2}, {6013, -3, 1, 2}, {6013, -3, 5, 2}// 247	248	250	
			, {6013, 2, 6, 2}, {4998, -1, 4, 2}, {6013, 5, 3, 2}// 251	252	254	
			, {6013, 6, 4, 2}, {6020, 2, 4, 3}, {6024, -2, 4, 3}// 255	256	257	
			, {6013, -1, 3, 2}, {6013, -3, 2, 2}, {6013, 2, 8, 2}// 260	261	262	
			, {6019, -2, 5, 3}, {4998, 3, 4, 2}, {4998, 2, 4, 2}// 263	265	266	
			, {6013, 4, 4, 2}, {6013, 4, 6, 2}, {6025, -2, 5, 2}// 267	268	269	
			, {6013, 3, 1, 2}, {6013, 6, 1, 2}, {6013, 2, 2, 2}// 270	271	272	
			, {4998, 6, 5, 2}, {6013, 6, 6, 2}, {6013, 3, 2, 2}// 273	274	276	
			, {6013, 3, 4, 2}, {6013, 1, 4, 2}, {6013, 3, 5, 2}// 278	280	281	
			, {6013, 3, 7, 2}, {6013, 3, 6, 2}, {6013, 7, 1, 2}// 282	283	285	
			, {6020, 5, 4, 2}, {6018, 3, 5, 2}, {6013, 5, 8, 2}// 286	287	288	
			, {6013, -3, 7, 2}, {11535, 0, 5, 2}, {6018, -3, 5, 2}// 289	290	291	
			, {6013, 4, 3, 2}, {4998, 6, 4, 2}, {6018, 0, 5, 2}// 292	293	294	
			, {6021, -2, 4, 3}, {6013, 2, 7, 2}, {6013, 4, 2, 2}// 295	296	297	
			, {6013, 0, 8, 2}, {6022, 2, 5, 3}, {6013, -2, 3, 2}// 299	300	301	
			, {4998, 4, 5, 2}, {4998, -3, 5, 2}, {6013, 1, 7, 2}// 303	304	305	
			, {6013, 1, 5, 2}, {6020, 1, 4, 2}, {6020, 3, 4, 3}// 306	307	308	
			, {6013, 7, 4, 2}, {6013, 4, 5, 2}, {6013, -1, 2, 2}// 309	310	311	
			, {6018, -1, 5, 2}, {6013, -2, 2, 2}, {6018, 2, 5, 2}// 313	314	315	
			, {6013, 5, 5, 2}, {6018, -1, 6, 2}, {6020, -2, 4, 2}// 317	318	321	
			, {6022, 2, 5, 4}, {4998, 5, 5, 2}, {6013, -3, 4, 2}// 322	323	325	
			, {6013, 6, 6, 2}, {6019, -1, 4, 2}, {6013, 6, 3, 2}// 327	328	330	
			, {6020, -1, 4, 2}, {6013, 5, 6, 2}, {6018, -1, 5, 2}// 331	334	335	
			, {6018, -3, 5, 2}, {6024, 6, 4, 2}, {6013, -1, 4, 2}// 336	338	340	
			, {6013, 5, 7, 2}, {6020, 4, 4, 2}, {6013, 3, 3, 2}// 341	344	345	
			, {6013, 4, 1, 2}, {6018, -2, 5, 2}, {6013, 1, 2, 2}// 346	348	349	
			, {6013, -2, 8, 2}, {6013, -2, 6, 2}, {6013, -2, 4, 2}// 350	351	352	
			, {6013, 6, 2, 2}, {6013, -1, 8, 2}, {6024, -3, 4, 3}// 353	354	356	
			, {6013, -3, 3, 2}, {6013, 4, 6, 2}, {6018, 0, 5, 2}// 357	358	359	
			, {6013, 0, 1, 2}, {6013, 1, 1, 2}, {6019, -1, 5, 2}// 360	361	362	
			, {6018, 4, 5, 2}, {6013, 5, 1, 2}, {6020, 5, 4, 2}// 363	364	365	
			, {6018, 1, 5, 2}, {6013, 7, 5, 2}, {6013, 9, 1, 2}// 366	367	368	
			, {6013, 9, 7, 2}, {6013, 8, 2, 2}, {6013, 9, 4, 2}// 369	370	371	
			, {6013, 9, 2, 2}, {6013, 9, 6, 2}, {6013, 8, 8, 2}// 373	374	379	
			, {6013, 8, 1, 2}, {6013, 9, 5, 2}, {6013, 8, 4, 2}// 380	381	382	
			, {6013, 8, 5, 2}, {6013, 8, 6, 2}, {6013, 8, 7, 2}// 383	384	386	
			, {6013, 8, 3, 2}, {6013, 9, 3, 2}, {6013, 9, 8, 2}// 387	389	390	
			, {4998, -2, 4, 2}, {4998, -3, 4, 2}, {3142, -3, 3, 2}// 391	392	393	
			, {6013, 7, 2, 2}, {6013, 1, 6, 2}, {6013, -1, 5, 2}// 394	397	398	
			, {6013, 6, 7, 2}, {6013, 0, 4, 2}, {6025, 6, 5, 2}// 399	400	401	
			, {6013, 0, 7, 2}, {6013, 0, 6, 2}, {6013, -3, 8, 2}// 402	403	404	
			, {6013, 0, 5, 2}, {6013, 7, 6, 2}, {6013, 2, 5, 2}// 405	406	407	
			, {6013, 4, 7, 2}, {6013, 5, 5, 2}, {4998, 5, 4, 2}// 408	409	411	
			, {4998, 2, 5, 2}, {6013, 5, 4, 2}, {6013, 5, 2, 2}// 412	413	414	
			, {6013, 1, 3, 2}, {6013, -1, 1, 2}, {6013, 7, 8, 2}// 415	416	417	
			, {4998, -2, 5, 2}, {6013, 7, 7, 2}, {6013, 2, 1, 2}// 418	419	420	
			, {4998, -1, 5, 2}, {6013, 0, 4, 2}, {6013, -1, 7, 2}// 421	423	424	
			, {6018, 2, 5, 2}, {6020, -3, 4, 2}, {6013, -2, 5, 2}// 425	426	427	
			, {4998, 3, 5, 2}, {4998, 4, 4, 2}, {6013, 0, 3, 2}// 430	431	432	
			, {6013, 0, 2, 2}, {6020, 0, 4, 2}, {6013, 2, 3, 2}// 433	434	435	
			, {3272, 0, 3, 2}, {6013, 4, 8, 2}, {6022, -1, 5, 3}// 437	438	439	
			, {6024, -3, 4, 2}, {6013, 3, 8, 2}, {3144, 1, 3, 2}// 440	441	442	
			, {6013, -2, 1, 2}// 444	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new BBRooftopAddonDeed();
			}
		}

		[ Constructable ]
		public BBRooftopAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 3216, -8, -2, 2, 2210, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 3391, -8, -7, 8, 2212, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 3218, -8, -1, 3, 2211, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 2916, -7, 0, 2, 966, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 3217, -8, 0, 3, 2209, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 3258, -7, -3, 2, 2211, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 3159, -5, -4, 2, 2212, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 2915, -7, -1, 2, 966, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 3244, -7, -2, 3, 2212, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 3392, -7, -5, 2, 2212, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 2915, -4, -1, 2, 966, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 3216, -8, -3, 2, 2208, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 2916, -4, 0, 2, 966, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 7870, -5, -2, 2, 2212, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 3216, -4, -7, 2, 2210, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 3216, -8, -6, 2, 2211, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 3216, -8, -7, 2, 2212, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 3216, -5, -7, 2, 2210, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 3216, -6, -7, 2, 2208, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 3216, -8, -4, 2, 2210, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 3216, -8, -5, 2, 2210, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 3216, -7, -7, 2, 2208, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 3270, -4, 3, 2, 2212, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 3217, -8, 3, 2, 2212, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 3217, -7, 2, 2, 2212, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 3216, -8, 6, 2, 2208, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 2920, -5, 6, 2, 966, -1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 3391, -8, 8, 8, 2212, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 3216, -8, 5, 2, 2209, -1, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 3216, -7, 8, 2, 2212, -1, "", 1);// 126
			AddComplexComponent( (BaseAddon) this, 3216, -8, 4, 2, 2211, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 3216, -8, 3, 2, 2210, -1, "", 1);// 129
			AddComplexComponent( (BaseAddon) this, 3216, -8, 8, 2, 2212, -1, "", 1);// 134
			AddComplexComponent( (BaseAddon) this, 3244, -7, 4, 2, 2212, -1, "", 1);// 136
			AddComplexComponent( (BaseAddon) this, 3217, -5, 8, 2, 2210, -1, "", 1);// 146
			AddComplexComponent( (BaseAddon) this, 2921, -6, 6, 2, 966, -1, "", 1);// 147
			AddComplexComponent( (BaseAddon) this, 3217, -8, 1, 2, 2212, -1, "", 1);// 148
			AddComplexComponent( (BaseAddon) this, 3216, -8, 7, 2, 2211, -1, "", 1);// 150
			AddComplexComponent( (BaseAddon) this, 3217, -8, 2, 2, 2212, -1, "", 1);// 152
			AddComplexComponent( (BaseAddon) this, 2914, -4, 1, 2, 966, -1, "", 1);// 159
			AddComplexComponent( (BaseAddon) this, 3216, -6, 8, 2, 2210, -1, "", 1);// 163
			AddComplexComponent( (BaseAddon) this, 2914, -7, 1, 2, 966, -1, "", 1);// 173
			AddComplexComponent( (BaseAddon) this, 3216, -4, 8, 2, 2209, -1, "", 1);// 176
			AddComplexComponent( (BaseAddon) this, 3258, -6, 2, 3, 2211, -1, "", 1);// 179
			AddComplexComponent( (BaseAddon) this, 3254, -5, 6, 2, 2211, -1, "", 1);// 180
			AddComplexComponent( (BaseAddon) this, 3244, -6, 5, 3, 2211, -1, "", 1);// 181
			AddComplexComponent( (BaseAddon) this, 3244, -4, 6, 3, 2211, -1, "", 1);// 182
			AddComplexComponent( (BaseAddon) this, 3392, -3, -5, 2, 2212, -1, "", 1);// 184
			AddComplexComponent( (BaseAddon) this, 3216, -2, -3, 2, 2212, -1, "", 1);// 187
			AddComplexComponent( (BaseAddon) this, 3216, -2, -1, 2, 2209, -1, "", 1);// 191
			AddComplexComponent( (BaseAddon) this, 3216, -2, -2, 2, 2211, -1, "", 1);// 195
			AddComplexComponent( (BaseAddon) this, 3249, -3, -6, 2, 2212, -1, "", 1);// 196
			AddComplexComponent( (BaseAddon) this, 3218, -2, 0, 2, 2208, -1, "", 1);// 197
			AddComplexComponent( (BaseAddon) this, 3216, -2, 0, 2, 2208, -1, "", 1);// 201
			AddComplexComponent( (BaseAddon) this, 3216, -2, -4, 2, 2211, -1, "", 1);// 212
			AddComplexComponent( (BaseAddon) this, 3216, -2, -7, 2, 2212, -1, "", 1);// 214
			AddComplexComponent( (BaseAddon) this, 3216, -2, -6, 2, 2208, -1, "", 1);// 215
			AddComplexComponent( (BaseAddon) this, 3216, -3, -7, 2, 2211, -1, "", 1);// 217
			AddComplexComponent( (BaseAddon) this, 3216, -2, -5, 2, 2212, -1, "", 1);// 222
			AddComplexComponent( (BaseAddon) this, 3218, -2, -1, 4, 2210, -1, "", 1);// 226
			AddComplexComponent( (BaseAddon) this, 3217, 4, 8, 2, 2212, -1, "", 1);// 231
			AddComplexComponent( (BaseAddon) this, 3216, -3, 8, 2, 2208, -1, "", 1);// 238
			AddComplexComponent( (BaseAddon) this, 3216, 0, 1, 2, 2212, -1, "", 1);// 239
			AddComplexComponent( (BaseAddon) this, 3216, -1, 1, 2, 2209, -1, "", 1);// 241
			AddComplexComponent( (BaseAddon) this, 3392, 7, 8, 9, 2212, -1, "", 1);// 244
			AddComplexComponent( (BaseAddon) this, 3392, 3, 2, 2, 2212, -1, "", 1);// 246
			AddComplexComponent( (BaseAddon) this, 3216, 0, 8, 2, 2211, -1, "", 1);// 249
			AddComplexComponent( (BaseAddon) this, 3216, -2, 8, 2, 2211, -1, "", 1);// 253
			AddComplexComponent( (BaseAddon) this, 3216, 3, 1, 2, 2211, -1, "", 1);// 258
			AddComplexComponent( (BaseAddon) this, 3216, -2, 1, 2, 2212, -1, "", 1);// 259
			AddComplexComponent( (BaseAddon) this, 3512, 2, 1, 2, 2210, -1, "", 1);// 264
			AddComplexComponent( (BaseAddon) this, 3378, 5, 5, 4, 2212, -1, "", 1);// 275
			AddComplexComponent( (BaseAddon) this, 3216, 5, 8, 2, 2211, -1, "", 1);// 277
			AddComplexComponent( (BaseAddon) this, 3217, -3, 1, 2, 2212, -1, "", 1);// 279
			AddComplexComponent( (BaseAddon) this, 3513, 1, 1, 2, 2207, -1, "", 1);// 284
			AddComplexComponent( (BaseAddon) this, 3245, 2, 2, 2, 2209, -1, "", 1);// 298
			AddComplexComponent( (BaseAddon) this, 3249, -2, 2, 3, 2212, -1, "", 1);// 302
			AddComplexComponent( (BaseAddon) this, 3216, 2, 8, 2, 2210, -1, "", 1);// 312
			AddComplexComponent( (BaseAddon) this, 3249, 6, 6, 2, 2210, -1, "", 1);// 316
			AddComplexComponent( (BaseAddon) this, 3380, 4, 5, 3, 2212, -1, "", 1);// 319
			AddComplexComponent( (BaseAddon) this, 3216, 8, 4, 2, 2209, -1, "", 1);// 320
			AddComplexComponent( (BaseAddon) this, 3216, 7, 1, 2, 2212, -1, "", 1);// 324
			AddComplexComponent( (BaseAddon) this, 3216, 6, 1, 2, 2208, -1, "", 1);// 326
			AddComplexComponent( (BaseAddon) this, 3218, 8, 5, 3, 2208, -1, "", 1);// 329
			AddComplexComponent( (BaseAddon) this, 3258, 1, 5, 2, 2212, -1, "", 1);// 332
			AddComplexComponent( (BaseAddon) this, 3217, 1, 8, 2, 2208, -1, "", 1);// 333
			AddComplexComponent( (BaseAddon) this, 3249, 5, 4, 2, 2210, -1, "", 1);// 337
			AddComplexComponent( (BaseAddon) this, 3216, 3, 8, 2, 2211, -1, "", 1);// 339
			AddComplexComponent( (BaseAddon) this, 3217, 3, 1, 4, 2209, -1, "", 1);// 342
			AddComplexComponent( (BaseAddon) this, 3217, 0, 1, 2, 2211, -1, "", 1);// 343
			AddComplexComponent( (BaseAddon) this, 3246, 5, 2, 2, 2210, -1, "", 1);// 347
			AddComplexComponent( (BaseAddon) this, 3217, 5, 1, 2, 2209, -1, "", 1);// 355
			AddComplexComponent( (BaseAddon) this, 3216, 8, 3, 2, 2210, -1, "", 1);// 372
			AddComplexComponent( (BaseAddon) this, 3216, 8, 8, 2, 2212, -1, "", 1);// 375
			AddComplexComponent( (BaseAddon) this, 3216, 8, 1, 2, 2212, -1, "", 1);// 376
			AddComplexComponent( (BaseAddon) this, 3216, 8, 5, 2, 2208, -1, "", 1);// 377
			AddComplexComponent( (BaseAddon) this, 3216, 8, 2, 2, 2211, -1, "", 1);// 378
			AddComplexComponent( (BaseAddon) this, 3216, 8, 6, 2, 2210, -1, "", 1);// 385
			AddComplexComponent( (BaseAddon) this, 3216, 8, 7, 2, 2211, -1, "", 1);// 388
			AddComplexComponent( (BaseAddon) this, 3216, 7, 8, 2, 2211, -1, "", 1);// 395
			AddComplexComponent( (BaseAddon) this, 3216, 6, 8, 2, 2208, -1, "", 1);// 396
			AddComplexComponent( (BaseAddon) this, 3217, 4, 1, 2, 2210, -1, "", 1);// 410
			AddComplexComponent( (BaseAddon) this, 7870, 4, 4, 2, 2212, -1, "", 1);// 422
			AddComplexComponent( (BaseAddon) this, 3216, -1, 8, 2, 2212, -1, "", 1);// 428
			AddComplexComponent( (BaseAddon) this, 3249, -1, 2, 3, 2212, -1, "", 1);// 429
			AddComplexComponent( (BaseAddon) this, 3392, -2, 8, 8, 2212, -1, "", 1);// 436
			AddComplexComponent( (BaseAddon) this, 3392, 8, 3, 9, 2212, -1, "", 1);// 443
			AddComplexComponent( (BaseAddon) this, 3257, -3, 2, 3, 2211, -1, "", 1);// 445

		}

		public BBRooftopAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class BBRooftopAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BBRooftopAddon();
			}
		}

		[Constructable]
		public BBRooftopAddonDeed()
		{
			Name = "BBRooftop";
		}

		public BBRooftopAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}