////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SkullballTrophyGoldAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SkullballTrophyGoldAddonDeed();
			}
		}

		[ Constructable ]
		public SkullballTrophyGoldAddon()
		{
			AddComplexComponent( (BaseAddon) this, 4643, 0, 0, 5, 1290, -1, "Ultimate Skullball Trophy - GOLD 11/29/14", 1);// 1
			AddComplexComponent( (BaseAddon) this, 7960, 0, 0, 14, 1290, -1, "Ultimate Skullball Trophy - GOLD 11/29/14", 1);// 2
			AddComplexComponent( (BaseAddon) this, 8700, 0, 0, 0, 1290, -1, "", 1);// 3
		}

		public SkullballTrophyGoldAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SkullballTrophyGoldAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SkullballTrophyGoldAddon();
			}
		}

		[Constructable]
		public SkullballTrophyGoldAddonDeed()
		{
			Name = "SkullballTrophyGold";
		}

		public SkullballTrophyGoldAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}