////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class Ultimate_Sb_Bronze_StatAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new Ultimate_Sb_Bronze_StatAddonDeed();
			}
		}

		[ Constructable ]
		public Ultimate_Sb_Bronze_StatAddon()
		{
			AddComplexComponent( (BaseAddon) this, 4643, 0, 0, 0, 2018, -1, "Skullball Trophy - Bronze", 1);// 1
			AddComplexComponent( (BaseAddon) this, 7960, 0, 0, 9, 2018, -1, "Skullball Trophy - Bronze", 1);// 2
			AddComplexComponent( (BaseAddon) this, 8454, 0, 0, 17, 2018, -1, "Skullball Trophy - Bronze", 1);// 3

		}

		public Ultimate_Sb_Bronze_StatAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class Ultimate_Sb_Bronze_StatAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new Ultimate_Sb_Bronze_StatAddon();
			}
		}

		[Constructable]
		public Ultimate_Sb_Bronze_StatAddonDeed()
		{
			Name = "Ultimate_Sb_Bronze_Stat";
		}

		public Ultimate_Sb_Bronze_StatAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}