
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SlendySiloAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {18221, 0, 0, 0}, {18235, -2, 3, 0}, {18222, -1, 0, 0}// 1	2	3	
			, {18225, 0, 1, 0}, {18226, -1, 1, 0}, {18231, -1, 2, 0}// 4	5	6	
			, {18220, 0, 0, 0}, {18234, -1, 3, 0}, {18223, -2, 3, 0}// 7	8	9	
			, {18230, 0, 2, 0}, {18227, -2, 1, 0}, {18232, -2, 2, 0}// 10	11	12	
			, {18215, 0, -1, 0}, {18224, 1, 1, 0}, {18219, 1, 0, 0}// 13	14	15	
			, {18233, 2, 2, 0}, {18229, 1, 2, 0}, {18212, 1, -2, 0}// 16	17	18	
			, {18214, 1, -1, 0}, {18228, 2, 1, 0}// 19	20	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SlendySiloAddonDeed();
			}
		}

		[ Constructable ]
		public SlendySiloAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public SlendySiloAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SlendySiloAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SlendySiloAddon();
			}
		}

		[Constructable]
		public SlendySiloAddonDeed()
		{
			Name = "SlendySilo";
		}

		public SlendySiloAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}