
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MiasmaAddon : BaseAddon
	{
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MiasmaAddonDeed();
			}
		}

		[ Constructable ]
		public MiasmaAddon()
		{
			AddComplexComponent( (BaseAddon) this, 6078, -3, -4, 1, 1757, -1, "Miasma Pit", 1);// 1
			AddComplexComponent( (BaseAddon) this, 6078, -3, -3, 1, 1757, -1, "Miasma Pit", 1);// 2
			AddComplexComponent( (BaseAddon) this, 6078, -3, -2, 1, 1757, -1, "Miasma Pit", 1);// 3
			AddComplexComponent( (BaseAddon) this, 6078, -3, -1, 1, 1757, -1, "Miasma Pit", 1);// 4
			AddComplexComponent( (BaseAddon) this, 6078, -3, 0, 1, 1757, -1, "Miasma Pit", 1);// 5
			AddComplexComponent( (BaseAddon) this, 6078, -3, 1, 1, 1757, -1, "Miasma Pit", 1);// 6
			AddComplexComponent( (BaseAddon) this, 6078, -3, 2, 1, 1757, -1, "Miasma Pit", 1);// 7
			AddComplexComponent( (BaseAddon) this, 6078, -3, 3, 1, 1757, -1, "Miasma Pit", 1);// 8
			AddComplexComponent( (BaseAddon) this, 6079, -2, -4, 1, 1757, -1, "Miasma Pit", 1);// 9
			AddComplexComponent( (BaseAddon) this, 6079, -2, -3, 1, 1757, -1, "Miasma Pit", 1);// 10
			AddComplexComponent( (BaseAddon) this, 6079, -2, -2, 1, 1757, -1, "Miasma Pit", 1);// 11
			AddComplexComponent( (BaseAddon) this, 6079, -2, -1, 1, 1757, -1, "Miasma Pit", 1);// 12
			AddComplexComponent( (BaseAddon) this, 6079, -2, 0, 1, 1757, -1, "Miasma Pit", 1);// 13
			AddComplexComponent( (BaseAddon) this, 6079, -2, 1, 1, 1757, -1, "Miasma Pit", 1);// 14
			AddComplexComponent( (BaseAddon) this, 6079, -2, 2, 1, 1757, -1, "Miasma Pit", 1);// 15
			AddComplexComponent( (BaseAddon) this, 6079, -2, 3, 1, 1757, -1, "Miasma Pit", 1);// 16
			AddComplexComponent( (BaseAddon) this, 6077, -1, -4, 1, 1757, -1, "Miasma Pit", 1);// 17
			AddComplexComponent( (BaseAddon) this, 6077, -1, -3, 1, 1757, -1, "Miasma Pit", 1);// 18
			AddComplexComponent( (BaseAddon) this, 6077, -1, -2, 1, 1757, -1, "Miasma Pit", 1);// 19
			AddComplexComponent( (BaseAddon) this, 6077, -1, -1, 1, 1757, -1, "Miasma Pit", 1);// 20
			AddComplexComponent( (BaseAddon) this, 6077, -1, 0, 1, 1757, -1, "Miasma Pit", 1);// 21
			AddComplexComponent( (BaseAddon) this, 6077, -1, 1, 1, 1757, -1, "Miasma Pit", 1);// 22
			AddComplexComponent( (BaseAddon) this, 6077, -1, 2, 1, 1757, -1, "Miasma Pit", 1);// 23
			AddComplexComponent( (BaseAddon) this, 6077, -1, 3, 1, 1757, -1, "Miasma Pit", 1);// 24
			AddComplexComponent( (BaseAddon) this, 6080, 0, -4, 1, 1757, -1, "Miasma Pit", 1);// 25
			AddComplexComponent( (BaseAddon) this, 6080, 0, -3, 1, 1757, -1, "Miasma Pit", 1);// 26
			AddComplexComponent( (BaseAddon) this, 6080, 0, -2, 1, 1757, -1, "Miasma Pit", 1);// 27
			AddComplexComponent( (BaseAddon) this, 6080, 0, -1, 1, 1757, -1, "Miasma Pit", 1);// 28
			AddComplexComponent( (BaseAddon) this, 6080, 0, 0, 1, 1757, -1, "Miasma Pit", 1);// 29
			AddComplexComponent( (BaseAddon) this, 6080, 0, 1, 1, 1757, -1, "Miasma Pit", 1);// 30
			AddComplexComponent( (BaseAddon) this, 6080, 0, 2, 1, 1757, -1, "Miasma Pit", 1);// 31
			AddComplexComponent( (BaseAddon) this, 6080, 0, 3, 1, 1757, -1, "Miasma Pit", 1);// 32
			AddComplexComponent( (BaseAddon) this, 6077, 1, -4, 1, 1757, -1, "Miasma Pit", 1);// 33
			AddComplexComponent( (BaseAddon) this, 6077, 1, -3, 1, 1757, -1, "Miasma Pit", 1);// 34
			AddComplexComponent( (BaseAddon) this, 6077, 1, -2, 1, 1757, -1, "Miasma Pit", 1);// 35
			AddComplexComponent( (BaseAddon) this, 6077, 1, -1, 1, 1757, -1, "Miasma Pit", 1);// 36
			AddComplexComponent( (BaseAddon) this, 6077, 1, 0, 1, 1757, -1, "Miasma Pit", 1);// 37
			AddComplexComponent( (BaseAddon) this, 6077, 1, 1, 1, 1757, -1, "Miasma Pit", 1);// 38
			AddComplexComponent( (BaseAddon) this, 6077, 1, 2, 1, 1757, -1, "Miasma Pit", 1);// 39
			AddComplexComponent( (BaseAddon) this, 6077, 1, 3, 1, 1757, -1, "Miasma Pit", 1);// 40
			AddComplexComponent( (BaseAddon) this, 6078, 2, -4, 1, 1757, -1, "Miasma Pit", 1);// 41
			AddComplexComponent( (BaseAddon) this, 6078, 2, -3, 1, 1757, -1, "Miasma Pit", 1);// 42
			AddComplexComponent( (BaseAddon) this, 6078, 2, -2, 1, 1757, -1, "Miasma Pit", 1);// 43
			AddComplexComponent( (BaseAddon) this, 6078, 2, -1, 1, 1757, -1, "Miasma Pit", 1);// 44
			AddComplexComponent( (BaseAddon) this, 6078, 2, 0, 1, 1757, -1, "Miasma Pit", 1);// 45
			AddComplexComponent( (BaseAddon) this, 6078, 2, 1, 1, 1757, -1, "Miasma Pit", 1);// 46
			AddComplexComponent( (BaseAddon) this, 6078, 2, 2, 1, 1757, -1, "Miasma Pit", 1);// 47
			AddComplexComponent( (BaseAddon) this, 6078, 2, 3, 1, 1757, -1, "Miasma Pit", 1);// 48
			AddComplexComponent( (BaseAddon) this, 6079, 3, -4, 1, 1757, -1, "Miasma Pit", 1);// 49
			AddComplexComponent( (BaseAddon) this, 6079, 3, -3, 1, 1757, -1, "Miasma Pit", 1);// 50
			AddComplexComponent( (BaseAddon) this, 6079, 3, -2, 1, 1757, -1, "Miasma Pit", 1);// 51
			AddComplexComponent( (BaseAddon) this, 6079, 3, -1, 1, 1757, -1, "Miasma Pit", 1);// 52
			AddComplexComponent( (BaseAddon) this, 6079, 3, 0, 1, 1757, -1, "Miasma Pit", 1);// 53
			AddComplexComponent( (BaseAddon) this, 6079, 3, 1, 1, 1757, -1, "Miasma Pit", 1);// 54
			AddComplexComponent( (BaseAddon) this, 6079, 3, 2, 1, 1757, -1, "Miasma Pit", 1);// 55
			AddComplexComponent( (BaseAddon) this, 6079, 3, 3, 1, 1757, -1, "Miasma Pit", 1);// 56
			AddComplexComponent( (BaseAddon) this, 6080, 4, -4, 1, 1757, -1, "Miasma Pit", 1);// 57
			AddComplexComponent( (BaseAddon) this, 6080, 4, -3, 1, 1757, -1, "Miasma Pit", 1);// 58
			AddComplexComponent( (BaseAddon) this, 6080, 4, -2, 1, 1757, -1, "Miasma Pit", 1);// 59
			AddComplexComponent( (BaseAddon) this, 6080, 4, -1, 1, 1757, -1, "Miasma Pit", 1);// 60
			AddComplexComponent( (BaseAddon) this, 6080, 4, 0, 1, 1757, -1, "Miasma Pit", 1);// 61
			AddComplexComponent( (BaseAddon) this, 6080, 4, 1, 1, 1757, -1, "Miasma Pit", 1);// 62
			AddComplexComponent( (BaseAddon) this, 6080, 4, 2, 1, 1757, -1, "Miasma Pit", 1);// 63
			AddComplexComponent( (BaseAddon) this, 6080, 4, 3, 1, 1757, -1, "Miasma Pit", 1);// 64
			AddComplexComponent( (BaseAddon) this, 6077, 5, -4, 1, 1757, -1, "Miasma Pit", 1);// 65
			AddComplexComponent( (BaseAddon) this, 6077, 5, -3, 1, 1757, -1, "Miasma Pit", 1);// 66
			AddComplexComponent( (BaseAddon) this, 6077, 5, -2, 1, 1757, -1, "Miasma Pit", 1);// 67
			AddComplexComponent( (BaseAddon) this, 6077, 5, -1, 1, 1757, -1, "Miasma Pit", 1);// 68
			AddComplexComponent( (BaseAddon) this, 6077, 5, 0, 1, 1757, -1, "Miasma Pit", 1);// 69
			AddComplexComponent( (BaseAddon) this, 6077, 5, 1, 1, 1757, -1, "Miasma Pit", 1);// 70
			AddComplexComponent( (BaseAddon) this, 6077, 5, 2, 1, 1757, -1, "Miasma Pit", 1);// 71
			AddComplexComponent( (BaseAddon) this, 6077, 5, 3, 1, 1757, -1, "Miasma Pit", 1);// 72
			AddComplexComponent( (BaseAddon) this, 6092, 6, -4, 1, 1757, -1, "Miasma Pit", 1);// 73
			AddComplexComponent( (BaseAddon) this, 6092, 6, -1, 1, 1757, -1, "Miasma Pit", 1);// 74
			AddComplexComponent( (BaseAddon) this, 6092, 6, 3, 1, 1757, -1, "Miasma Pit", 1);// 75
			AddComplexComponent( (BaseAddon) this, 6087, 6, -3, 1, 1757, -1, "Miasma Pit", 1);// 76
			AddComplexComponent( (BaseAddon) this, 6086, 6, -2, 1, 1757, -1, "Miasma Pit", 1);// 77
			AddComplexComponent( (BaseAddon) this, 6087, 6, 0, 1, 1757, -1, "Miasma Pit", 1);// 78
			AddComplexComponent( (BaseAddon) this, 6092, 6, 2, 1, 1757, -1, "Miasma Pit", 1);// 79
			AddComplexComponent( (BaseAddon) this, 6092, 6, 1, 1, 1757, -1, "Miasma Pit", 1);// 80
			AddComplexComponent( (BaseAddon) this, 6086, 6, 0, 1, 1757, -1, "Miasma Pit", 1);// 81
			AddComplexComponent( (BaseAddon) this, 6091, -4, -5, 1, 1757, -1, "Miasma Pit", 1);// 82
			AddComplexComponent( (BaseAddon) this, 6091, -3, -5, 1, 1757, -1, "Miasma Pit", 1);// 83
			AddComplexComponent( (BaseAddon) this, 6091, -2, -5, 1, 1757, -1, "Miasma Pit", 1);// 84
			AddComplexComponent( (BaseAddon) this, 6091, -1, -5, 1, 1757, -1, "Miasma Pit", 1);// 85
			AddComplexComponent( (BaseAddon) this, 6091, 0, -5, 1, 1757, -1, "Miasma Pit", 1);// 86
			AddComplexComponent( (BaseAddon) this, 6091, 2, -5, 1, 1757, -1, "Miasma Pit", 1);// 87
			AddComplexComponent( (BaseAddon) this, 6091, 3, -5, 1, 1757, -1, "Miasma Pit", 1);// 88
			AddComplexComponent( (BaseAddon) this, 6091, 4, -5, 1, 1757, -1, "Miasma Pit", 1);// 89
			AddComplexComponent( (BaseAddon) this, 6091, 5, -5, 1, 1757, -1, "Miasma Pit", 1);// 90
			AddComplexComponent( (BaseAddon) this, 6086, 6, -5, 1, 1757, -1, "Miasma Pit", 1);// 91
			AddComplexComponent( (BaseAddon) this, 6086, 1, -5, 1, 1757, -1, "Miasma Pit", 1);// 92
			AddComplexComponent( (BaseAddon) this, 6085, 1, -5, 1, 1757, -1, "Miasma Pit", 1);// 93
			AddComplexComponent( (BaseAddon) this, 6077, -4, -4, 1, 1757, -1, "Miasma Pit", 1);// 94
			AddComplexComponent( (BaseAddon) this, 6077, -4, -3, 1, 1757, -1, "Miasma Pit", 1);// 95
			AddComplexComponent( (BaseAddon) this, 6077, -4, -2, 1, 1757, -1, "Miasma Pit", 1);// 96
			AddComplexComponent( (BaseAddon) this, 6077, -4, -1, 1, 1757, -1, "Miasma Pit", 1);// 97
			AddComplexComponent( (BaseAddon) this, 6077, -4, 0, 1, 1757, -1, "Miasma Pit", 1);// 98
			AddComplexComponent( (BaseAddon) this, 6077, -4, 1, 1, 1757, -1, "Miasma Pit", 1);// 99
			AddComplexComponent( (BaseAddon) this, 6077, -4, 2, 1, 1757, -1, "Miasma Pit", 1);// 100
			AddComplexComponent( (BaseAddon) this, 6077, -4, 3, 1, 1757, -1, "Miasma Pit", 1);// 101
			AddComplexComponent( (BaseAddon) this, 6090, -5, -4, 1, 1757, -1, "Miasma Pit", 1);// 102
			AddComplexComponent( (BaseAddon) this, 6090, -5, -3, 1, 1757, -1, "Miasma Pit", 1);// 103
			AddComplexComponent( (BaseAddon) this, 6090, -5, -2, 1, 1757, -1, "Miasma Pit", 1);// 104
			AddComplexComponent( (BaseAddon) this, 6090, -5, 0, 1, 1757, -1, "Miasma Pit", 1);// 105
			AddComplexComponent( (BaseAddon) this, 6090, -5, 1, 1, 1757, -1, "Miasma Pit", 1);// 106
			AddComplexComponent( (BaseAddon) this, 6090, -5, 3, 1, 1757, -1, "Miasma Pit", 1);// 107
			AddComplexComponent( (BaseAddon) this, 6088, -5, -1, 1, 1757, -1, "Miasma Pit", 1);// 108
			AddComplexComponent( (BaseAddon) this, 6088, -5, 2, 1, 1757, -1, "Miasma Pit", 1);// 109
			AddComplexComponent( (BaseAddon) this, 6085, -5, -1, 1, 1757, -1, "Miasma Pit", 1);// 110
			AddComplexComponent( (BaseAddon) this, 6085, -5, 2, 1, 1757, -1, "Miasma Pit", 1);// 111
			AddComplexComponent( (BaseAddon) this, 6085, -5, -5, 1, 1757, -1, "Miasma Pit", 1);// 112
			AddComplexComponent( (BaseAddon) this, 10810, -6, -6, 1, 1757, -1, "Miasma Pit", 1);// 113
			AddComplexComponent( (BaseAddon) this, 9372, -6, -5, 1, 1757, -1, "Miasma Pit", 1);// 114
			AddComplexComponent( (BaseAddon) this, 9372, -6, -4, 1, 1757, -1, "Miasma Pit", 1);// 115
			AddComplexComponent( (BaseAddon) this, 9372, -6, -3, 1, 1757, -1, "Miasma Pit", 1);// 116
			AddComplexComponent( (BaseAddon) this, 9372, -6, -2, 1, 1757, -1, "Miasma Pit", 1);// 117
			AddComplexComponent( (BaseAddon) this, 9372, -6, -1, 1, 1757, -1, "Miasma Pit", 1);// 118
			AddComplexComponent( (BaseAddon) this, 9372, -6, 0, 1, 1757, -1, "Miasma Pit", 1);// 119
			AddComplexComponent( (BaseAddon) this, 9372, -6, 1, 1, 1757, -1, "Miasma Pit", 1);// 120
			AddComplexComponent( (BaseAddon) this, 9372, -6, 2, 1, 1757, -1, "Miasma Pit", 1);// 121
			AddComplexComponent( (BaseAddon) this, 9372, -6, 3, 1, 1757, -1, "Miasma Pit", 1);// 122
			AddComplexComponent( (BaseAddon) this, 9372, 6, -5, 0, 1757, -1, "Miasma Pit", 1);// 123
			AddComplexComponent( (BaseAddon) this, 9372, 6, -4, 0, 1757, -1, "Miasma Pit", 1);// 124
			AddComplexComponent( (BaseAddon) this, 9372, 6, -3, 0, 1757, -1, "Miasma Pit", 1);// 125
			AddComplexComponent( (BaseAddon) this, 9372, 6, -2, 0, 1757, -1, "Miasma Pit", 1);// 126
			AddComplexComponent( (BaseAddon) this, 9372, 6, -1, 0, 1757, -1, "Miasma Pit", 1);// 127
			AddComplexComponent( (BaseAddon) this, 9372, 6, 0, 0, 1757, -1, "Miasma Pit", 1);// 128
			AddComplexComponent( (BaseAddon) this, 9372, 6, 1, 0, 1757, -1, "Miasma Pit", 1);// 129
			AddComplexComponent( (BaseAddon) this, 9372, 6, 2, 0, 1757, -1, "Miasma Pit", 1);// 130
			AddComplexComponent( (BaseAddon) this, 9372, 6, 3, 0, 1757, -1, "Miasma Pit", 1);// 131
			AddComplexComponent( (BaseAddon) this, 9371, -5, -6, 1, 1757, -1, "Miasma Pit", 1);// 132
			AddComplexComponent( (BaseAddon) this, 9371, -4, -6, 1, 1757, -1, "Miasma Pit", 1);// 133
			AddComplexComponent( (BaseAddon) this, 9371, -3, -6, 1, 1757, -1, "Miasma Pit", 1);// 134
			AddComplexComponent( (BaseAddon) this, 9371, -2, -6, 1, 1757, -1, "Miasma Pit", 1);// 135
			AddComplexComponent( (BaseAddon) this, 9371, -1, -6, 1, 1757, -1, "Miasma Pit", 1);// 136
			AddComplexComponent( (BaseAddon) this, 9371, 0, -6, 1, 1757, -1, "Miasma Pit", 1);// 137
			AddComplexComponent( (BaseAddon) this, 9371, 1, -6, 1, 1757, -1, "Miasma Pit", 1);// 138
			AddComplexComponent( (BaseAddon) this, 9371, 2, -6, 1, 1757, -1, "Miasma Pit", 1);// 139
			AddComplexComponent( (BaseAddon) this, 9371, 3, -6, 1, 1757, -1, "Miasma Pit", 1);// 140
			AddComplexComponent( (BaseAddon) this, 9371, 4, -6, 1, 1757, -1, "Miasma Pit", 1);// 141
			AddComplexComponent( (BaseAddon) this, 9371, 5, -6, 1, 1757, -1, "Miasma Pit", 1);// 142
			AddComplexComponent( (BaseAddon) this, 9380, 6, -6, 1, 1757, -1, "Miasma Pit", 1);// 143
			AddComplexComponent( (BaseAddon) this, 6078, -3, 4, 1, 1757, -1, "Miasma Pit", 1);// 144
			AddComplexComponent( (BaseAddon) this, 6078, -3, 5, 1, 1757, -1, "Miasma Pit", 1);// 145
			AddComplexComponent( (BaseAddon) this, 6079, -2, 4, 1, 1757, -1, "Miasma Pit", 1);// 146
			AddComplexComponent( (BaseAddon) this, 6079, -2, 5, 1, 1757, -1, "Miasma Pit", 1);// 147
			AddComplexComponent( (BaseAddon) this, 6077, -1, 4, 1, 1757, -1, "Miasma Pit", 1);// 148
			AddComplexComponent( (BaseAddon) this, 6077, -1, 5, 1, 1757, -1, "Miasma Pit", 1);// 149
			AddComplexComponent( (BaseAddon) this, 6080, 0, 4, 1, 1757, -1, "Miasma Pit", 1);// 150
			AddComplexComponent( (BaseAddon) this, 6080, 0, 5, 1, 1757, -1, "Miasma Pit", 1);// 151
			AddComplexComponent( (BaseAddon) this, 6077, 1, 4, 1, 1757, -1, "Miasma Pit", 1);// 152
			AddComplexComponent( (BaseAddon) this, 6077, 1, 5, 1, 1757, -1, "Miasma Pit", 1);// 153
			AddComplexComponent( (BaseAddon) this, 6078, 2, 4, 1, 1757, -1, "Miasma Pit", 1);// 154
			AddComplexComponent( (BaseAddon) this, 6078, 2, 5, 1, 1757, -1, "Miasma Pit", 1);// 155
			AddComplexComponent( (BaseAddon) this, 6079, 3, 4, 1, 1757, -1, "Miasma Pit", 1);// 156
			AddComplexComponent( (BaseAddon) this, 6079, 3, 5, 1, 1757, -1, "Miasma Pit", 1);// 157
			AddComplexComponent( (BaseAddon) this, 6080, 4, 4, 1, 1757, -1, "Miasma Pit", 1);// 158
			AddComplexComponent( (BaseAddon) this, 6080, 4, 5, 1, 1757, -1, "Miasma Pit", 1);// 159
			AddComplexComponent( (BaseAddon) this, 6077, 5, 4, 1, 1757, -1, "Miasma Pit", 1);// 160
			AddComplexComponent( (BaseAddon) this, 6077, 5, 5, 1, 1757, -1, "Miasma Pit", 1);// 161
			AddComplexComponent( (BaseAddon) this, 6092, 6, 5, 1, 1757, -1, "Miasma Pit", 1);// 162
			AddComplexComponent( (BaseAddon) this, 6086, 6, 4, 1, 1757, -1, "Miasma Pit", 1);// 163
			AddComplexComponent( (BaseAddon) this, 6087, 6, 4, 1, 1757, -1, "Miasma Pit", 1);// 164
			AddComplexComponent( (BaseAddon) this, 6077, -4, 4, 1, 1757, -1, "Miasma Pit", 1);// 165
			AddComplexComponent( (BaseAddon) this, 6077, -4, 5, 1, 1757, -1, "Miasma Pit", 1);// 166
			AddComplexComponent( (BaseAddon) this, 6090, -5, 4, 1, 1757, -1, "Miasma Pit", 1);// 167
			AddComplexComponent( (BaseAddon) this, 6090, -5, 5, 1, 1757, -1, "Miasma Pit", 1);// 168
			AddComplexComponent( (BaseAddon) this, 6089, -4, 6, 1, 1757, -1, "Miasma Pit", 1);// 169
			AddComplexComponent( (BaseAddon) this, 6089, -2, 6, 1, 1757, -1, "Miasma Pit", 1);// 170
			AddComplexComponent( (BaseAddon) this, 6089, -1, 6, 1, 1757, -1, "Miasma Pit", 1);// 171
			AddComplexComponent( (BaseAddon) this, 6089, 1, 6, 1, 1757, -1, "Miasma Pit", 1);// 172
			AddComplexComponent( (BaseAddon) this, 6089, 2, 6, 1, 1757, -1, "Miasma Pit", 1);// 173
			AddComplexComponent( (BaseAddon) this, 6089, 3, 6, 1, 1757, -1, "Miasma Pit", 1);// 174
			AddComplexComponent( (BaseAddon) this, 6089, 5, 6, 1, 1757, -1, "Miasma Pit", 1);// 175
			AddComplexComponent( (BaseAddon) this, 6088, -5, 6, 1, 1757, -1, "Miasma Pit", 1);// 176
			AddComplexComponent( (BaseAddon) this, 6087, 6, 6, 1, 1757, -1, "Miasma Pit", 1);// 177
			AddComplexComponent( (BaseAddon) this, 6087, 4, 6, 1, 1757, -1, "Miasma Pit", 1);// 178
			AddComplexComponent( (BaseAddon) this, 6087, 0, 6, 1, 1757, -1, "Miasma Pit", 1);// 179
			AddComplexComponent( (BaseAddon) this, 6087, -3, 6, 1, 1757, -1, "Miasma Pit", 1);// 180
			AddComplexComponent( (BaseAddon) this, 6088, 4, 6, 1, 1757, -1, "Miasma Pit", 1);// 181
			AddComplexComponent( (BaseAddon) this, 6088, 0, 6, 1, 1757, -1, "Miasma Pit", 1);// 182
			AddComplexComponent( (BaseAddon) this, 6088, -3, 6, 1, 1757, -1, "Miasma Pit", 1);// 183
			AddComplexComponent( (BaseAddon) this, 10804, 6, 6, 0, 1757, -1, "Miasma Pit", 1);// 184
			AddComplexComponent( (BaseAddon) this, 9371, -5, 6, 0, 1757, -1, "Miasma Pit", 1);// 185
			AddComplexComponent( (BaseAddon) this, 9371, -4, 6, 0, 1757, -1, "Miasma Pit", 1);// 186
			AddComplexComponent( (BaseAddon) this, 9371, -3, 6, 0, 1757, -1, "Miasma Pit", 1);// 187
			AddComplexComponent( (BaseAddon) this, 9371, -2, 6, 0, 1757, -1, "Miasma Pit", 1);// 188
			AddComplexComponent( (BaseAddon) this, 9371, -1, 6, 0, 1757, -1, "Miasma Pit", 1);// 189
			AddComplexComponent( (BaseAddon) this, 9371, 0, 6, 0, 1757, -1, "Miasma Pit", 1);// 190
			AddComplexComponent( (BaseAddon) this, 9371, 1, 6, 0, 1757, -1, "Miasma Pit", 1);// 191
			AddComplexComponent( (BaseAddon) this, 9371, 2, 6, 0, 1757, -1, "Miasma Pit", 1);// 192
			AddComplexComponent( (BaseAddon) this, 9371, 3, 6, 0, 1757, -1, "Miasma Pit", 1);// 193
			AddComplexComponent( (BaseAddon) this, 9371, 4, 6, 0, 1757, -1, "Miasma Pit", 1);// 194
			AddComplexComponent( (BaseAddon) this, 9372, -6, 4, 1, 1757, -1, "Miasma Pit", 1);// 195
			AddComplexComponent( (BaseAddon) this, 9372, -6, 5, 1, 1757, -1, "Miasma Pit", 1);// 196
			AddComplexComponent( (BaseAddon) this, 9379, -6, 6, 1, 1757, -1, "Miasma Pit", 1);// 197
			AddComplexComponent( (BaseAddon) this, 9371, 5, 6, 0, 1757, -1, "Miasma Pit", 1);// 198
			AddComplexComponent( (BaseAddon) this, 9372, 6, 4, 0, 1757, -1, "Miasma Pit", 1);// 199
			AddComplexComponent( (BaseAddon) this, 9372, 6, 5, 0, 1757, -1, "Miasma Pit", 1);// 200

		}

		public MiasmaAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MiasmaAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MiasmaAddon();
			}
		}

		[Constructable]
		public MiasmaAddonDeed()
		{
			Name = "Miasma Fighting";
		}

		public MiasmaAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}