
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class WolfAndSwordTrapdoorAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new WolfAndSwordTrapdoorAddonDeed();
			}
		}

		[ Constructable ]
		public WolfAndSwordTrapdoorAddon()
		{



			AddComplexComponent( (BaseAddon) this, 1202, -1, 2, 0, 1446, -1, "Trapdoor", 1);// 1
			AddComplexComponent( (BaseAddon) this, 1199, 1, -1, 0, 1446, -1, "Trapdoor", 1);// 2
			AddComplexComponent( (BaseAddon) this, 1199, 1, 0, 0, 1446, -1, "Trapdoor", 1);// 3
			AddComplexComponent( (BaseAddon) this, 1199, 1, 1, 0, 1446, -1, "Trapdoor", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1201, 1, 2, 0, 1446, -1, "Trapdoor", 1);// 5
			AddComplexComponent( (BaseAddon) this, 1200, 0, -2, 0, 1446, -1, "Trapdoor", 1);// 6
			AddComplexComponent( (BaseAddon) this, 1203, 1, -2, 0, 1446, -1, "Trapdoor", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1204, -1, -2, 0, 1446, -1, "Trapdoor", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1195, 0, -1, 0, 1446, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1195, 0, 0, 0, 1446, -1, "Trapdoor", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1195, 0, 1, 0, 1446, -1, "Trapdoor", 1);// 11
			AddComplexComponent( (BaseAddon) this, 1197, -1, -1, 0, 1446, -1, "Trapdoor", 1);// 12
			AddComplexComponent( (BaseAddon) this, 1197, -1, 0, 0, 1446, -1, "Trapdoor", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1197, -1, 1, 0, 1446, -1, "Trapdoor", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1198, 0, 2, 0, 1446, -1, "Trapdoor", 1);// 15
			AddComplexComponent( (BaseAddon) this, 4113, 0, 0, 0, 0, -1, "Latch", 1);// 16

		}

		public WolfAndSwordTrapdoorAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class WolfAndSwordTrapdoorAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new WolfAndSwordTrapdoorAddon();
			}
		}

		[Constructable]
		public WolfAndSwordTrapdoorAddonDeed()
		{
			Name = "WolfAndSwordTrapdoor";
		}

		public WolfAndSwordTrapdoorAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}