
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class NecroCityHealerNEWAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3619, -2, -1, 13}, {6188, -3, -2, 15}, {5701, -2, -2, 9}// 2	5	6	
			, {3616, -2, -2, 9}, {4148, -1, -1, 7}, {2652, -2, -2, 7}// 34	35	49	
			, {2659, -2, -3, 7}, {4651, -1, -2, 9}, {7400, -2, -3, 8}// 51	52	65	
			, {7586, -1, -2, 7}, {2976, -1, 4, 6}, {6665, 4, 0, 0}// 69	73	113	
			, {4651, 1, -2, 9}, {4653, 0, -1, 7}, {6657, 4, -3, 0}// 119	137	166	
			, {2652, 1, -2, 7}, {2659, 1, -3, 7}, {5701, 0, -1, 7}// 170	171	185	
			, {4650, 0, 0, 7}, {4650, 0, -1, 7}, {5701, 2, -1, 7}// 186	187	195	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new NecroCityHealerNEWAddonDeed();
			}
		}

		[ Constructable ]
		public NecroCityHealerNEWAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1176, -1, -2, 7, 1109, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 99, -1, 3, 0, 1109, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 100, -2, 3, 0, 1109, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1175, -1, 1, 7, 1109, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1175, -1, 0, 7, 1109, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1176, -1, -1, 7, 1109, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1175, -2, 1, 7, 1109, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1173, -2, -1, 7, 1109, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 13879, -1, 3, 36, 1102, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 99, -2, 1, 0, 1109, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1174, -3, -2, 7, 1109, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 13882, -3, 2, 7, 1102, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 13882, -3, 1, 7, 1102, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1173, -1, 3, 7, 1109, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 13882, -4, -3, 7, 1102, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1174, -2, 0, 7, 1109, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1173, -1, 2, 7, 1109, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 1173, -1, -3, 37, 1109, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 1114, -3, -2, 10, 2053, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 1173, -2, 2, 37, 1109, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 1173, -2, 0, 37, 1109, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 6217, -3, -2, 15, 0, 1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 68, -2, -1, 7, 1104, -1, "Bone Table", 1);// 26
			AddComplexComponent( (BaseAddon) this, 100, -4, -2, 0, 1109, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 1173, -2, -2, 37, 1109, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 1173, -2, -1, 37, 1109, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 102, -3, -4, 0, 1109, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 100, -3, 2, 0, 1109, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 1173, -1, -3, 7, 1109, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 1173, -3, -3, 38, 1109, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 100, -3, 0, 0, 1109, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 100, -3, 1, 0, 1109, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 1173, -1, 1, 7, 1109, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 10585, -2, -2, 7, 1754, -1, "Bed post", 1);// 39
			AddComplexComponent( (BaseAddon) this, 100, -4, -1, 0, 1109, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 1175, -2, -2, 7, 1109, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 1173, -2, -2, 7, 1109, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 1173, -1, -1, 7, 1109, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 1880, -1, 4, 0, 1109, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 1176, -2, -3, 7, 1109, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 99, -2, -4, 0, 1109, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 1173, -1, -3, 7, 1109, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 99, -1, -4, 0, 1109, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 1173, -1, -2, 37, 1109, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 1173, -1, 1, 37, 1109, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 1173, -1, -1, 37, 1109, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 1173, -1, 0, 37, 1109, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 1173, -1, 3, 37, 1109, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 1173, -2, 1, 37, 1109, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 1173, -3, -1, 37, 1109, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 1173, -3, -2, 37, 1109, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 1173, -2, -3, 37, 1109, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 1173, -1, 2, 37, 1109, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 1173, -2, 1, 7, 1109, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 1114, -3, -2, 7, 2053, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 1173, -3, -3, 37, 1109, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 1174, -3, -1, 7, 1109, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 1174, -3, -3, 7, 1109, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 10585, -2, -2, 6, 1754, -1, "Bed post", 1);// 68
			AddComplexComponent( (BaseAddon) this, 1114, -3, -3, 10, 2053, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 13883, -1, 3, 7, 1102, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 13883, -2, 2, 7, 1102, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 100, -3, -3, 0, 1109, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 11526, -1, 2, 7, 901, -1, "Bone cupboard", 1);// 75
			AddComplexComponent( (BaseAddon) this, 1114, -3, -3, 7, 2053, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 13887, -2, -4, 7, 1102, 0, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 13882, -4, -2, 7, 1102, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 13882, -4, -1, 7, 1102, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 13882, -4, -3, 7, 1102, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 13882, -3, 0, 7, 1102, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 13883, -3, -1, 7, 1102, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 13849, -4, -4, 7, 1102, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 13882, -2, 3, 7, 1102, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 13878, -4, -1, 36, 1102, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 13878, -4, -2, 36, 1102, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 13878, -4, -3, 36, 1102, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 13878, -3, 1, 36, 1102, -1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 13883, -1, -4, 7, 1102, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 13879, -1, -4, 36, 1102, -1, "", 1);// 90
			AddComplexComponent( (BaseAddon) this, 13879, -3, -4, 36, 1102, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 13878, -3, 2, 36, 1102, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 13879, -2, -4, 36, 1102, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 13878, -2, 3, 36, 1102, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 13878, -3, 0, 36, 1102, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 13879, -3, -1, 36, 1102, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 13847, -4, -4, 35, 1102, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 13881, -1, 3, 27, 1102, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 13880, -3, 2, 27, 1102, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 13880, -3, 1, 27, 1102, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 13880, -3, 0, 27, 1102, -1, "", 1);// 101
			AddComplexComponent( (BaseAddon) this, 13880, -4, -1, 27, 1102, -1, "", 1);// 102
			AddComplexComponent( (BaseAddon) this, 13880, -4, -2, 27, 1102, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 13880, -4, -3, 27, 1102, -1, "", 1);// 104
			AddComplexComponent( (BaseAddon) this, 13879, -2, 2, 36, 1102, -1, "", 1);// 105
			AddComplexComponent( (BaseAddon) this, 13881, -1, -4, 27, 1102, -1, "", 1);// 106
			AddComplexComponent( (BaseAddon) this, 13881, -2, -4, 27, 1102, -1, "", 1);// 107
			AddComplexComponent( (BaseAddon) this, 13881, -3, -4, 27, 1102, -1, "", 1);// 108
			AddComplexComponent( (BaseAddon) this, 13881, -3, -1, 27, 1102, -1, "", 1);// 109
			AddComplexComponent( (BaseAddon) this, 13881, -2, 2, 27, 1102, -1, "", 1);// 110
			AddComplexComponent( (BaseAddon) this, 13880, -2, 3, 27, 1102, -1, "", 1);// 111
			AddComplexComponent( (BaseAddon) this, 13883, -3, -4, 7, 1102, -1, "", 1);// 112
			AddComplexComponent( (BaseAddon) this, 13879, 2, 3, 36, 1102, -1, "", 1);// 114
			AddComplexComponent( (BaseAddon) this, 99, 2, -4, 0, 1109, -1, "", 1);// 115
			AddComplexComponent( (BaseAddon) this, 13838, 2, 3, 7, 1102, -1, "", 1);// 116
			AddComplexComponent( (BaseAddon) this, 13879, 1, 3, 36, 1102, -1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 13879, 0, 3, 36, 1102, -1, "", 1);// 118
			AddComplexComponent( (BaseAddon) this, 1174, 0, -3, 7, 1109, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 1173, 2, -1, 7, 1109, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 1173, 2, -2, 7, 1109, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 1174, 1, -3, 7, 1109, -1, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 1174, 1, -1, 7, 1109, -1, "", 1);// 124
			AddComplexComponent( (BaseAddon) this, 1176, 1, -2, 7, 1109, -1, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 1175, 2, -3, 7, 1109, -1, "", 1);// 126
			AddComplexComponent( (BaseAddon) this, 1176, 3, -1, 7, 1109, -1, "", 1);// 127
			AddComplexComponent( (BaseAddon) this, 1175, 3, -2, 7, 1109, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 1173, 0, -2, 7, 1109, -1, "", 1);// 129
			AddComplexComponent( (BaseAddon) this, 1173, 0, -1, 7, 1109, -1, "", 1);// 130
			AddComplexComponent( (BaseAddon) this, 1174, 0, 0, 7, 1109, -1, "", 1);// 131
			AddComplexComponent( (BaseAddon) this, 1176, 3, -3, 7, 1109, -1, "", 1);// 132
			AddComplexComponent( (BaseAddon) this, 1173, 0, 2, 7, 1109, -1, "", 1);// 133
			AddComplexComponent( (BaseAddon) this, 1176, 0, 1, 7, 1109, -1, "", 1);// 134
			AddComplexComponent( (BaseAddon) this, 1173, 1, 3, 7, 1109, -1, "", 1);// 135
			AddComplexComponent( (BaseAddon) this, 1173, 1, 2, 7, 1109, -1, "", 1);// 136
			AddComplexComponent( (BaseAddon) this, 99, 0, -4, 0, 1109, -1, "", 1);// 138
			AddComplexComponent( (BaseAddon) this, 1173, 0, 3, 7, 1109, -1, "", 1);// 139
			AddComplexComponent( (BaseAddon) this, 1173, 2, 1, 37, 1109, -1, "", 1);// 140
			AddComplexComponent( (BaseAddon) this, 99, 1, -4, 0, 1109, -1, "", 1);// 141
			AddComplexComponent( (BaseAddon) this, 13878, 2, 3, 36, 1102, -1, "", 1);// 142
			AddComplexComponent( (BaseAddon) this, 13878, 2, 2, 36, 1102, -1, "", 1);// 143
			AddComplexComponent( (BaseAddon) this, 1173, 3, -2, 37, 1109, -1, "", 1);// 144
			AddComplexComponent( (BaseAddon) this, 1173, 3, -1, 37, 1109, -1, "", 1);// 145
			AddComplexComponent( (BaseAddon) this, 13878, 3, 0, 36, 1102, -1, "", 1);// 146
			AddComplexComponent( (BaseAddon) this, 1173, 1, 1, 7, 1109, -1, "", 1);// 147
			AddComplexComponent( (BaseAddon) this, 1173, 2, 1, 7, 1109, -1, "", 1);// 148
			AddComplexComponent( (BaseAddon) this, 1173, 3, 1, 37, 1109, -1, "", 1);// 149
			AddComplexComponent( (BaseAddon) this, 1878, 2, 4, 0, 1109, -1, "", 1);// 150
			AddComplexComponent( (BaseAddon) this, 100, 3, -1, 0, 1109, -1, "", 1);// 151
			AddComplexComponent( (BaseAddon) this, 99, 3, 1, 0, 1109, -1, "", 1);// 152
			AddComplexComponent( (BaseAddon) this, 100, 3, -3, 0, 1109, -1, "", 1);// 153
			AddComplexComponent( (BaseAddon) this, 99, 2, 3, 0, 1109, -1, "", 1);// 154
			AddComplexComponent( (BaseAddon) this, 99, 1, 3, 0, 1109, -1, "", 1);// 155
			AddComplexComponent( (BaseAddon) this, 100, 3, 0, 0, 1109, -1, "", 1);// 156
			AddComplexComponent( (BaseAddon) this, 99, 0, 3, 0, 1109, -1, "", 1);// 157
			AddComplexComponent( (BaseAddon) this, 1173, 3, 1, 7, 1109, -1, "", 1);// 158
			AddComplexComponent( (BaseAddon) this, 100, 3, -2, 0, 1109, -1, "", 1);// 159
			AddComplexComponent( (BaseAddon) this, 68, 1, -1, 7, 1104, -1, "Bone Table", 1);// 160
			AddComplexComponent( (BaseAddon) this, 1173, 1, -3, 7, 1109, -1, "", 1);// 161
			AddComplexComponent( (BaseAddon) this, 1176, 2, 1, 27, 1109, -1, "", 1);// 162
			AddComplexComponent( (BaseAddon) this, 1173, 3, 0, 7, 1109, -1, "", 1);// 163
			AddComplexComponent( (BaseAddon) this, 1173, 1, -1, 7, 1109, -1, "", 1);// 164
			AddComplexComponent( (BaseAddon) this, 1173, 3, -3, 37, 1109, -1, "", 1);// 165
			AddComplexComponent( (BaseAddon) this, 13879, 3, 1, 36, 1102, -1, "", 1);// 167
			AddComplexComponent( (BaseAddon) this, 13880, 3, -2, 27, 1102, -1, "", 1);// 168
			AddComplexComponent( (BaseAddon) this, 13880, 3, -3, 27, 1102, -1, "", 1);// 169
			AddComplexComponent( (BaseAddon) this, 1173, 1, 0, 7, 1109, -1, "", 1);// 172
			AddComplexComponent( (BaseAddon) this, 1173, 1, 0, 37, 1109, -1, "", 1);// 173
			AddComplexComponent( (BaseAddon) this, 1173, 1, 1, 37, 1109, -1, "", 1);// 174
			AddComplexComponent( (BaseAddon) this, 1173, 1, -1, 37, 1109, -1, "", 1);// 175
			AddComplexComponent( (BaseAddon) this, 1173, 1, -2, 37, 1109, -1, "", 1);// 176
			AddComplexComponent( (BaseAddon) this, 1173, 1, -3, 37, 1109, -1, "", 1);// 177
			AddComplexComponent( (BaseAddon) this, 1173, 0, 1, 37, 1109, -1, "", 1);// 178
			AddComplexComponent( (BaseAddon) this, 1173, 2, -1, 37, 1109, -1, "", 1);// 179
			AddComplexComponent( (BaseAddon) this, 1173, 2, -2, 37, 1109, -1, "", 1);// 180
			AddComplexComponent( (BaseAddon) this, 1173, 2, -3, 37, 1109, -1, "", 1);// 181
			AddComplexComponent( (BaseAddon) this, 1173, 2, 0, 37, 1109, -1, "", 1);// 182
			AddComplexComponent( (BaseAddon) this, 1173, 0, 2, 37, 1109, -1, "", 1);// 183
			AddComplexComponent( (BaseAddon) this, 1173, 0, -2, 37, 1109, -1, "", 1);// 184
			AddComplexComponent( (BaseAddon) this, 1173, 2, 3, 27, 1109, -1, "", 1);// 188
			AddComplexComponent( (BaseAddon) this, 1173, 2, 2, 7, 1109, -1, "", 1);// 189
			AddComplexComponent( (BaseAddon) this, 1173, 2, 3, 7, 1109, -1, "", 1);// 190
			AddComplexComponent( (BaseAddon) this, 1173, 2, 3, 27, 1109, -1, "", 1);// 191
			AddComplexComponent( (BaseAddon) this, 1173, 2, 2, 27, 1109, -1, "", 1);// 192
			AddComplexComponent( (BaseAddon) this, 1173, 0, -1, 37, 1109, -1, "", 1);// 193
			AddComplexComponent( (BaseAddon) this, 100, 2, 2, 0, 1109, -1, "", 1);// 194
			AddComplexComponent( (BaseAddon) this, 1173, 0, 0, 37, 1109, -1, "", 1);// 196
			AddComplexComponent( (BaseAddon) this, 1173, 2, 0, 7, 1109, -1, "", 1);// 197
			AddComplexComponent( (BaseAddon) this, 100, 2, 3, 0, 1109, -1, "", 1);// 198
			AddComplexComponent( (BaseAddon) this, 1173, 2, 3, 37, 1109, -1, "", 1);// 199
			AddComplexComponent( (BaseAddon) this, 1173, 2, 2, 37, 1109, -1, "", 1);// 200
			AddComplexComponent( (BaseAddon) this, 1173, 1, 3, 37, 1109, -1, "", 1);// 201
			AddComplexComponent( (BaseAddon) this, 1173, 1, 2, 37, 1109, -1, "", 1);// 202
			AddComplexComponent( (BaseAddon) this, 1173, 0, 3, 37, 1109, -1, "", 1);// 203
			AddComplexComponent( (BaseAddon) this, 13882, 2, 3, 7, 1102, -1, "", 1);// 204
			AddComplexComponent( (BaseAddon) this, 13882, 3, -2, 7, 1102, -1, "", 1);// 205
			AddComplexComponent( (BaseAddon) this, 13878, 3, -3, 36, 1102, -1, "", 1);// 206
			AddComplexComponent( (BaseAddon) this, 13879, 2, -4, 36, 1102, -1, "", 1);// 207
			AddComplexComponent( (BaseAddon) this, 13882, 3, -3, 7, 1102, -1, "", 1);// 208
			AddComplexComponent( (BaseAddon) this, 13879, 1, -4, 36, 1102, -1, "", 1);// 209
			AddComplexComponent( (BaseAddon) this, 13878, 3, -2, 36, 1102, -1, "", 1);// 210
			AddComplexComponent( (BaseAddon) this, 1173, 0, -3, 37, 1109, -1, "", 1);// 211
			AddComplexComponent( (BaseAddon) this, 1173, 3, 0, 37, 1109, -1, "", 1);// 212
			AddComplexComponent( (BaseAddon) this, 100, 3, 1, 0, 1109, -1, "", 1);// 213
			AddComplexComponent( (BaseAddon) this, 99, 3, -4, 0, 1109, -1, "", 1);// 214
			AddComplexComponent( (BaseAddon) this, 1173, 1, -2, 7, 1109, -1, "", 1);// 215
			AddComplexComponent( (BaseAddon) this, 13882, 3, 1, 7, 1102, -1, "", 1);// 216
			AddComplexComponent( (BaseAddon) this, 13878, 3, 1, 36, 1102, -1, "", 1);// 217
			AddComplexComponent( (BaseAddon) this, 13882, 3, 0, 7, 1102, -1, "", 1);// 218
			AddComplexComponent( (BaseAddon) this, 13879, 0, -4, 36, 1102, -1, "", 1);// 219
			AddComplexComponent( (BaseAddon) this, 13883, 3, -4, 8, 1102, -1, "", 1);// 220
			AddComplexComponent( (BaseAddon) this, 13879, 3, -4, 36, 1102, -1, "", 1);// 221
			AddComplexComponent( (BaseAddon) this, 13883, 3, 1, 7, 1102, -1, "", 1);// 222
			AddComplexComponent( (BaseAddon) this, 13884, 3, -1, 6, 1102, 1, "", 1);// 223
			AddComplexComponent( (BaseAddon) this, 13878, 3, -1, 36, 1102, -1, "", 1);// 224
			AddComplexComponent( (BaseAddon) this, 13845, 3, 1, 27, 1102, -1, "", 1);// 225
			AddComplexComponent( (BaseAddon) this, 13884, 2, 2, 7, 1102, 1, "", 1);// 226
			AddComplexComponent( (BaseAddon) this, 13883, 0, -4, 7, 1102, -1, "", 1);// 227
			AddComplexComponent( (BaseAddon) this, 13879, 2, 3, 37, 1102, -1, "", 1);// 228
			AddComplexComponent( (BaseAddon) this, 13887, 1, -4, 7, 1102, 0, "", 1);// 229
			AddComplexComponent( (BaseAddon) this, 13835, 1, 4, 0, 1102, -1, "", 1);// 230
			AddComplexComponent( (BaseAddon) this, 13840, 0, 3, 7, 1102, -1, "", 1);// 231
			AddComplexComponent( (BaseAddon) this, 13835, 0, 4, 0, 1102, -1, "", 1);// 232
			AddComplexComponent( (BaseAddon) this, 13881, 0, 3, 27, 1102, -1, "", 1);// 233
			AddComplexComponent( (BaseAddon) this, 13881, 1, 3, 27, 1102, -1, "", 1);// 234
			AddComplexComponent( (BaseAddon) this, 13881, 3, -4, 27, 1102, -1, "", 1);// 235
			AddComplexComponent( (BaseAddon) this, 13881, 2, -4, 27, 1102, -1, "", 1);// 236
			AddComplexComponent( (BaseAddon) this, 13881, 1, -4, 27, 1102, -1, "", 1);// 237
			AddComplexComponent( (BaseAddon) this, 13881, 0, -4, 27, 1102, -1, "", 1);// 238
			AddComplexComponent( (BaseAddon) this, 13847, 2, 1, 35, 1102, -1, "", 1);// 239
			AddComplexComponent( (BaseAddon) this, 13880, 2, 2, 27, 1102, -1, "", 1);// 240
			AddComplexComponent( (BaseAddon) this, 13880, 3, 0, 27, 1102, -1, "", 1);// 241
			AddComplexComponent( (BaseAddon) this, 13845, 2, 3, 27, 1102, -1, "", 1);// 242
			AddComplexComponent( (BaseAddon) this, 13880, 3, -1, 27, 1102, -1, "", 1);// 243
			AddComplexComponent( (BaseAddon) this, 13883, 2, -4, 7, 1102, -1, "", 1);// 244

		}

		public NecroCityHealerNEWAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class NecroCityHealerNEWAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new NecroCityHealerNEWAddon();
			}
		}

		[Constructable]
		public NecroCityHealerNEWAddonDeed()
		{
			Name = "NecroCityHealerNEW";
		}

		public NecroCityHealerNEWAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}