/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//  Created by Hammerhand                                           //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class LamppostAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new LamppostAddonDeed();
			}
		}

		[ Constructable ]
		public LamppostAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 2848 );
			ac.Light = LightType.Circle300;
			AddComponent( ac, 0, 0, 0 );

		}

		public LamppostAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class LamppostAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new LamppostAddon();
			}
		}

		[Constructable]
		public LamppostAddonDeed()
		{
			Name = "Lamppost";
		}

		public LamppostAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}