
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class PlasterCityBankNEWAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {310, 0, -4, 7}, {310, -2, -4, 7}, {311, -3, 2, 7}// 1	2	3	
			, {311, -3, -1, 7}, {311, -3, -3, 7}, {1236, 0, 2, 7}// 4	5	6	
			, {1239, 0, 1, 7}, {1237, 0, 0, 7}, {1238, 0, -1, 7}// 7	8	9	
			, {1238, 0, -2, 7}, {1237, 0, -3, 7}, {1238, -1, 2, 7}// 10	11	12	
			, {1239, -1, 1, 7}, {1239, -1, 0, 7}, {1237, -1, -1, 7}// 13	14	15	
			, {1238, -1, -2, 7}, {1237, -1, -3, 7}, {1238, -2, 1, 7}// 16	17	18	
			, {1239, -2, 0, 7}, {1239, -2, -1, 7}, {1237, -2, -2, 7}// 19	20	21	
			, {1237, -2, -3, 7}, {100, -3, 1, 0}, {100, -3, 0, 0}// 22	23	24	
			, {100, -3, -2, 0}, {102, -3, -4, 0}, {311, -3, 0, 7}// 25	26	27	
			, {298, -3, -4, 7}, {1237, -2, 2, 7}, {99, 0, -4, 0}// 28	29	30	
			, {99, -1, -4, 0}, {99, -2, -4, 0}, {100, -3, 2, 0}// 31	32	33	
			, {100, -3, -1, 0}, {100, -3, -3, 0}, {1476, -2, -1, 27}// 34	35	36	
			, {1476, -2, 0, 27}, {1476, -2, 1, 27}, {1476, -2, 2, 27}// 37	38	39	
			, {1476, -1, -1, 30}, {1476, -1, 0, 30}, {1476, -1, 1, 30}// 40	41	42	
			, {1476, -1, 2, 30}, {2880, -2, -3, 7}, {2880, -1, -3, 7}// 43	47	48	
			, {3823, -2, -3, 13}, {3826, -1, -3, 13}, {100, 3, -3, 0}// 49	50	51	
			, {100, 3, -2, 0}, {100, 3, -1, 0}, {100, 0, 0, 0}// 52	53	54	
			, {100, 0, 1, 0}, {100, 0, 2, 0}, {2082, 0, -2, 7}// 55	56	57	
			, {2083, -2, -2, 7}, {2083, -1, -2, 7}, {99, 1, -1, 0}// 58	59	60	
			, {99, 2, -1, 0}, {99, 3, -1, 0}, {99, 1, -4, 0}// 61	62	63	
			, {99, 2, -4, 0}, {99, 3, -4, 0}, {311, 0, 0, 7}// 64	65	66	
			, {311, 0, 1, 7}, {311, 0, 2, 7}, {310, 1, -4, 7}// 67	68	69	
			, {310, 2, -4, 7}, {310, 3, -4, 7}, {1236, 0, -3, 7}// 70	71	72	
			, {1236, 0, -2, 7}, {1236, 0, -1, 7}, {1236, 1, -3, 7}// 73	74	75	
			, {1236, 1, -2, 7}, {1236, 1, -1, 7}, {1236, 2, -3, 7}// 76	77	78	
			, {1236, 2, -2, 7}, {1236, 2, -1, 7}, {1236, 3, -3, 7}// 79	80	81	
			, {1236, 3, -2, 7}, {1236, 3, -1, 7}, {311, 3, -3, 7}// 82	83	84	
			, {311, 3, -2, 7}, {311, 3, -1, 7}, {310, 1, -1, 7}// 85	86	87	
			, {310, 2, -1, 7}, {310, 3, -1, 7}, {1475, 0, 0, 30}// 88	89	90	
			, {1475, 0, 1, 30}, {1475, 0, 2, 30}, {1480, 1, 0, 27}// 91	92	93	
			, {1480, 0, -1, 30}, {8562, 1, -1, 30}, {8562, 1, -1, 25}// 94	95	96	
			, {8562, 2, 0, 27}, {8562, 3, 0, 27}, {8562, 4, 0, 27}// 97	98	99	
			, {8562, 4, -1, 30}, {8562, 3, -1, 30}, {8562, 2, -1, 30}// 100	101	102	
			, {8566, 0, -2, 30}, {8566, 1, -2, 30}, {8566, 2, -2, 30}// 103	104	105	
			, {8566, 3, -3, 25}, {8566, 4, -3, 26}, {8566, 4, -2, 29}// 106	107	108	
			, {8566, 3, -2, 30}, {8566, 0, -3, 25}, {8566, 1, -3, 25}// 109	110	111	
			, {8566, 2, -3, 24}, {8567, -1, -3, 25}, {8565, -2, -2, 26}// 112	113	114	
			, {1475, 1, 1, 27}, {1475, 1, 2, 27}, {1479, -1, -2, 28}// 115	116	117	
			, {1479, -2, -3, 24}, {2081, 0, -3, 7}, {7150, -2, -3, 16}// 118	119	120	
			, {7158, -1, -3, 16}, {2959, -1, 0, 7}, {6226, -1, 0, 13}// 121	122	123	
			, {311, -3, 3, 7}, {1237, 0, 3, 7}, {1237, -2, 3, 7}// 124	125	126	
			, {99, 0, 3, 0}, {99, -2, 3, 0}, {1239, -1, 3, 7}// 127	128	129	
			, {1873, -1, 4, 0}, {99, -1, 3, 0}, {100, -3, 3, 0}// 130	131	132	
			, {307, -2, 3, 7}, {1882, 0, 4, 0}, {1883, -2, 4, 0}// 133	134	135	
			, {312, 0, 3, 7}, {1476, -2, 3, 27}, {1476, -2, 4, 27}// 136	137	138	
			, {1476, -1, 3, 30}, {2968, -3, 4, 7}, {24, -1, 3, 27}// 139	140	141	
			, {24, 0, 3, 27}, {24, -2, 3, 27}, {100, 0, 3, 0}// 142	143	144	
			, {311, 0, 3, 7}, {1476, -1, 4, 30}, {1475, 0, 4, 29}// 145	146	147	
			, {1475, 0, 3, 29}, {1475, 1, 3, 27}, {1475, 1, 4, 27}// 148	149	150	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new PlasterCityBankNEWAddonDeed();
			}
		}

		[ Constructable ]
		public PlasterCityBankNEWAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 315, -3, 1, 7, 0, 0, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 315, -3, -2, 7, 0, 0, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 314, -1, -4, 7, 0, 0, "", 1);// 46

		}

		public PlasterCityBankNEWAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class PlasterCityBankNEWAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new PlasterCityBankNEWAddon();
			}
		}

		[Constructable]
		public PlasterCityBankNEWAddonDeed()
		{
			Name = "PlasterCityBankNEW";
		}

		public PlasterCityBankNEWAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}