/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class NecroCityMoongateAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				//return new NecroCityMoongateAddonDeed();
				return null;
			}
		}

		[ Constructable ]
		public NecroCityMoongateAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, -4, -4, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, -4, 4, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, -3, -3, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 1802 );
			ac.Hue = 1108;
			AddComponent( ac, -3, 4, 0 );
			ac = new AddonComponent( 1802 );
			ac.Hue = 1108;
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 1802 );
			ac.Hue = 1108;
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 1811 );
			ac.Hue = 1108;
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 1811 );
			ac.Hue = 1108;
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 1812 );
			ac.Hue = 1108;
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 1812 );
			ac.Hue = 1108;
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 1819 );
			ac.Hue = 1108;
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 1819 );
			ac.Hue = 1108;
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 1821 );
			ac.Hue = 1108;
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 1821 );
			ac.Hue = 1108;
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 1804 );
			ac.Hue = 1108;
			AddComponent( ac, 0, -4, 0 );
			ac = new AddonComponent( 1804 );
			ac.Hue = 1108;
			AddComponent( ac, -3, -4, 0 );
			ac = new AddonComponent( 1804 );
			ac.Hue = 1108;
			AddComponent( ac, 3, -4, 0 );
			ac = new AddonComponent( 1805 );
			ac.Hue = 1108;
			AddComponent( ac, -4, -3, 0 );
			ac = new AddonComponent( 1805 );
			ac.Hue = 1108;
			AddComponent( ac, -4, 0, 0 );
			ac = new AddonComponent( 1805 );
			ac.Hue = 1108;
			AddComponent( ac, -4, 3, 0 );
			ac = new AddonComponent( 1810 );
			ac.Hue = 1108;
			AddComponent( ac, -4, 2, 0 );
			ac = new AddonComponent( 1810 );
			ac.Hue = 1108;
			AddComponent( ac, -4, -1, 0 );
			ac = new AddonComponent( 1810 );
			ac.Hue = 1108;
			AddComponent( ac, -1, -4, 0 );
			ac = new AddonComponent( 1810 );
			ac.Hue = 1108;
			AddComponent( ac, 2, -4, 0 );
			ac = new AddonComponent( 1812 );
			ac.Hue = 1108;
			AddComponent( ac, -4, -2, 0 );
			ac = new AddonComponent( 1812 );
			ac.Hue = 1108;
			AddComponent( ac, -4, 1, 0 );
			ac = new AddonComponent( 1813 );
			ac.Hue = 1108;
			AddComponent( ac, -2, -4, 0 );
			ac = new AddonComponent( 1813 );
			ac.Hue = 1108;
			AddComponent( ac, 1, -4, 0 );
			ac = new AddonComponent( 1818 );
			ac.Hue = 1108;
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 1818 );
			ac.Hue = 1108;
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 1818 );
			ac.Hue = 1108;
			AddComponent( ac, 2, -3, 0 );
			ac = new AddonComponent( 1818 );
			ac.Hue = 1108;
			AddComponent( ac, -1, -3, 0 );
			ac = new AddonComponent( 1819 );
			ac.Hue = 1108;
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 1819 );
			ac.Hue = 1108;
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 1820 );
			ac.Hue = 1108;
			AddComponent( ac, -2, -3, 0 );
			ac = new AddonComponent( 1820 );
			ac.Hue = 1108;
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 1820 );
			ac.Hue = 1108;
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 1820 );
			ac.Hue = 1108;
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 1821 );
			ac.Hue = 1108;
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 1821 );
			ac.Hue = 1108;
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 4070 );
			ac.Hue = 1108;
			AddComponent( ac, -1, 0, 5 );
			ac = new AddonComponent( 4071 );
			ac.Hue = 1108;
			AddComponent( ac, -1, -1, 5 );
			ac = new AddonComponent( 4072 );
			ac.Hue = 1108;
			AddComponent( ac, 0, -1, 5 );
			ac = new AddonComponent( 4073 );
			ac.Hue = 1108;
			AddComponent( ac, -1, 1, 5 );
			ac = new AddonComponent( 4074 );
			ac.Hue = 1108;
			AddComponent( ac, 0, 0, 5 );
			ac = new AddonComponent( 4075 );
			ac.Hue = 1108;
			AddComponent( ac, 1, -1, 5 );
			ac = new AddonComponent( 4076 );
			ac.Hue = 1108;
			AddComponent( ac, 0, 1, 5 );
			ac = new AddonComponent( 4077 );
			ac.Hue = 1108;
			AddComponent( ac, 1, 1, 5 );
			ac = new AddonComponent( 4078 );
			ac.Hue = 1108;
			AddComponent( ac, 1, 0, 5 );
			ac = new AddonComponent( 8708 );
			AddComponent( ac, -4, 4, 10 );
			ac = new AddonComponent( 8708 );
			AddComponent( ac, -4, -4, 10 );
			ac = new AddonComponent( 6587 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, -4, 4, 30 );
			ac = new AddonComponent( 6587 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, -4, -4, 30 );
			ac = new AddonComponent( 6571 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, -4, 4, 32 );
			ac = new AddonComponent( 6571 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, -4, -4, 32 );
			ac = new AddonComponent( 2976 );
			AddComponent( ac, -4, 5, 10 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 4, -4, 0 );
			ac = new AddonComponent( 1801 );
			ac.Hue = 1108;
			AddComponent( ac, 4, 4, 0 );
			ac = new AddonComponent( 1803 );
			ac.Hue = 1108;
			AddComponent( ac, 4, -3, 0 );
			ac = new AddonComponent( 1803 );
			ac.Hue = 1108;
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 1803 );
			ac.Hue = 1108;
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 1811 );
			ac.Hue = 1108;
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 1811 );
			ac.Hue = 1108;
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 1813 );
			ac.Hue = 1108;
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 1813 );
			ac.Hue = 1108;
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 8708 );
			AddComponent( ac, 4, -4, 10 );
			ac = new AddonComponent( 8708 );
			AddComponent( ac, 4, 4, 10 );
			ac = new AddonComponent( 6587 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 4, -4, 30 );
			ac = new AddonComponent( 6587 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 4, 4, 30 );
			ac = new AddonComponent( 6571 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 4, 4, 32 );
			ac = new AddonComponent( 6571 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 4, -4, 32 );

		}

		public NecroCityMoongateAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	
}
