////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AshChainsawAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AshChainsawAddonDeed();
			}
		}

		[ Constructable ]
		public AshChainsawAddon()
		{
			AddComplexComponent( (BaseAddon) this, 10307, 1, 0, 0, 0, -1, "wooden stand", 1);// 1
			AddComplexComponent( (BaseAddon) this, 10307, 0, 0, 0, 0, -1, "wooden stand", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2474, 1, 0, 5, 1762, -1, "Ash's Chainsaw hand", 1);// 3
			AddComplexComponent( (BaseAddon) this, 4113, 1, 0, 7, 1762, -1, "Ash's Chainsaw hand", 1);// 4
			AddComplexComponent( (BaseAddon) this, 7133, 0, 0, 2, 2955, -1, "Ash's Chainsaw hand", 1);// 5
		}

		public AshChainsawAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AshChainsawAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AshChainsawAddon();
			}
		}

		[Constructable]
		public AshChainsawAddonDeed()
		{
			Name = "Ash's Chainsaw hand";
		}

		public AshChainsawAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}