////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class HauntedHouseBlankAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {13851, -9, -10, 5}, {13851, -9, -9, 5}, {13851, -9, -8, 5}// 1	2	3	
			, {13851, -9, -6, 5}, {13876, -9, -4, 51}, {13876, -9, -5, 48}// 4	5	6	
			, {13862, -9, -6, 45}, {13851, -9, -7, 5}, {4706, -9, -6, 45}// 7	8	9	
			, {4706, -9, -6, 38}, {13851, -8, -10, 5}, {13851, -7, -10, 5}// 10	11	12	
			, {13851, -8, -9, 5}, {13851, -7, -9, 5}, {13851, -8, -5, 5}// 13	14	15	
			, {13851, -7, -4, 5}, {13851, -8, -7, 5}, {13851, -7, -8, 5}// 16	17	18	
			, {13851, -7, -6, 5}, {13851, -8, -6, 5}, {13876, -7, -4, 51}// 19	20	21	
			, {13876, -8, -4, 51}, {13876, -7, -5, 48}, {13876, -8, -5, 47}// 22	23	24	
			, {13862, -7, -6, 45}, {13862, -8, -6, 45}, {13851, -7, -7, 5}// 25	26	27	
			, {13851, -8, -4, 5}, {13851, -7, -5, 5}, {13851, -8, -8, 5}// 28	29	30	
			, {4306, -9, -1, 26}, {13860, -9, -1, 45}, {13851, -9, 3, 5}// 125	126	127	
			, {13851, -9, 2, 5}, {13851, -9, 1, 5}, {13851, -9, 0, 5}// 128	129	130	
			, {13851, -9, -1, 5}, {13875, -9, -3, 51}, {13875, -9, -2, 48}// 131	132	133	
			, {13851, -9, -2, 5}, {13851, -8, -2, 5}, {13851, -7, -3, 5}// 134	135	136	
			, {13851, -7, -2, 5}, {13860, -7, -1, 45}, {13860, -8, -1, 44}// 137	138	139	
			, {13851, -7, 3, 5}, {13851, -7, 2, 5}, {13851, -7, 1, 5}// 140	141	142	
			, {13851, -7, 0, 5}, {13851, -7, -1, 5}, {13851, -8, 3, 5}// 143	144	145	
			, {13851, -8, 2, 5}, {13851, -8, 1, 5}, {13851, -8, 0, 5}// 146	147	148	
			, {13851, -8, -1, 5}, {13875, -7, -3, 51}, {13875, -8, -3, 51}// 149	150	151	
			, {13875, -7, -2, 48}, {13875, -8, -2, 47}, {13851, -8, -3, 5}// 152	153	154	
			, {6663, -8, -3, 28}, {13851, 1, -9, 5}, {13851, 1, -10, 5}// 155	237	238	
			, {13851, 0, -9, 5}, {13851, 0, -10, 5}, {13851, -1, -9, 5}// 239	240	241	
			, {13851, -1, -10, 5}, {13851, -3, -10, 5}, {13851, -3, -9, 5}// 242	243	244	
			, {13851, -4, -9, 5}, {13851, -4, -10, 5}, {13851, -5, -10, 5}// 245	246	247	
			, {13851, -5, -9, 5}, {13851, -2, -9, 5}, {13851, -2, -10, 5}// 248	249	250	
			, {12788, 3, -9, 2}, {12788, 2, -9, 2}, {13851, -6, -10, 5}// 251	252	253	
			, {13851, -6, -9, 5}, {13851, -4, -8, 5}, {13851, 0, -4, 5}// 254	255	256	
			, {13851, 0, -5, 5}, {13851, 0, -6, 5}, {13851, 0, -7, 5}// 257	258	259	
			, {13851, 0, -8, 5}, {13851, -1, -4, 5}, {13851, -1, -5, 5}// 260	261	262	
			, {13851, -1, -6, 5}, {13851, -1, -7, 5}, {13851, -1, -8, 5}// 263	264	265	
			, {13851, -3, -8, 5}, {13851, -3, -7, 5}, {13851, -2, -4, 5}// 266	267	268	
			, {13851, -2, -5, 5}, {13851, -6, -5, 5}, {13851, -6, -4, 5}// 269	270	271	
			, {13851, -2, -6, 5}, {13851, -2, -7, 5}, {13851, -2, -8, 5}// 272	273	274	
			, {13851, -5, -8, 5}, {13851, -6, -8, 5}, {13851, -5, -5, 5}// 275	276	277	
			, {13851, -3, -4, 5}, {13851, -3, -5, 5}, {13851, -3, -6, 5}// 278	279	280	
			, {13851, -5, -4, 5}, {13980, 2, -8, 2}, {13851, -4, -5, 5}// 281	282	283	
			, {4307, 4, -6, 2}, {6919, 6, -4, 2}, {13876, 4, -4, 28}// 284	285	286	
			, {13862, 4, -5, 24}, {13833, 4, -5, 5}, {13833, 5, -5, 2}// 287	288	289	
			, {13834, 5, -4, 2}, {12788, 3, -6, 2}, {12788, 2, -6, 2}// 290	291	292	
			, {12788, 3, -7, 2}, {12788, 3, -8, 2}, {12788, 2, -7, 2}// 293	294	295	
			, {12788, 2, -8, 2}, {13876, -3, -5, 43}, {13862, -4, -6, 40}// 296	297	298	
			, {13862, -3, -6, 40}, {13876, -5, -4, 51}, {13876, -6, -4, 51}// 299	300	301	
			, {13876, -5, -5, 47}, {13876, -6, -5, 48}, {13876, -4, -4, 51}// 302	303	304	
			, {13876, -4, -5, 48}, {13862, -5, -6, 45}, {13862, -6, -6, 45}// 305	306	307	
			, {13862, -4, -6, 45}, {13876, 2, -4, 28}, {13876, 3, -4, 28}// 308	309	310	
			, {13862, 3, -5, 25}, {13862, 2, -5, 24}, {13833, 2, -5, 5}// 311	312	313	
			, {13876, -4, -5, 43}, {13874, -3, -4, 46}, {13874, -4, -4, 46}// 314	315	316	
			, {13898, 1, -7, 5}, {13851, 1, -4, 5}, {13851, 1, -5, 5}// 317	318	319	
			, {13851, 1, -8, 5}, {13851, 1, -6, 5}, {13851, 1, -7, 5}// 320	321	322	
			, {4651, -6, -6, 2}, {13851, -4, -4, 5}, {13896, 1, -8, 5}// 323	324	325	
			, {6920, 8, -5, 2}, {13851, 0, -2, 5}, {13851, 0, -3, 5}// 326	496	497	
			, {13851, -1, -2, 5}, {13851, -1, -3, 5}, {13851, -2, -2, 5}// 498	499	500	
			, {13851, -4, -2, 5}, {13851, -2, -3, 5}, {13851, -6, -2, 5}// 501	502	503	
			, {13851, -5, -3, 5}, {13851, -3, -2, 5}, {13851, -3, -3, 5}// 504	505	506	
			, {13851, -5, -2, 5}, {6919, 7, 5, 2}, {6919, 6, 0, 3}// 507	508	509	
			, {6914, 7, 2, 2}, {6917, 7, -2, 2}, {13875, 4, -3, 27}// 510	511	512	
			, {13860, 4, -2, 23}, {13833, 4, -2, 5}, {13833, 5, -2, 2}// 513	514	515	
			, {13834, 5, -3, 2}, {4308, 2, 3, 2}, {4309, -2, 4, 2}// 516	517	518	
			, {4308, 0, 2, 25}, {4306, 3, -1, 2}, {4471, -1, 6, 5}// 519	520	521	
			, {3810, -1, 7, 3}, {3810, -1, 5, 3}, {3810, -1, 6, 3}// 522	523	524	
			, {3808, 0, 5, 2}, {3808, 0, 6, 2}, {4457, -1, 5, 4}// 525	526	527	
			, {4459, -1, 7, 5}, {3808, 0, 7, 2}, {12788, 3, 1, 2}// 528	529	530	
			, {12788, 3, -1, 2}, {12788, 3, 2, 2}, {12788, 2, -1, 2}// 531	532	533	
			, {13860, -5, -1, 45}, {13860, -6, -1, 44}, {13860, -4, -1, 45}// 534	535	536	
			, {13898, 1, 1, 5}, {13896, 1, 0, 5}, {13851, 1, 3, 5}// 537	538	539	
			, {13851, 1, 2, 5}, {13851, 1, 1, 5}, {13851, 1, 0, 5}// 540	541	542	
			, {13851, 1, -1, 5}, {13851, 0, 3, 5}, {13851, 0, 2, 5}// 543	544	545	
			, {13851, 0, 1, 5}, {13851, 0, 0, 5}, {13851, 0, -1, 5}// 546	547	548	
			, {13851, -1, 3, 5}, {13851, -1, 2, 5}, {13851, -1, 1, 5}// 549	550	551	
			, {13851, -1, 0, 5}, {13851, -1, -1, 5}, {13851, -2, 3, 5}// 552	553	554	
			, {13851, -2, 2, 5}, {13851, -2, 1, 5}, {13851, -2, 0, 5}// 555	556	557	
			, {13851, -2, -1, 5}, {13851, -3, 3, 5}, {13851, -3, 2, 5}// 558	559	560	
			, {13851, -3, 1, 5}, {13851, -3, 0, 5}, {13851, -3, -1, 5}// 561	562	563	
			, {13851, -4, 3, 5}, {13851, -4, 2, 5}, {13851, -4, 1, 5}// 564	565	566	
			, {13851, -4, 0, 5}, {13851, -4, -1, 5}, {13851, -5, 3, 5}// 567	568	569	
			, {13851, -5, 2, 5}, {13851, -5, 1, 5}, {13851, -5, 0, 5}// 570	571	572	
			, {13851, -5, -1, 5}, {13851, -6, 3, 5}, {13851, -6, 2, 5}// 573	574	575	
			, {13851, -6, 1, 5}, {13851, -6, 0, 5}, {13851, -6, -1, 5}// 576	577	578	
			, {12788, 2, 2, 2}, {13980, 2, 0, 2}, {4308, -4, -2, 25}// 579	580	581	
			, {13875, -4, -3, 43}, {13875, -3, -3, 43}, {13860, -4, -2, 40}// 582	583	584	
			, {13875, -5, -3, 51}, {13875, -6, -3, 50}, {13860, -3, -2, 39}// 585	586	587	
			, {13875, -4, -3, 51}, {13875, -5, -2, 47}, {13875, -6, -2, 48}// 588	589	590	
			, {13875, -4, -2, 48}, {13875, 2, -3, 27}, {13875, 3, -3, 28}// 591	592	593	
			, {13833, 2, -2, 5}, {13860, 3, -2, 25}, {13860, 2, -2, 24}// 594	595	596	
			, {13851, 1, -2, 5}, {13851, 1, -3, 5}, {12788, 2, 1, 2}// 597	598	599	
			, {5742, -4, -1, 31}, {6883, -4, 4, 7}, {13851, -4, -3, 5}// 600	601	602	
			, {3707, -3, -1, 25}, {6880, -4, 4, 7}, {6937, -4, 5, 2}// 603	604	605	
			, {12788, 3, 0, 2}, {12788, 2, 0, 2}, {6916, 6, 8, 2}// 606	607	608	
			, {3810, -1, 8, 3}, {4453, -1, 8, 5}, {3808, 0, 8, 2}// 609	610	611	
			, {6915, 8, 6, 2}, {13851, -6, -3, 5}// 612	826	
		}; 

		public override BaseAddonDeed Deed
		{
			get
			{
				return new HauntedHouseBlankAddonDeed();
			}
		}

		[ Constructable ]
		public HauntedHouseBlankAddon()
		{
            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );

			AddComplexComponent( (BaseAddon) this, 13851, -9, -10, 25, 1102, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 13848, -10, -11, 25, 1102, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 13878, -10, -9, 25, 1102, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 13880, -10, -10, 25, 1102, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 13851, -9, -9, 25, 1102, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 6955, -9, -10, 25, 2052, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 13881, -9, -11, 25, 1102, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 13882, -10, -10, 5, 1102, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 13883, -9, -11, 5, 1102, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 13849, -10, -11, 5, 1102, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 13847, -10, -11, 2, 1102, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 13879, -9, -11, 2, 1102, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 13878, -10, -10, 2, 1102, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 13878, -10, -9, 2, 1102, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 6955, -9, -10, 5, 794, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 6952, -9, -9, 5, 794, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 6952, -9, -9, 25, 2052, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 6952, -9, -8, 5, 794, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 13849, -10, -7, 25, 1102, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 13884, -10, -4, 25, 1102, 0, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 13882, -10, -6, 25, 1102, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 13883, -9, -7, 25, 1102, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 13882, -10, -5, 25, 1102, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 13878, -10, -7, 25, 1102, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 13878, -10, -8, 25, 1102, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 13851, -9, -4, 25, 1102, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 13851, -9, -5, 25, 1102, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 13851, -9, -6, 25, 1102, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 13851, -9, -7, 25, 1102, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 13851, -9, -8, 25, 1102, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 13841, -9, -5, 5, 1102, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 13882, -10, -7, 5, 1102, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 13883, -9, -7, 5, 1102, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 13882, -10, -6, 5, 1102, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 13846, -9, -6, 4, 1102, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 13882, -10, -5, 5, 1102, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 13882, -10, -4, 5, 1102, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 13851, -9, -4, 5, 1102, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 13851, -9, -5, 5, 1102, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 13878, -10, -8, 2, 1102, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 13878, -10, -7, 2, 1102, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 13878, -10, -6, 2, 1102, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 13878, -10, -5, 2, 1102, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 13878, -10, -4, 2, 1102, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 7677, -9, -8, 5, 794, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 424, -9, -4, 25, 1762, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 7383, -9, -4, 25, 1762, -1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 424, -9, -6, 28, 1762, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 6952, -9, -8, 25, 2052, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 7383, -9, -5, 25, 1762, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 6952, -9, -7, 5, 794, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 7371, -9, -6, 25, 1762, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 13879, -7, -11, 25, 1102, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 13879, -8, -11, 25, 1102, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 13851, -7, -9, 25, 1102, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 13851, -7, -10, 25, 1102, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 13851, -8, -9, 25, 1102, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 13851, -8, -10, 25, 1102, -1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 13885, -7, -11, 5, 1102, 0, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 13883, -8, -11, 5, 1102, -1, "", 1);// 90
			AddComplexComponent( (BaseAddon) this, 13879, -7, -11, 2, 1102, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 13879, -8, -11, 2, 1102, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 6959, -8, -10, 25, 2052, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 4651, -8, -4, 25, 1762, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 7421, -8, -6, 25, 1762, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 4653, -7, -4, 25, 1762, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 13840, -8, -7, 25, 1102, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 13851, -7, -4, 25, 1102, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 13851, -7, -5, 25, 1102, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 13851, -7, -6, 25, 1102, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 13851, -7, -7, 25, 1102, -1, "", 1);// 101
			AddComplexComponent( (BaseAddon) this, 13851, -7, -8, 25, 1102, -1, "", 1);// 102
			AddComplexComponent( (BaseAddon) this, 13851, -8, -4, 25, 1102, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 13851, -8, -5, 25, 1102, -1, "", 1);// 104
			AddComplexComponent( (BaseAddon) this, 13851, -8, -6, 25, 1102, -1, "", 1);// 105
			AddComplexComponent( (BaseAddon) this, 13851, -8, -7, 25, 1102, -1, "", 1);// 106
			AddComplexComponent( (BaseAddon) this, 13851, -8, -8, 25, 1102, -1, "", 1);// 107
			AddComplexComponent( (BaseAddon) this, 6974, -8, -6, 5, 794, -1, "", 1);// 108
			AddComplexComponent( (BaseAddon) this, 7677, -8, -5, 5, 794, -1, "", 1);// 109
			AddComplexComponent( (BaseAddon) this, 13001, -7, -7, 2, 1, -1, "", 1);// 110
			AddComplexComponent( (BaseAddon) this, 7677, -8, -7, 5, 794, -1, "", 1);// 111
			AddComplexComponent( (BaseAddon) this, 6969, -8, -5, 5, 794, -1, "", 1);// 112
			AddComplexComponent( (BaseAddon) this, 13001, -7, -8, 2, 1, -1, "", 1);// 113
			AddComplexComponent( (BaseAddon) this, 7418, -7, -5, 25, 1762, -1, "", 1);// 114
			AddComplexComponent( (BaseAddon) this, 5701, -8, -6, 25, 1762, -1, "", 1);// 115
			AddComplexComponent( (BaseAddon) this, 7422, -7, -6, 25, 1762, -1, "", 1);// 116
			AddComplexComponent( (BaseAddon) this, 7677, -8, -8, 5, 794, -1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 7677, -8, -4, 5, 794, -1, "", 1);// 118
			AddComplexComponent( (BaseAddon) this, 767, -7, -6, 0, 1102, -1, "", 1);// 119
			AddComplexComponent( (BaseAddon) this, 4655, -8, -4, 25, 1762, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 6952, -8, -4, 5, 794, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 7678, -8, -4, 5, 794, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 13882, -10, -9, 5, 1102, -1, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 13882, -10, -8, 5, 1102, -1, "", 1);// 124
			AddComplexComponent( (BaseAddon) this, 6952, -9, 1, 25, 2052, -1, "", 1);// 156
			AddComplexComponent( (BaseAddon) this, 13878, -10, 2, 25, 1102, -1, "", 1);// 157
			AddComplexComponent( (BaseAddon) this, 13878, -10, 1, 25, 1102, -1, "", 1);// 158
			AddComplexComponent( (BaseAddon) this, 13878, -10, 0, 25, 1102, -1, "", 1);// 159
			AddComplexComponent( (BaseAddon) this, 13878, -10, -1, 25, 1102, -1, "", 1);// 160
			AddComplexComponent( (BaseAddon) this, 13880, -10, 3, 25, 1102, -1, "", 1);// 161
			AddComplexComponent( (BaseAddon) this, 13851, -9, 3, 25, 1102, -1, "", 1);// 162
			AddComplexComponent( (BaseAddon) this, 13851, -9, 2, 25, 1102, -1, "", 1);// 163
			AddComplexComponent( (BaseAddon) this, 13851, -9, 1, 25, 1102, -1, "", 1);// 164
			AddComplexComponent( (BaseAddon) this, 13851, -9, 0, 25, 1102, -1, "", 1);// 165
			AddComplexComponent( (BaseAddon) this, 13851, -9, -1, 25, 1102, -1, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 13882, -10, 2, 5, 1102, -1, "", 1);// 167
			AddComplexComponent( (BaseAddon) this, 13882, -10, -1, 5, 1102, -1, "", 1);// 168
			AddComplexComponent( (BaseAddon) this, 13881, -9, 3, 25, 1102, -1, "", 1);// 169
			AddComplexComponent( (BaseAddon) this, 13882, -10, 3, 5, 1102, -1, "", 1);// 170
			AddComplexComponent( (BaseAddon) this, 13883, -9, 3, 5, 1102, -1, "", 1);// 171
			AddComplexComponent( (BaseAddon) this, 13878, -10, 3, 2, 1102, -1, "", 1);// 172
			AddComplexComponent( (BaseAddon) this, 13878, -10, 2, 2, 1102, -1, "", 1);// 173
			AddComplexComponent( (BaseAddon) this, 13878, -10, 1, 2, 1102, -1, "", 1);// 174
			AddComplexComponent( (BaseAddon) this, 13878, -10, 0, 2, 1102, -1, "", 1);// 175
			AddComplexComponent( (BaseAddon) this, 13878, -10, -1, 2, 1102, -1, "", 1);// 176
			AddComplexComponent( (BaseAddon) this, 13879, -9, 3, 2, 1102, -1, "", 1);// 177
			AddComplexComponent( (BaseAddon) this, 13883, -9, -2, 25, 1102, -1, "", 1);// 178
			AddComplexComponent( (BaseAddon) this, 13882, -10, -3, 25, 1102, -1, "", 1);// 179
			AddComplexComponent( (BaseAddon) this, 13882, -10, -2, 25, 1102, -1, "", 1);// 180
			AddComplexComponent( (BaseAddon) this, 13851, -9, -2, 25, 1102, -1, "", 1);// 181
			AddComplexComponent( (BaseAddon) this, 13851, -9, -3, 25, 1102, -1, "", 1);// 182
			AddComplexComponent( (BaseAddon) this, 13839, -9, -3, 5, 1102, -1, "", 1);// 183
			AddComplexComponent( (BaseAddon) this, 13883, -9, -3, 5, 1102, -1, "", 1);// 184
			AddComplexComponent( (BaseAddon) this, 13846, -9, -2, 5, 1102, -1, "", 1);// 185
			AddComplexComponent( (BaseAddon) this, 13882, -10, -3, 5, 1102, -1, "", 1);// 186
			AddComplexComponent( (BaseAddon) this, 13882, -10, -2, 5, 1102, -1, "", 1);// 187
			AddComplexComponent( (BaseAddon) this, 13851, -9, -3, 5, 1102, -1, "", 1);// 188
			AddComplexComponent( (BaseAddon) this, 13878, -10, -3, 2, 1102, -1, "", 1);// 189
			AddComplexComponent( (BaseAddon) this, 13878, -10, -2, 2, 1102, -1, "", 1);// 190
			AddComplexComponent( (BaseAddon) this, 7379, -9, -1, 25, 1762, -1, "", 1);// 191
			AddComplexComponent( (BaseAddon) this, 6919, -9, 1, 25, 1807, -1, "", 1);// 192
			AddComplexComponent( (BaseAddon) this, 7383, -9, -3, 25, 1762, -1, "", 1);// 193
			AddComplexComponent( (BaseAddon) this, 6972, -9, -1, 5, 794, -1, "", 1);// 194
			AddComplexComponent( (BaseAddon) this, 7677, -9, -1, 5, 794, -1, "", 1);// 195
			AddComplexComponent( (BaseAddon) this, 7069, -10, 5, 2, 2101, -1, "", 1);// 196
			AddComplexComponent( (BaseAddon) this, 6952, -9, 0, 5, 794, -1, "", 1);// 197
			AddComplexComponent( (BaseAddon) this, 6952, -9, 1, 5, 794, -1, "", 1);// 198
			AddComplexComponent( (BaseAddon) this, 7677, -9, 1, 5, 794, -1, "", 1);// 199
			AddComplexComponent( (BaseAddon) this, 6952, -9, 0, 25, 2052, -1, "", 1);// 200
			AddComplexComponent( (BaseAddon) this, 6952, -9, -1, 25, 2052, -1, "", 1);// 201
			AddComplexComponent( (BaseAddon) this, 6952, -9, 2, 25, 2052, -1, "", 1);// 202
			AddComplexComponent( (BaseAddon) this, 3308, -7, 4, 2, 1102, -1, "", 1);// 203
			AddComplexComponent( (BaseAddon) this, 6972, -8, -2, 5, 794, -1, "", 1);// 204
			AddComplexComponent( (BaseAddon) this, 3309, -7, 4, 2, 1102, -1, "", 1);// 205
			AddComplexComponent( (BaseAddon) this, 13885, -8, 3, 5, 1102, 0, "", 1);// 206
			AddComplexComponent( (BaseAddon) this, 13879, -7, 3, 25, 1102, -1, "", 1);// 207
			AddComplexComponent( (BaseAddon) this, 13879, -8, 3, 25, 1102, -1, "", 1);// 208
			AddComplexComponent( (BaseAddon) this, 13851, -7, 3, 25, 1102, -1, "", 1);// 209
			AddComplexComponent( (BaseAddon) this, 13851, -7, 2, 25, 1102, -1, "", 1);// 210
			AddComplexComponent( (BaseAddon) this, 13851, -7, 1, 25, 1102, -1, "", 1);// 211
			AddComplexComponent( (BaseAddon) this, 13851, -7, 0, 25, 1102, -1, "", 1);// 212
			AddComplexComponent( (BaseAddon) this, 13851, -7, -1, 25, 1102, -1, "", 1);// 213
			AddComplexComponent( (BaseAddon) this, 13851, -8, 3, 25, 1102, -1, "", 1);// 214
			AddComplexComponent( (BaseAddon) this, 13851, -8, 2, 25, 1102, -1, "", 1);// 215
			AddComplexComponent( (BaseAddon) this, 13851, -8, 1, 25, 1102, -1, "", 1);// 216
			AddComplexComponent( (BaseAddon) this, 13851, -8, 0, 25, 1102, -1, "", 1);// 217
			AddComplexComponent( (BaseAddon) this, 13851, -8, -1, 25, 1102, -1, "", 1);// 218
			AddComplexComponent( (BaseAddon) this, 13879, -7, 3, 2, 1102, -1, "", 1);// 219
			AddComplexComponent( (BaseAddon) this, 13879, -8, 3, 2, 1102, -1, "", 1);// 220
			AddComplexComponent( (BaseAddon) this, 13840, -8, -2, 25, 1102, -1, "", 1);// 221
			AddComplexComponent( (BaseAddon) this, 13851, -7, -2, 25, 1102, -1, "", 1);// 222
			AddComplexComponent( (BaseAddon) this, 13851, -7, -3, 25, 1102, -1, "", 1);// 223
			AddComplexComponent( (BaseAddon) this, 13851, -8, -2, 25, 1102, -1, "", 1);// 224
			AddComplexComponent( (BaseAddon) this, 13851, -8, -3, 25, 1102, -1, "", 1);// 225
			AddComplexComponent( (BaseAddon) this, 3276, -8, 5, 2, 2101, -1, "", 1);// 226
			AddComplexComponent( (BaseAddon) this, 6919, -8, 1, 25, 1807, -1, "", 1);// 227
			AddComplexComponent( (BaseAddon) this, 7678, -8, 0, 5, 1807, -1, "", 1);// 228
			AddComplexComponent( (BaseAddon) this, 7677, -8, 0, 5, 794, -1, "", 1);// 229
			AddComplexComponent( (BaseAddon) this, 6968, -8, -3, 5, 794, -1, "", 1);// 230
			AddComplexComponent( (BaseAddon) this, 6918, -7, 1, 25, 1807, -1, "", 1);// 231
			AddComplexComponent( (BaseAddon) this, 7069, -8, 6, 2, 2101, -1, "", 1);// 232
			AddComplexComponent( (BaseAddon) this, 7677, -8, -2, 5, 794, -1, "", 1);// 233
			AddComplexComponent( (BaseAddon) this, 13883, -7, 3, 5, 1102, -1, "", 1);// 234
			AddComplexComponent( (BaseAddon) this, 13882, -10, 0, 5, 1102, -1, "", 1);// 235
			AddComplexComponent( (BaseAddon) this, 13882, -10, 1, 5, 1102, -1, "", 1);// 236
			AddComplexComponent( (BaseAddon) this, 7069, 4, -9, 2, 2101, -1, "", 1);// 327
			AddComplexComponent( (BaseAddon) this, 12321, 2, -9, 0, 2101, -1, "", 1);// 328
			AddComplexComponent( (BaseAddon) this, 3277, 4, -11, 2, 2101, -1, "", 1);// 329
			AddComplexComponent( (BaseAddon) this, 13879, 3, -10, 2, 1102, -1, "", 1);// 330
			AddComplexComponent( (BaseAddon) this, 13879, 2, -10, 2, 1102, -1, "", 1);// 331
			AddComplexComponent( (BaseAddon) this, 13878, 3, -9, 2, 1102, -1, "", 1);// 332
			AddComplexComponent( (BaseAddon) this, 13879, 0, -11, 25, 1102, -1, "", 1);// 333
			AddComplexComponent( (BaseAddon) this, 13879, -1, -11, 25, 1102, -1, "", 1);// 334
			AddComplexComponent( (BaseAddon) this, 13879, -2, -11, 25, 1102, -1, "", 1);// 335
			AddComplexComponent( (BaseAddon) this, 13879, -3, -11, 25, 1102, -1, "", 1);// 336
			AddComplexComponent( (BaseAddon) this, 13879, -4, -11, 25, 1102, -1, "", 1);// 337
			AddComplexComponent( (BaseAddon) this, 13879, -5, -11, 25, 1102, -1, "", 1);// 338
			AddComplexComponent( (BaseAddon) this, 13879, -6, -11, 25, 1102, -1, "", 1);// 339
			AddComplexComponent( (BaseAddon) this, 13878, 1, -9, 25, 1102, -1, "", 1);// 340
			AddComplexComponent( (BaseAddon) this, 13880, 1, -10, 25, 1102, -1, "", 1);// 341
			AddComplexComponent( (BaseAddon) this, 13851, 1, -9, 25, 1102, -1, "", 1);// 342
			AddComplexComponent( (BaseAddon) this, 13851, 1, -10, 25, 1102, -1, "", 1);// 343
			AddComplexComponent( (BaseAddon) this, 13851, 0, -9, 25, 1102, -1, "", 1);// 344
			AddComplexComponent( (BaseAddon) this, 13851, 0, -10, 25, 1102, -1, "", 1);// 345
			AddComplexComponent( (BaseAddon) this, 13851, -1, -9, 25, 1102, -1, "", 1);// 346
			AddComplexComponent( (BaseAddon) this, 13851, -1, -10, 25, 1102, -1, "", 1);// 347
			AddComplexComponent( (BaseAddon) this, 13851, -2, -9, 25, 1102, -1, "", 1);// 348
			AddComplexComponent( (BaseAddon) this, 13851, -2, -10, 25, 1102, -1, "", 1);// 349
			AddComplexComponent( (BaseAddon) this, 13851, -3, -9, 25, 1102, -1, "", 1);// 350
			AddComplexComponent( (BaseAddon) this, 13851, -3, -10, 25, 1102, -1, "", 1);// 351
			AddComplexComponent( (BaseAddon) this, 13851, -4, -9, 25, 1102, -1, "", 1);// 352
			AddComplexComponent( (BaseAddon) this, 13851, -4, -10, 25, 1102, -1, "", 1);// 353
			AddComplexComponent( (BaseAddon) this, 13851, -5, -9, 25, 1102, -1, "", 1);// 354
			AddComplexComponent( (BaseAddon) this, 13851, -5, -10, 25, 1102, -1, "", 1);// 355
			AddComplexComponent( (BaseAddon) this, 13851, -6, -9, 25, 1102, -1, "", 1);// 356
			AddComplexComponent( (BaseAddon) this, 13851, -6, -10, 25, 1102, -1, "", 1);// 357
			AddComplexComponent( (BaseAddon) this, 13881, 1, -11, 25, 1102, -1, "", 1);// 358
			AddComplexComponent( (BaseAddon) this, 13885, -6, -11, 5, 1102, 0, "", 1);// 359
			AddComplexComponent( (BaseAddon) this, 13885, -3, -11, 5, 1102, 0, "", 1);// 360
			AddComplexComponent( (BaseAddon) this, 13885, -2, -11, 5, 1102, 0, "", 1);// 361
			AddComplexComponent( (BaseAddon) this, 13883, -1, -11, 5, 1102, -1, "", 1);// 362
			AddComplexComponent( (BaseAddon) this, 13883, 0, -11, 5, 1102, -1, "", 1);// 363
			AddComplexComponent( (BaseAddon) this, 13882, 1, -10, 5, 1102, -1, "", 1);// 364
			AddComplexComponent( (BaseAddon) this, 13883, 1, -11, 5, 1102, -1, "", 1);// 365
			AddComplexComponent( (BaseAddon) this, 13884, 1, -9, 5, 1102, 0, "", 1);// 366
			AddComplexComponent( (BaseAddon) this, 13879, -5, -11, 2, 1102, -1, "", 1);// 367
			AddComplexComponent( (BaseAddon) this, 13879, -6, -11, 2, 1102, -1, "", 1);// 368
			AddComplexComponent( (BaseAddon) this, 13879, -2, -11, 2, 1102, -1, "", 1);// 369
			AddComplexComponent( (BaseAddon) this, 13879, -3, -11, 2, 1102, -1, "", 1);// 370
			AddComplexComponent( (BaseAddon) this, 13879, -4, -11, 2, 1102, -1, "", 1);// 371
			AddComplexComponent( (BaseAddon) this, 13879, 1, -11, 2, 1102, -1, "", 1);// 372
			AddComplexComponent( (BaseAddon) this, 13879, 0, -11, 2, 1102, -1, "", 1);// 373
			AddComplexComponent( (BaseAddon) this, 13879, -1, -11, 2, 1102, -1, "", 1);// 374
			AddComplexComponent( (BaseAddon) this, 13878, 1, -10, 2, 1102, -1, "", 1);// 375
			AddComplexComponent( (BaseAddon) this, 13878, 1, -9, 2, 1102, -1, "", 1);// 376
			AddComplexComponent( (BaseAddon) this, 7882, 1, -9, 28, 1102, -1, "", 1);// 377
			AddComplexComponent( (BaseAddon) this, 6915, -3, -10, 25, 1807, -1, "", 1);// 378
			AddComplexComponent( (BaseAddon) this, 7677, -5, -9, 5, 794, -1, "", 1);// 379
			AddComplexComponent( (BaseAddon) this, 7070, 5, -10, 2, 2101, -1, "", 1);// 380
			AddComplexComponent( (BaseAddon) this, 6920, 0, -10, 25, 1807, -1, "", 1);// 381
			AddComplexComponent( (BaseAddon) this, 6972, -4, -5, 5, 794, -1, "", 1);// 382
			AddComplexComponent( (BaseAddon) this, 13001, -5, -7, 2, 1, -1, "", 1);// 383
			AddComplexComponent( (BaseAddon) this, 13001, -6, -7, 2, 1, -1, "", 1);// 384
			AddComplexComponent( (BaseAddon) this, 6952, -3, -7, 5, 794, -1, "", 1);// 385
			AddComplexComponent( (BaseAddon) this, 7882, 1, -4, 25, 1102, -1, "", 1);// 386
			AddComplexComponent( (BaseAddon) this, 1305, 7, -5, 2, 951, -1, "", 1);// 387
			AddComplexComponent( (BaseAddon) this, 1305, 6, -5, 2, 951, -1, "", 1);// 388
			AddComplexComponent( (BaseAddon) this, 1305, 6, -4, 2, 951, -1, "", 1);// 389
			AddComplexComponent( (BaseAddon) this, 13851, 4, -4, 5, 1102, -1, "", 1);// 390
			AddComplexComponent( (BaseAddon) this, 13851, 4, -5, 5, 1102, -1, "", 1);// 391
			AddComplexComponent( (BaseAddon) this, 13879, 4, -6, 2, 1102, -1, "", 1);// 392
			AddComplexComponent( (BaseAddon) this, 13878, 4, -4, 2, 1102, -1, "", 1);// 393
			AddComplexComponent( (BaseAddon) this, 13878, 4, -5, 2, 1102, -1, "", 1);// 394
			AddComplexComponent( (BaseAddon) this, 13879, 3, -6, 5, 1102, -1, "", 1);// 395
			AddComplexComponent( (BaseAddon) this, 13878, 3, -6, 2, 1102, -1, "", 1);// 396
			AddComplexComponent( (BaseAddon) this, 13878, 3, -7, 2, 1102, -1, "", 1);// 397
			AddComplexComponent( (BaseAddon) this, 13878, 3, -8, 2, 1102, -1, "", 1);// 398
			AddComplexComponent( (BaseAddon) this, 13838, -6, -7, 25, 1102, -1, "", 1);// 399
			AddComplexComponent( (BaseAddon) this, 13841, -5, -5, 25, 1102, -1, "", 1);// 400
			AddComplexComponent( (BaseAddon) this, 13882, -5, -6, 25, 1102, -1, "", 1);// 401
			AddComplexComponent( (BaseAddon) this, 13883, -5, -7, 25, 1102, -1, "", 1);// 402
			AddComplexComponent( (BaseAddon) this, 13842, -4, -6, 25, 1102, -1, "", 1);// 403
			AddComplexComponent( (BaseAddon) this, 13878, 1, -6, 25, 1102, -1, "", 1);// 404
			AddComplexComponent( (BaseAddon) this, 13878, 1, -7, 25, 1102, -1, "", 1);// 405
			AddComplexComponent( (BaseAddon) this, 13878, 1, -8, 25, 1102, -1, "", 1);// 406
			AddComplexComponent( (BaseAddon) this, 13878, 1, -4, 25, 1102, -1, "", 1);// 407
			AddComplexComponent( (BaseAddon) this, 13878, 1, -5, 25, 1102, -1, "", 1);// 408
			AddComplexComponent( (BaseAddon) this, 13851, 1, -4, 25, 1102, -1, "", 1);// 409
			AddComplexComponent( (BaseAddon) this, 13851, 1, -5, 25, 1102, -1, "", 1);// 410
			AddComplexComponent( (BaseAddon) this, 13851, 1, -6, 25, 1102, -1, "", 1);// 411
			AddComplexComponent( (BaseAddon) this, 13851, 1, -7, 25, 1102, -1, "", 1);// 412
			AddComplexComponent( (BaseAddon) this, 13851, 1, -8, 25, 1102, -1, "", 1);// 413
			AddComplexComponent( (BaseAddon) this, 13851, 0, -4, 25, 1102, -1, "", 1);// 414
			AddComplexComponent( (BaseAddon) this, 13851, 0, -5, 25, 1102, -1, "", 1);// 415
			AddComplexComponent( (BaseAddon) this, 13851, 0, -6, 25, 1102, -1, "", 1);// 416
			AddComplexComponent( (BaseAddon) this, 13851, 0, -7, 25, 1102, -1, "", 1);// 417
			AddComplexComponent( (BaseAddon) this, 13851, 0, -8, 25, 1102, -1, "", 1);// 418
			AddComplexComponent( (BaseAddon) this, 13851, -1, -4, 25, 1102, -1, "", 1);// 419
			AddComplexComponent( (BaseAddon) this, 13851, -1, -5, 25, 1102, -1, "", 1);// 420
			AddComplexComponent( (BaseAddon) this, 13851, -1, -6, 25, 1102, -1, "", 1);// 421
			AddComplexComponent( (BaseAddon) this, 13851, -1, -7, 25, 1102, -1, "", 1);// 422
			AddComplexComponent( (BaseAddon) this, 13851, -1, -8, 25, 1102, -1, "", 1);// 423
			AddComplexComponent( (BaseAddon) this, 13851, -2, -4, 25, 1102, -1, "", 1);// 424
			AddComplexComponent( (BaseAddon) this, 13851, -2, -5, 25, 1102, -1, "", 1);// 425
			AddComplexComponent( (BaseAddon) this, 13851, -2, -6, 25, 1102, -1, "", 1);// 426
			AddComplexComponent( (BaseAddon) this, 13851, -2, -7, 25, 1102, -1, "", 1);// 427
			AddComplexComponent( (BaseAddon) this, 13851, -2, -8, 25, 1102, -1, "", 1);// 428
			AddComplexComponent( (BaseAddon) this, 13851, -3, -4, 25, 1102, -1, "", 1);// 429
			AddComplexComponent( (BaseAddon) this, 13851, -3, -5, 25, 1102, -1, "", 1);// 430
			AddComplexComponent( (BaseAddon) this, 13851, -3, -6, 25, 1102, -1, "", 1);// 431
			AddComplexComponent( (BaseAddon) this, 13851, -3, -7, 25, 1102, -1, "", 1);// 432
			AddComplexComponent( (BaseAddon) this, 13851, -3, -8, 25, 1102, -1, "", 1);// 433
			AddComplexComponent( (BaseAddon) this, 13851, -4, -4, 25, 1102, -1, "", 1);// 434
			AddComplexComponent( (BaseAddon) this, 13851, -4, -5, 25, 1102, -1, "", 1);// 435
			AddComplexComponent( (BaseAddon) this, 13851, -4, -6, 25, 1102, -1, "", 1);// 436
			AddComplexComponent( (BaseAddon) this, 13851, -4, -7, 25, 1102, -1, "", 1);// 437
			AddComplexComponent( (BaseAddon) this, 13851, -4, -8, 25, 1102, -1, "", 1);// 438
			AddComplexComponent( (BaseAddon) this, 13851, -5, -4, 25, 1102, -1, "", 1);// 439
			AddComplexComponent( (BaseAddon) this, 13851, -5, -5, 25, 1102, -1, "", 1);// 440
			AddComplexComponent( (BaseAddon) this, 13851, -5, -6, 25, 1102, -1, "", 1);// 441
			AddComplexComponent( (BaseAddon) this, 13851, -5, -7, 25, 1102, -1, "", 1);// 442
			AddComplexComponent( (BaseAddon) this, 13851, -5, -8, 25, 1102, -1, "", 1);// 443
			AddComplexComponent( (BaseAddon) this, 13851, -6, -4, 25, 1102, -1, "", 1);// 444
			AddComplexComponent( (BaseAddon) this, 13851, -6, -5, 25, 1102, -1, "", 1);// 445
			AddComplexComponent( (BaseAddon) this, 13851, -6, -6, 25, 1102, -1, "", 1);// 446
			AddComplexComponent( (BaseAddon) this, 13851, -6, -7, 25, 1102, -1, "", 1);// 447
			AddComplexComponent( (BaseAddon) this, 13851, -6, -8, 25, 1102, -1, "", 1);// 448
			AddComplexComponent( (BaseAddon) this, 13882, 1, -6, 5, 1102, -1, "", 1);// 449
			AddComplexComponent( (BaseAddon) this, 13884, 1, -5, 5, 1102, 0, "", 1);// 450
			AddComplexComponent( (BaseAddon) this, 13842, 2, -5, 10, 1102, -1, "", 1);// 451
			AddComplexComponent( (BaseAddon) this, 13879, 3, -6, 2, 1102, -1, "", 1);// 452
			AddComplexComponent( (BaseAddon) this, 13879, 2, -6, 2, 1102, -1, "", 1);// 453
			AddComplexComponent( (BaseAddon) this, 13851, 3, -4, 5, 1102, -1, "", 1);// 454
			AddComplexComponent( (BaseAddon) this, 13851, 3, -5, 5, 1102, -1, "", 1);// 455
			AddComplexComponent( (BaseAddon) this, 13851, 2, -4, 5, 1102, -1, "", 1);// 456
			AddComplexComponent( (BaseAddon) this, 13851, 2, -5, 5, 1102, -1, "", 1);// 457
			AddComplexComponent( (BaseAddon) this, 13878, 1, -8, 2, 1102, -1, "", 1);// 458
			AddComplexComponent( (BaseAddon) this, 13878, 1, -7, 2, 1102, -1, "", 1);// 459
			AddComplexComponent( (BaseAddon) this, 4109, 5, -6, 2, 1762, -1, "", 1);// 460
			AddComplexComponent( (BaseAddon) this, 3892, 5, -6, 2, 1762, -1, "", 1);// 461
			AddComplexComponent( (BaseAddon) this, 3892, 6, -6, 1, 1762, -1, "", 1);// 462
			AddComplexComponent( (BaseAddon) this, 3892, 5, -5, 7, 1762, -1, "", 1);// 463
			AddComplexComponent( (BaseAddon) this, 7677, -5, -4, 5, 794, -1, "", 1);// 464
			AddComplexComponent( (BaseAddon) this, 1258, -4, -7, 2, 1, -1, "", 1);// 465
			AddComplexComponent( (BaseAddon) this, 6916, -3, -6, 25, 1807, -1, "", 1);// 466
			AddComplexComponent( (BaseAddon) this, 7678, -3, -8, 5, 794, -1, "", 1);// 467
			AddComplexComponent( (BaseAddon) this, 7678, -2, -5, 5, 794, -1, "", 1);// 468
			AddComplexComponent( (BaseAddon) this, 7678, -1, -7, 5, 794, -1, "", 1);// 469
			AddComplexComponent( (BaseAddon) this, 7678, -3, -5, 5, 1807, -1, "", 1);// 470
			AddComplexComponent( (BaseAddon) this, 6951, -5, -5, 5, 794, -1, "", 1);// 471
			AddComplexComponent( (BaseAddon) this, 3391, 7, -4, 2, 2101, -1, "", 1);// 472
			AddComplexComponent( (BaseAddon) this, 7678, -2, -8, 5, 1807, -1, "", 1);// 473
			AddComplexComponent( (BaseAddon) this, 1847, -6, -6, 0, 2101, -1, "", 1);// 474
			AddComplexComponent( (BaseAddon) this, 7678, -1, -4, 5, 794, -1, "", 1);// 475
			AddComplexComponent( (BaseAddon) this, 6973, -6, -5, 5, 794, -1, "", 1);// 476
			AddComplexComponent( (BaseAddon) this, 1075, -4, -5, 27, 2101, -1, "", 1);// 477
			AddComplexComponent( (BaseAddon) this, 6970, 1, -4, 5, 794, -1, "", 1);// 478
			AddComplexComponent( (BaseAddon) this, 1258, -4, -6, 1, 1, -1, "", 1);// 479
			AddComplexComponent( (BaseAddon) this, 1258, -5, -6, 2, 1, -1, "", 1);// 480
			AddComplexComponent( (BaseAddon) this, 1258, -6, -6, 1, 1, -1, "", 1);// 481
			AddComplexComponent( (BaseAddon) this, 6972, -3, -6, 5, 794, -1, "", 1);// 482
			AddComplexComponent( (BaseAddon) this, 7882, 1, -7, 28, 1102, -1, "", 1);// 483
			AddComplexComponent( (BaseAddon) this, 7677, -5, -5, 5, 794, -1, "", 1);// 484
			AddComplexComponent( (BaseAddon) this, 766, -4, -8, 0, 1102, -1, "", 1);// 485
			AddComplexComponent( (BaseAddon) this, 766, -5, -8, 0, 1102, -1, "", 1);// 486
			AddComplexComponent( (BaseAddon) this, 766, -6, -8, 0, 1102, -1, "", 1);// 487
			AddComplexComponent( (BaseAddon) this, 6971, 1, -5, 5, 794, -1, "", 1);// 488
			AddComplexComponent( (BaseAddon) this, 1847, -4, -6, 0, 2101, -1, "", 1);// 489
			AddComplexComponent( (BaseAddon) this, 7677, -1, -8, 5, 794, -1, "", 1);// 490
			AddComplexComponent( (BaseAddon) this, 1847, -5, -6, 1, 2101, -1, "", 1);// 491
			AddComplexComponent( (BaseAddon) this, 1305, 8, -4, 2, 951, -1, "", 1);// 492
			AddComplexComponent( (BaseAddon) this, 1305, 8, -5, 2, 951, -1, "", 1);// 493
			AddComplexComponent( (BaseAddon) this, 13883, -5, -11, 5, 1102, -1, "", 1);// 494
			AddComplexComponent( (BaseAddon) this, 13883, -4, -11, 5, 1102, -1, "", 1);// 495
			AddComplexComponent( (BaseAddon) this, 3309, 1, 4, 2, 1102, -1, "", 1);// 613
			AddComplexComponent( (BaseAddon) this, 13879, -3, 3, 25, 1102, -1, "", 1);// 614
			AddComplexComponent( (BaseAddon) this, 3309, 0, 4, 2, 1102, -1, "", 1);// 615
			AddComplexComponent( (BaseAddon) this, 3703, -4, 4, 2, 1109, -1, "", 1);// 616
			AddComplexComponent( (BaseAddon) this, 4014, -3, 4, 4, 1109, -1, "", 1);// 617
			AddComplexComponent( (BaseAddon) this, 13879, -4, 3, 25, 1102, -1, "", 1);// 618
			AddComplexComponent( (BaseAddon) this, 7608, -3, 5, 2, 1109, -1, "", 1);// 619
			AddComplexComponent( (BaseAddon) this, 1305, 7, 7, 2, 951, -1, "", 1);// 620
			AddComplexComponent( (BaseAddon) this, 1305, 7, 6, 3, 951, -1, "", 1);// 621
			AddComplexComponent( (BaseAddon) this, 1305, 7, 5, 2, 951, -1, "", 1);// 622
			AddComplexComponent( (BaseAddon) this, 1305, 6, 7, 2, 951, -1, "", 1);// 623
			AddComplexComponent( (BaseAddon) this, 1305, 6, 6, 2, 951, -1, "", 1);// 624
			AddComplexComponent( (BaseAddon) this, 1305, 6, 5, 3, 951, -1, "", 1);// 625
			AddComplexComponent( (BaseAddon) this, 1305, 7, 3, 2, 951, -1, "", 1);// 626
			AddComplexComponent( (BaseAddon) this, 1305, 7, 2, 2, 951, -1, "", 1);// 627
			AddComplexComponent( (BaseAddon) this, 1305, 7, 1, 2, 951, -1, "", 1);// 628
			AddComplexComponent( (BaseAddon) this, 1305, 7, 0, 2, 951, -1, "", 1);// 629
			AddComplexComponent( (BaseAddon) this, 1305, 7, -1, 2, 951, -1, "", 1);// 630
			AddComplexComponent( (BaseAddon) this, 1305, 6, 4, 2, 951, -1, "", 1);// 631
			AddComplexComponent( (BaseAddon) this, 1305, 6, 2, 2, 951, -1, "", 1);// 632
			AddComplexComponent( (BaseAddon) this, 1305, 6, 1, 2, 951, -1, "", 1);// 633
			AddComplexComponent( (BaseAddon) this, 1305, 6, 0, 3, 951, -1, "", 1);// 634
			AddComplexComponent( (BaseAddon) this, 1305, 6, -1, 2, 951, -1, "", 1);// 635
			AddComplexComponent( (BaseAddon) this, 1305, 7, -2, 2, 951, -1, "", 1);// 636
			AddComplexComponent( (BaseAddon) this, 1305, 7, -3, 2, 951, -1, "", 1);// 637
			AddComplexComponent( (BaseAddon) this, 1305, 6, -2, 2, 951, -1, "", 1);// 638
			AddComplexComponent( (BaseAddon) this, 1305, 6, -3, 2, 951, -1, "", 1);// 639
			AddComplexComponent( (BaseAddon) this, 2959, -4, -1, 25, 1807, -1, "", 1);// 640
			AddComplexComponent( (BaseAddon) this, 13842, 4, -2, 10, 1102, -1, "", 1);// 641
			AddComplexComponent( (BaseAddon) this, 13851, 4, -3, 5, 1102, -1, "", 1);// 642
			AddComplexComponent( (BaseAddon) this, 13851, 4, -2, 5, 1102, -1, "", 1);// 643
			AddComplexComponent( (BaseAddon) this, 13879, 4, -2, 2, 1102, -1, "", 1);// 644
			AddComplexComponent( (BaseAddon) this, 13878, 4, -3, 2, 1102, -1, "", 1);// 645
			AddComplexComponent( (BaseAddon) this, 13878, 3, -1, 2, 1102, -1, "", 1);// 646
			AddComplexComponent( (BaseAddon) this, 13878, 3, 0, 2, 1102, -1, "", 1);// 647
			AddComplexComponent( (BaseAddon) this, 13878, 3, 1, 2, 1102, -1, "", 1);// 648
			AddComplexComponent( (BaseAddon) this, 13844, 3, 2, 2, 1102, -1, "", 1);// 649
			AddComplexComponent( (BaseAddon) this, 13879, 2, 2, 2, 1102, -1, "", 1);// 650
			AddComplexComponent( (BaseAddon) this, 13883, -4, 3, 5, 1102, -1, "", 1);// 651
			AddComplexComponent( (BaseAddon) this, 13878, 1, 2, 25, 1102, -1, "", 1);// 652
			AddComplexComponent( (BaseAddon) this, 13878, 1, 1, 25, 1102, -1, "", 1);// 653
			AddComplexComponent( (BaseAddon) this, 13878, 1, 0, 25, 1102, -1, "", 1);// 654
			AddComplexComponent( (BaseAddon) this, 13878, 1, -1, 25, 1102, -1, "", 1);// 655
			AddComplexComponent( (BaseAddon) this, 13879, 0, 3, 25, 1102, -1, "", 1);// 656
			AddComplexComponent( (BaseAddon) this, 13879, -1, 3, 25, 1102, -1, "", 1);// 657
			AddComplexComponent( (BaseAddon) this, 13845, 1, 3, 25, 1102, -1, "", 1);// 658
			AddComplexComponent( (BaseAddon) this, 13851, 1, 2, 25, 1102, -1, "", 1);// 659
			AddComplexComponent( (BaseAddon) this, 13851, 1, 1, 25, 1102, -1, "", 1);// 660
			AddComplexComponent( (BaseAddon) this, 13851, 1, 0, 25, 1102, -1, "", 1);// 661
			AddComplexComponent( (BaseAddon) this, 13851, 1, -1, 25, 1102, -1, "", 1);// 662
			AddComplexComponent( (BaseAddon) this, 13851, 0, 3, 25, 1102, -1, "", 1);// 663
			AddComplexComponent( (BaseAddon) this, 13851, 0, 2, 25, 1102, -1, "", 1);// 664
			AddComplexComponent( (BaseAddon) this, 13851, 0, 1, 25, 1102, -1, "", 1);// 665
			AddComplexComponent( (BaseAddon) this, 13851, 0, 0, 25, 1102, -1, "", 1);// 666
			AddComplexComponent( (BaseAddon) this, 13851, 0, -1, 25, 1102, -1, "", 1);// 667
			AddComplexComponent( (BaseAddon) this, 13851, -1, 3, 25, 1102, -1, "", 1);// 668
			AddComplexComponent( (BaseAddon) this, 13851, -1, 2, 25, 1102, -1, "", 1);// 669
			AddComplexComponent( (BaseAddon) this, 13851, -1, 1, 25, 1102, -1, "", 1);// 670
			AddComplexComponent( (BaseAddon) this, 13851, -1, 0, 25, 1102, -1, "", 1);// 671
			AddComplexComponent( (BaseAddon) this, 13851, -1, -1, 25, 1102, -1, "", 1);// 672
			AddComplexComponent( (BaseAddon) this, 13851, -2, 3, 25, 1102, -1, "", 1);// 673
			AddComplexComponent( (BaseAddon) this, 13851, -2, 2, 25, 1102, -1, "", 1);// 674
			AddComplexComponent( (BaseAddon) this, 13851, -2, 1, 25, 1102, -1, "", 1);// 675
			AddComplexComponent( (BaseAddon) this, 13851, -2, 0, 25, 1102, -1, "", 1);// 676
			AddComplexComponent( (BaseAddon) this, 13851, -2, -1, 25, 1102, -1, "", 1);// 677
			AddComplexComponent( (BaseAddon) this, 13851, -3, 3, 25, 1102, -1, "", 1);// 678
			AddComplexComponent( (BaseAddon) this, 13851, -3, 2, 25, 1102, -1, "", 1);// 679
			AddComplexComponent( (BaseAddon) this, 13851, -3, 1, 25, 1102, -1, "", 1);// 680
			AddComplexComponent( (BaseAddon) this, 13851, -3, 0, 25, 1102, -1, "", 1);// 681
			AddComplexComponent( (BaseAddon) this, 13851, -3, -1, 25, 1102, -1, "", 1);// 682
			AddComplexComponent( (BaseAddon) this, 13851, -4, 3, 25, 1102, -1, "", 1);// 683
			AddComplexComponent( (BaseAddon) this, 13851, -4, 2, 25, 1102, -1, "", 1);// 684
			AddComplexComponent( (BaseAddon) this, 13851, -4, 1, 25, 1102, -1, "", 1);// 685
			AddComplexComponent( (BaseAddon) this, 13851, -4, 0, 25, 1102, -1, "", 1);// 686
			AddComplexComponent( (BaseAddon) this, 13851, -4, -1, 25, 1102, -1, "", 1);// 687
			AddComplexComponent( (BaseAddon) this, 13851, -5, 3, 25, 1102, -1, "", 1);// 688
			AddComplexComponent( (BaseAddon) this, 13851, -5, 2, 25, 1102, -1, "", 1);// 689
			AddComplexComponent( (BaseAddon) this, 13851, -5, 1, 25, 1102, -1, "", 1);// 690
			AddComplexComponent( (BaseAddon) this, 13851, -5, 0, 25, 1102, -1, "", 1);// 691
			AddComplexComponent( (BaseAddon) this, 13851, -5, -1, 25, 1102, -1, "", 1);// 692
			AddComplexComponent( (BaseAddon) this, 13851, -6, 3, 25, 1102, -1, "", 1);// 693
			AddComplexComponent( (BaseAddon) this, 13851, -6, 1, 25, 1102, -1, "", 1);// 694
			AddComplexComponent( (BaseAddon) this, 13851, -6, 0, 25, 1102, -1, "", 1);// 695
			AddComplexComponent( (BaseAddon) this, 13851, -6, -1, 25, 1102, -1, "", 1);// 696
			AddComplexComponent( (BaseAddon) this, 13851, 1, 3, 25, 1102, -1, "", 1);// 697
			AddComplexComponent( (BaseAddon) this, 13882, 1, -1, 5, 1102, -1, "", 1);// 698
			AddComplexComponent( (BaseAddon) this, 13885, -3, 3, 5, 1102, 0, "", 1);// 699
			AddComplexComponent( (BaseAddon) this, 13885, -6, 3, 5, 1102, 0, "", 1);// 700
			AddComplexComponent( (BaseAddon) this, 13884, 1, 2, 5, 1102, 0, "", 1);// 701
			AddComplexComponent( (BaseAddon) this, 4655, -5, 6, 2, 1762, -1, "", 1);// 702
			AddComplexComponent( (BaseAddon) this, 13883, 0, 3, 5, 1102, -1, "", 1);// 703
			AddComplexComponent( (BaseAddon) this, 13883, -5, 3, 5, 1102, -1, "", 1);// 704
			AddComplexComponent( (BaseAddon) this, 13846, 1, 3, 5, 1102, -1, "", 1);// 705
			AddComplexComponent( (BaseAddon) this, 13879, -3, 3, 2, 1102, -1, "", 1);// 706
			AddComplexComponent( (BaseAddon) this, 13879, -4, 3, 2, 1102, -1, "", 1);// 707
			AddComplexComponent( (BaseAddon) this, 13879, -5, 3, 2, 1102, -1, "", 1);// 708
			AddComplexComponent( (BaseAddon) this, 13879, -6, 3, 2, 1102, -1, "", 1);// 709
			AddComplexComponent( (BaseAddon) this, 13879, -2, 3, 2, 1102, -1, "", 1);// 710
			AddComplexComponent( (BaseAddon) this, 13879, -1, 3, 2, 1102, -1, "", 1);// 711
			AddComplexComponent( (BaseAddon) this, 13879, 0, 3, 2, 1102, -1, "", 1);// 712
			AddComplexComponent( (BaseAddon) this, 13878, 1, 2, 2, 1102, -1, "", 1);// 713
			AddComplexComponent( (BaseAddon) this, 13878, 1, 1, 2, 1102, -1, "", 1);// 714
			AddComplexComponent( (BaseAddon) this, 13878, 1, 0, 2, 1102, -1, "", 1);// 715
			AddComplexComponent( (BaseAddon) this, 13878, 1, -1, 2, 1102, -1, "", 1);// 716
			AddComplexComponent( (BaseAddon) this, 13844, 1, 3, 2, 1102, -1, "", 1);// 717
			AddComplexComponent( (BaseAddon) this, 13879, 3, -2, 5, 1102, -1, "", 1);// 718
			AddComplexComponent( (BaseAddon) this, 13842, -4, -3, 25, 1102, -1, "", 1);// 719
			AddComplexComponent( (BaseAddon) this, 13838, -6, -2, 25, 1102, -1, "", 1);// 720
			AddComplexComponent( (BaseAddon) this, 13846, -5, -2, 25, 1102, -1, "", 1);// 721
			AddComplexComponent( (BaseAddon) this, 13839, -5, -3, 25, 1102, -1, "", 1);// 722
			AddComplexComponent( (BaseAddon) this, 13878, 1, -2, 25, 1102, -1, "", 1);// 723
			AddComplexComponent( (BaseAddon) this, 13878, 1, -3, 25, 1102, -1, "", 1);// 724
			AddComplexComponent( (BaseAddon) this, 13851, 1, -2, 25, 1102, -1, "", 1);// 725
			AddComplexComponent( (BaseAddon) this, 13851, 1, -3, 25, 1102, -1, "", 1);// 726
			AddComplexComponent( (BaseAddon) this, 13851, 0, -2, 25, 1102, -1, "", 1);// 727
			AddComplexComponent( (BaseAddon) this, 13851, 0, -3, 25, 1102, -1, "", 1);// 728
			AddComplexComponent( (BaseAddon) this, 13851, -1, -2, 25, 1102, -1, "", 1);// 729
			AddComplexComponent( (BaseAddon) this, 13851, -1, -3, 25, 1102, -1, "", 1);// 730
			AddComplexComponent( (BaseAddon) this, 13851, -2, -2, 25, 1102, -1, "", 1);// 731
			AddComplexComponent( (BaseAddon) this, 13851, -2, -3, 25, 1102, -1, "", 1);// 732
			AddComplexComponent( (BaseAddon) this, 13851, -3, -2, 25, 1102, -1, "", 1);// 733
			AddComplexComponent( (BaseAddon) this, 13851, -3, -3, 25, 1102, -1, "", 1);// 734
			AddComplexComponent( (BaseAddon) this, 13851, -4, -2, 25, 1102, -1, "", 1);// 735
			AddComplexComponent( (BaseAddon) this, 13851, -4, -3, 25, 1102, -1, "", 1);// 736
			AddComplexComponent( (BaseAddon) this, 13851, -5, -2, 25, 1102, -1, "", 1);// 737
			AddComplexComponent( (BaseAddon) this, 13851, -5, -3, 25, 1102, -1, "", 1);// 738
			AddComplexComponent( (BaseAddon) this, 13851, -6, -2, 25, 1102, -1, "", 1);// 739
			AddComplexComponent( (BaseAddon) this, 13851, -6, -3, 25, 1102, -1, "", 1);// 740
			AddComplexComponent( (BaseAddon) this, 13884, 1, -2, 5, 1102, 0, "", 1);// 741
			AddComplexComponent( (BaseAddon) this, 13842, 2, -2, 10, 1102, -1, "", 1);// 742
			AddComplexComponent( (BaseAddon) this, 13879, 3, -2, 2, 1102, -1, "", 1);// 743
			AddComplexComponent( (BaseAddon) this, 13879, 2, -2, 2, 1102, -1, "", 1);// 744
			AddComplexComponent( (BaseAddon) this, 13851, 3, -2, 5, 1102, -1, "", 1);// 745
			AddComplexComponent( (BaseAddon) this, 13851, 3, -3, 5, 1102, -1, "", 1);// 746
			AddComplexComponent( (BaseAddon) this, 13851, 2, -2, 5, 1102, -1, "", 1);// 747
			AddComplexComponent( (BaseAddon) this, 13851, 2, -3, 5, 1102, -1, "", 1);// 748
			AddComplexComponent( (BaseAddon) this, 13878, 1, -2, 2, 1102, -1, "", 1);// 749
			AddComplexComponent( (BaseAddon) this, 18065, 5, 4, 2, 0, 0, "", 1);// 750
			AddComplexComponent( (BaseAddon) this, 3894, 4, -1, 2, 1762, -1, "", 1);// 751
			AddComplexComponent( (BaseAddon) this, 3892, 5, -1, 2, 1762, -1, "", 1);// 752
			AddComplexComponent( (BaseAddon) this, 3892, 5, 0, 1, 1762, -1, "", 1);// 753
			AddComplexComponent( (BaseAddon) this, 7373, -6, -1, 25, 1762, -1, "", 1);// 754
			AddComplexComponent( (BaseAddon) this, 3892, 5, -2, 7, 1762, -1, "", 1);// 755
			AddComplexComponent( (BaseAddon) this, 3274, 3, 6, 2, 2101, -1, "", 1);// 756
			AddComplexComponent( (BaseAddon) this, 13883, -1, 3, 5, 1102, -1, "", 1);// 757
			AddComplexComponent( (BaseAddon) this, 13883, -2, 3, 5, 1102, -1, "", 1);// 758
			AddComplexComponent( (BaseAddon) this, 6914, -3, 3, 25, 1807, -1, "", 1);// 759
			AddComplexComponent( (BaseAddon) this, 7677, -1, -1, 5, 794, -1, "", 1);// 760
			AddComplexComponent( (BaseAddon) this, 7379, -5, -1, 25, 1762, -1, "", 1);// 761
			AddComplexComponent( (BaseAddon) this, 13879, -6, 3, 25, 1102, -1, "", 1);// 762
			AddComplexComponent( (BaseAddon) this, 6918, -3, 1, 25, 1807, -1, "", 1);// 763
			AddComplexComponent( (BaseAddon) this, 3715, -5, 4, 2, 1109, -1, "", 1);// 764
			AddComplexComponent( (BaseAddon) this, 7678, -1, -2, 5, 1807, -1, "", 1);// 765
			AddComplexComponent( (BaseAddon) this, 3392, 6, -1, 2, 2102, -1, "", 1);// 766
			AddComplexComponent( (BaseAddon) this, 7070, 5, 5, 2, 2101, -1, "", 1);// 767
			AddComplexComponent( (BaseAddon) this, 6914, -6, 3, 25, 1807, -1, "", 1);// 768
			AddComplexComponent( (BaseAddon) this, 6920, -5, -1, 25, 1807, -1, "", 1);// 769
			AddComplexComponent( (BaseAddon) this, 6920, -1, -2, 25, 1807, -1, "", 1);// 770
			AddComplexComponent( (BaseAddon) this, 12323, 2, 1, 2, 2101, -1, "", 1);// 771
			AddComplexComponent( (BaseAddon) this, 7882, 1, -1, 27, 1102, -1, "", 1);// 772
			AddComplexComponent( (BaseAddon) this, 13851, -6, 2, 25, 1102, -1, "", 1);// 773
			AddComplexComponent( (BaseAddon) this, 6918, 0, -1, 25, 1807, -1, "", 1);// 774
			AddComplexComponent( (BaseAddon) this, 13879, -2, 3, 25, 1102, -1, "", 1);// 775
			AddComplexComponent( (BaseAddon) this, 7677, -1, -2, 5, 794, -1, "", 1);// 776
			AddComplexComponent( (BaseAddon) this, 7882, 1, 1, 28, 1102, -1, "", 1);// 777
			AddComplexComponent( (BaseAddon) this, 6973, 1, -3, 5, 794, -1, "", 1);// 778
			AddComplexComponent( (BaseAddon) this, 2205, -5, 5, 2, 1109, -1, "", 1);// 779
			AddComplexComponent( (BaseAddon) this, 2205, -5, 4, 13, 1109, -1, "", 1);// 780
			AddComplexComponent( (BaseAddon) this, 6919, -3, -3, 25, 1807, -1, "", 1);// 781
			AddComplexComponent( (BaseAddon) this, 13001, 0, 10, 2, 1, -1, "", 1);// 782
			AddComplexComponent( (BaseAddon) this, 6019, -2, 10, 2, 1807, -1, "", 1);// 783
			AddComplexComponent( (BaseAddon) this, 7678, 2, 10, 2, 1807, -1, "", 1);// 784
			AddComplexComponent( (BaseAddon) this, 6019, -2, 9, 2, 1807, -1, "", 1);// 785
			AddComplexComponent( (BaseAddon) this, 6954, 0, 10, 3, 1807, -1, "", 1);// 786
			AddComplexComponent( (BaseAddon) this, 6957, -1, 10, 3, 1807, -1, "", 1);// 787
			AddComplexComponent( (BaseAddon) this, 1305, 7, 9, 2, 951, -1, "", 1);// 788
			AddComplexComponent( (BaseAddon) this, 1305, 7, 8, 2, 951, -1, "", 1);// 789
			AddComplexComponent( (BaseAddon) this, 1305, 6, 9, 2, 951, -1, "", 1);// 790
			AddComplexComponent( (BaseAddon) this, 1305, 6, 8, 2, 951, -1, "", 1);// 791
			AddComplexComponent( (BaseAddon) this, 6952, 1, 10, 3, 1807, -1, "", 1);// 792
			AddComplexComponent( (BaseAddon) this, 4127, -2, 10, 2, 1807, -1, "", 1);// 793
			AddComplexComponent( (BaseAddon) this, 6951, 0, 9, 3, 1807, -1, "", 1);// 794
			AddComplexComponent( (BaseAddon) this, 6951, -1, 9, 3, 1807, -1, "", 1);// 795
			AddComplexComponent( (BaseAddon) this, 7679, 2, 10, 2, 1807, -1, "", 1);// 796
			AddComplexComponent( (BaseAddon) this, 7679, 1, 11, 2, 1807, -1, "", 1);// 797
			AddComplexComponent( (BaseAddon) this, 7679, 1, 9, 2, 1807, -1, "", 1);// 798
			AddComplexComponent( (BaseAddon) this, 13001, -1, 9, 2, 1762, -1, "", 1);// 799
			AddComplexComponent( (BaseAddon) this, 6951, 0, 11, 3, 1807, -1, "", 1);// 800
			AddComplexComponent( (BaseAddon) this, 6018, 0, 8, 2, 1807, -1, "", 1);// 801
			AddComplexComponent( (BaseAddon) this, 13001, -1, 10, 2, 1, -1, "", 1);// 802
			AddComplexComponent( (BaseAddon) this, 7679, 1, 10, 2, 1807, -1, "", 1);// 803
			AddComplexComponent( (BaseAddon) this, 7679, 1, 9, 2, 1807, -1, "", 1);// 804
			AddComplexComponent( (BaseAddon) this, 6952, -1, 9, 3, 1807, -1, "", 1);// 805
			AddComplexComponent( (BaseAddon) this, 6951, -1, 11, 3, 1807, -1, "", 1);// 806
			AddComplexComponent( (BaseAddon) this, 6952, 1, 9, 3, 1807, -1, "", 1);// 807
			AddComplexComponent( (BaseAddon) this, 13001, 0, 9, 2, 1762, -1, "", 1);// 808
			AddComplexComponent( (BaseAddon) this, 6959, 1, 11, 3, 1807, -1, "", 1);// 809
			AddComplexComponent( (BaseAddon) this, 6018, -1, 8, 2, 1807, -1, "", 1);// 810
			AddComplexComponent( (BaseAddon) this, 3392, 6, 9, 2, 2102, -1, "", 1);// 811
			AddComplexComponent( (BaseAddon) this, 7679, 1, 9, 2, 1807, -1, "", 1);// 812
			AddComplexComponent( (BaseAddon) this, 1305, 8, 7, 2, 951, -1, "", 1);// 813
			AddComplexComponent( (BaseAddon) this, 1305, 8, 6, 2, 951, -1, "", 1);// 814
			AddComplexComponent( (BaseAddon) this, 1305, 8, 5, 3, 951, -1, "", 1);// 815
			AddComplexComponent( (BaseAddon) this, 1305, 8, 4, 2, 951, -1, "", 1);// 816
			AddComplexComponent( (BaseAddon) this, 1305, 8, 3, 2, 951, -1, "", 1);// 817
			AddComplexComponent( (BaseAddon) this, 1305, 8, 1, 2, 951, -1, "", 1);// 818
			AddComplexComponent( (BaseAddon) this, 1305, 8, 0, 2, 951, -1, "", 1);// 819
			AddComplexComponent( (BaseAddon) this, 1305, 8, -1, 3, 951, -1, "", 1);// 820
			AddComplexComponent( (BaseAddon) this, 6913, 8, -1, 3, 951, -1, "", 1);// 821
			AddComplexComponent( (BaseAddon) this, 1305, 8, -2, 2, 951, -1, "", 1);// 822
			AddComplexComponent( (BaseAddon) this, 3392, 9, 0, 2, 2102, -1, "", 1);// 823
			AddComplexComponent( (BaseAddon) this, 7070, 9, 5, 2, 2101, -1, "", 1);// 824
			AddComplexComponent( (BaseAddon) this, 1305, 8, 8, 2, 951, -1, "", 1);// 825
			AddComplexComponent( (BaseAddon) this, 3275, 10, 5, 2, 2101, -1, "", 1);// 827
			AddComplexComponent( (BaseAddon) this, 3391, 10, 6, 2, 2102, -1, "", 1);// 828
		}

		public HauntedHouseBlankAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class HauntedHouseBlankAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new HauntedHouseBlankAddon();
			}
		}

		[Constructable]
		public HauntedHouseBlankAddonDeed()
		{
			Name = "Haunted House Blank";
		}

		public HauntedHouseBlankAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}