////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class HauntedBonesnBloodAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {5701, -3, -1, 0}, {6921, 1, 1, 0}, {3786, 3, 0, 0}// 1	2	3	
			, {6922, 2, -1, 0}, {6926, -1, 0, 0}// 4	5	
		};

		public override BaseAddonDeed Deed
		{
			get
			{
				return new HauntedBonesnBloodAddonDeed();
			}
		}

		[ Constructable ]
		public HauntedBonesnBloodAddon()
		{
            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );
		}

		public HauntedBonesnBloodAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class HauntedBonesnBloodAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new HauntedBonesnBloodAddon();
			}
		}

		[Constructable]
		public HauntedBonesnBloodAddonDeed()
		{
			Name = "Haunted Bones and Blood";
		}

		public HauntedBonesnBloodAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}