/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SmallCityParkAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				//return new SmallCityParkAddonDeed();
				return null;
			}
		}

		[ Constructable ]
		public SmallCityParkAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 99 );
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 3255 );
			AddComponent( ac, -1, 0, 7 );
			ac = new AddonComponent( 6017 ); //NEW
			AddComponent( ac, 1, 0, 7 );
			ac = new AddonComponent( 6053 );
			AddComponent( ac, 1, 0, 7 );
			ac = new AddonComponent( 6050 );
			AddComponent( ac, 0, 2, 7 );
			ac = new AddonComponent( 6017 );//NEW
			AddComponent( ac, 0, 0, 7 );
			ac = new AddonComponent( 6048 );
			AddComponent( ac, 0, 0, 7 );
			ac = new AddonComponent( 6015 );
			AddComponent( ac, 4, 4, 7 );
			ac = new AddonComponent( 6017 );
			AddComponent( ac, 4, 3, 7 );
			ac = new AddonComponent( 6017 );
			AddComponent( ac, 4, 1, 7 );
			ac = new AddonComponent( 6016 );
			AddComponent( ac, 4, 0, 7 );
			ac = new AddonComponent( 6017 );
			AddComponent( ac, 4, -1, 7 );
			ac = new AddonComponent( 6015 );
			AddComponent( ac, 4, -3, 7 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 3, 4, 7 );
			ac = new AddonComponent( 6014 );
			AddComponent( ac, 3, 3, 7 );
			ac = new AddonComponent( 6017 );
			AddComponent( ac, 3, 2, 7 );
			ac = new AddonComponent( 6015 );
			AddComponent( ac, 3, 0, 7 );
			ac = new AddonComponent( 6014 );
			AddComponent( ac, 3, -1, 7 );
			ac = new AddonComponent( 6014 );
			AddComponent( ac, 2, 4, 7 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 2, 3, 7 );
			ac = new AddonComponent( 6014 );
			AddComponent( ac, 2, 2, 7 );
			ac = new AddonComponent( 6016 );
			AddComponent( ac, 2, 1, 7 );
			ac = new AddonComponent( 6017 );
			AddComponent( ac, 2, 0, 7 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 2, -3, 7 );
			ac = new AddonComponent( 6015 );
			AddComponent( ac, 1, 4, 7 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 1, 2, 7 );
			ac = new AddonComponent( 6016 );
			AddComponent( ac, 1, 1, 7 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 1, -1, 7 );
			ac = new AddonComponent( 6017 );
			AddComponent( ac, 0, 3, 7 );
			ac = new AddonComponent( 6015 );
			AddComponent( ac, 0, 2, 7 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 0, -1, 7 );
			ac = new AddonComponent( 6015 );
			AddComponent( ac, 0, -2, 7 );
			ac = new AddonComponent( 6016 );
			AddComponent( ac, -1, 3, 7 );
			ac = new AddonComponent( 6014 );
			AddComponent( ac, -1, 1, 7 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -1, 0, 7 );
			ac = new AddonComponent( 6017 );
			AddComponent( ac, -1, -1, 7 );
			ac = new AddonComponent( 6015 );
			AddComponent( ac, -1, -2, 7 );
			ac = new AddonComponent( 6015 );
			AddComponent( ac, -1, -3, 7 );
			ac = new AddonComponent( 6017 );
			AddComponent( ac, -2, 4, 7 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -2, 3, 7 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -2, 2, 7 );
			ac = new AddonComponent( 6014 );
			AddComponent( ac, -2, 1, 7 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -2, -1, 7 );
			ac = new AddonComponent( 6017 );
			AddComponent( ac, -2, -3, 7 );
			ac = new AddonComponent( 6014 );
			AddComponent( ac, -3, 4, 7 );
			ac = new AddonComponent( 6014 );
			AddComponent( ac, -3, 3, 7 );
			ac = new AddonComponent( 6017 );
			AddComponent( ac, -3, 2, 7 );
			ac = new AddonComponent( 6015 );
			AddComponent( ac, -3, 0, 7 );
			ac = new AddonComponent( 6016 );
			AddComponent( ac, -3, -1, 7 );
			ac = new AddonComponent( 6014 );
			AddComponent( ac, -3, -2, 7 );
			ac = new AddonComponent( 6015 );
			AddComponent( ac, -3, -3, 7 );
			ac = new AddonComponent( 101 );
			AddComponent( ac, 4, 4, 0 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, 4, -3, 0 );
			ac = new AddonComponent( 1873 );
			AddComponent( ac, 3, 5, 0 );
			ac = new AddonComponent( 1873 );
			AddComponent( ac, 1, 5, 0 );
			ac = new AddonComponent( 1873 );
			AddComponent( ac, 0, 5, 0 );
			ac = new AddonComponent( 1873 );
			AddComponent( ac, -2, 5, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, -3, 4, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, 3, -4, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, 2, -4, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, 1, -4, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, 0, -4, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, -1, -4, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, -2, -4, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, -3, -4, 0 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, -4, 4, 0 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, -4, 3, 0 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, -4, 1, 0 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, -4, 0, 0 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, -4, -1, 0 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, -4, -2, 0 );
			ac = new AddonComponent( 102 );
			AddComponent( ac, -4, -4, 0 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, 3, 0, 7 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, 1, -2, 7 );
			ac = new AddonComponent( 3206 );
			AddComponent( ac, 0, -2, 7 );
			ac = new AddonComponent( 3265 );
			AddComponent( ac, 3, -1, 7 );
			ac = new AddonComponent( 3265 );
			AddComponent( ac, -2, 0, 7 );
			ac = new AddonComponent( 6811 );
			AddComponent( ac, 3, 2, 7 );
			ac = new AddonComponent( 6811 );
			AddComponent( ac, -1, -2, 7 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 2, -1, 7 );
			ac = new AddonComponent( 3220 );
			AddComponent( ac, 3, 3, 7 );
			ac = new AddonComponent( 3220 );
			AddComponent( ac, -2, -2, 7 );
			ac = new AddonComponent( 9331 );
			AddComponent( ac, 3, -2, 7 );
			ac = new AddonComponent( 9969 );
			AddComponent( ac, -2, 3, 7 );
			ac = new AddonComponent( 9965 );
			ac.Hue = 1150;
			AddComponent( ac, -2, 3, 7 );
			ac = new AddonComponent( 2922 );
			ac.Hue = 1150;
			AddComponent( ac, 0, -1, 7 );
			ac = new AddonComponent( 2921 );
			ac.Hue = 1150;
			AddComponent( ac, -1, -1, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, -1, 4, 19 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, -1, 4, 13 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, 2, 4, 13 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, 2, 4, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, -2, 4, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, 4, 4, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, 4, 3, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, 4, 2, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, 4, 1, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, 4, 0, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, 4, -1, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, 4, -2, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, -3, 4, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, -3, 3, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, -3, 2, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, -3, 1, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, -3, 0, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, -3, -1, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, -3, -2, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, 4, -3, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, 3, -3, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, 2, -3, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, 1, -3, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, 0, -3, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, -1, -3, 7 );
			ac = new AddonComponent( 3256 );
			AddComponent( ac, 1, 1, 7 );
			ac = new AddonComponent( 6055 );
			AddComponent( ac, 1, 2, 7 );
			ac = new AddonComponent( 2852 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, -3, -3, 7 );
			ac = new AddonComponent( 6015 );
			AddComponent( ac, 4, 2, 7 );
			ac = new AddonComponent( 6016 );
			AddComponent( ac, 3, 1, 7 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 3, -2, 7 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 3, -3, 7 );
			ac = new AddonComponent( 6015 );
			AddComponent( ac, 2, -1, 7 );
			ac = new AddonComponent( 6017 );
			AddComponent( ac, 2, -2, 7 );
			ac = new AddonComponent( 6014 );
			AddComponent( ac, 1, 3, 7 );
			ac = new AddonComponent( 6017 );
			AddComponent( ac, 1, -2, 7 );
			ac = new AddonComponent( 6015 );
			AddComponent( ac, 1, -3, 7 );
			ac = new AddonComponent( 6015 );
			AddComponent( ac, 0, 4, 7 );
			ac = new AddonComponent( 6015 );
			AddComponent( ac, 0, 1, 7 );
			ac = new AddonComponent( 6016 );
			AddComponent( ac, 0, -3, 7 );
			ac = new AddonComponent( 6016 );
			AddComponent( ac, -1, 4, 7 );
			ac = new AddonComponent( 6014 );
			AddComponent( ac, -1, 2, 7 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -2, 0, 7 );
			ac = new AddonComponent( 6017 );
			AddComponent( ac, -2, -2, 7 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -3, 1, 7 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, 4, -2, 0 );
			ac = new AddonComponent( 1873 );
			AddComponent( ac, 2, 5, 0 );
			ac = new AddonComponent( 1873 );
			AddComponent( ac, -1, 5, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 99 );
			AddComponent( ac, 4, -4, 0 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, -4, 2, 0 );
			ac = new AddonComponent( 100 );
			AddComponent( ac, -4, -3, 0 );
			ac = new AddonComponent( 3206 );
			AddComponent( ac, 3, 1, 7 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, -2, -1, 7 );
			ac = new AddonComponent( 3220 );
			AddComponent( ac, 3, -2, 7 );
			ac = new AddonComponent( 9334 );
			AddComponent( ac, 3, -2, 7 );
			ac = new AddonComponent( 2920 );
			ac.Hue = 1150;
			AddComponent( ac, 1, -1, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, 1, 4, 30 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, 0, 4, 29 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, -1, 4, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, 3, 4, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, -2, -3, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, -3, -3, 7 );
			ac = new AddonComponent( 6017 );
			AddComponent( ac, 4, -2, 7 );
			ac = new AddonComponent( 3241 );
			AddComponent( ac, 2, -2, 7 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, 2, 4, 25 );
			ac = new AddonComponent( 3215 );
			AddComponent( ac, 2, 4, 19 );
			ac = new AddonComponent( 6042 );
			AddComponent( ac, 0, 1, 7 );
			ac = new AddonComponent( 6056 );
			AddComponent( ac, -1, 2, 7 );
			ac = new AddonComponent( 6054 );
			AddComponent( ac, -1, 0, 7 );
			ac = new AddonComponent( 6051 );
			AddComponent( ac, -1, 1, 7 );
			ac = new AddonComponent( 6045 );
			AddComponent( ac, 1, 1, 7 );
			ac = new AddonComponent( 2852 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 2, 4, 11 );
			ac = new AddonComponent( 2852 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, -1, 4, 5 );
			ac = new AddonComponent( 2852 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 3, 3, 7 );
			ac = new AddonComponent( 1882 );
			AddComponent( ac, 4, 5, 0 );
			ac = new AddonComponent( 1883 );
			AddComponent( ac, -3, 5, 0 );
			ac = new AddonComponent( 9 );
			AddComponent( ac, -4, 4, 7 );
			ac = new AddonComponent( 2968 );
			AddComponent( ac, -4, 5, 7 );

		}

		public SmallCityParkAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}


}
