/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class WoodCityMarketAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return null;
			}
		}

		[ Constructable ]
		public WoodCityMarketAddon()
		{
			AddComponent( new AddonComponent( 10625 ), -2, 2, 7 );
			AddComponent( new AddonComponent( 1403 ), -2, 2, 27 );
			AddComponent( new AddonComponent( 11328 ), -2, 2, 50 );
			AddComponent( new AddonComponent( 10625 ), -2, -1, 7 );
			AddComponent( new AddonComponent( 1403 ), -2, -1, 27 );
			AddComponent( new AddonComponent( 11329 ), -2, -1, 53 );
			AddComponent( new AddonComponent( 10619 ), 2, 4, 7 );
			AddComponent( new AddonComponent( 1403 ), 2, 4, 27 );
			AddComponent( new AddonComponent( 22 ), 2, 4, 27 );
			AddComponent( new AddonComponent( 11328 ), 2, 4, 44 );
			AddComponent( new AddonComponent( 22 ), 2, 4, 0 );
			AddComponent( new AddonComponent( 10627 ), 3, 0, 7 );
			AddComponent( new AddonComponent( 1403 ), 3, 0, 27 );
			AddComponent( new AddonComponent( 11327 ), 3, 0, 56 );
			AddComponent( new AddonComponent( 10619 ), 3, -1, 7 );
			AddComponent( new AddonComponent( 1403 ), 3, -1, 27 );
			AddComponent( new AddonComponent( 11329 ), 3, -1, 53 );
			AddComponent( new AddonComponent( 10625 ), 3, 2, 7 );
			AddComponent( new AddonComponent( 1404 ), 3, 2, 27 );
			AddComponent( new AddonComponent( 11328 ), 3, 2, 50 );
			AddComponent( new AddonComponent( 10627 ), 3, 1, 7 );
			AddComponent( new AddonComponent( 1403 ), 3, 1, 27 );
			AddComponent( new AddonComponent( 11328 ), 3, 1, 53 );
			AddComponent( new AddonComponent( 10619 ), 5, 2, 7 );
			AddComponent( new AddonComponent( 1403 ), 5, 2, 27 );
			AddComponent( new AddonComponent( 21 ), 5, 2, 27 );
			AddComponent( new AddonComponent( 11328 ), 5, 2, 50 );
			AddComponent( new AddonComponent( 21 ), 5, 2, 0 );
			AddComponent( new AddonComponent( 10619 ), 5, 1, 7 );
			AddComponent( new AddonComponent( 1403 ), 5, 1, 27 );
			AddComponent( new AddonComponent( 21 ), 5, 1, 27 );
			AddComponent( new AddonComponent( 11328 ), 5, 1, 53 );
			AddComponent( new AddonComponent( 21 ), 5, 1, 0 );
			AddComponent( new AddonComponent( 10619 ), 5, 0, 7 );
			AddComponent( new AddonComponent( 1403 ), 5, 0, 27 );
			AddComponent( new AddonComponent( 21 ), 5, 0, 27 );
			AddComponent( new AddonComponent( 11327 ), 5, 0, 56 );
			AddComponent( new AddonComponent( 21 ), 5, 0, 0 );
			AddComponent( new AddonComponent( 1854 ), 5, 5, 0 );
			AddComponent( new AddonComponent( 10619 ), 5, 4, 7 );
			AddComponent( new AddonComponent( 6 ), 5, 4, 7 );
			AddComponent( new AddonComponent( 1403 ), 5, 4, 27 );
			AddComponent( new AddonComponent( 20 ), 5, 4, 27 );
			AddComponent( new AddonComponent( 11328 ), 5, 4, 44 );
			AddComponent( new AddonComponent( 20 ), 5, 4, 0 );
			AddComponent( new AddonComponent( 10619 ), 5, 3, 7 );
			AddComponent( new AddonComponent( 9 ), 5, 3, 7 );
			AddComponent( new AddonComponent( 1403 ), 5, 3, 27 );
			AddComponent( new AddonComponent( 21 ), 5, 3, 27 );
			AddComponent( new AddonComponent( 11328 ), 5, 3, 47 );
			AddComponent( new AddonComponent( 21 ), 5, 3, 0 );
			AddComponent( new AddonComponent( 1 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 10619 ), 0, -1, 7 );
			AddComponent( new AddonComponent( 1403 ), 0, -1, 27 );
			AddComponent( new AddonComponent( 11329 ), 0, -1, 53 );
			AddComponent( new AddonComponent( 5139 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 10619 ), -3, 1, 7 );
			AddComponent( new AddonComponent( 1403 ), -3, 1, 27 );
			AddComponent( new AddonComponent( 11328 ), -3, 1, 53 );
			AddComponent( new AddonComponent( 10619 ), -3, 0, 7 );
			AddComponent( new AddonComponent( 1403 ), -3, 0, 27 );
			AddComponent( new AddonComponent( 11327 ), -3, 0, 56 );
			AddComponent( new AddonComponent( 10619 ), -3, -1, 7 );
			AddComponent( new AddonComponent( 1403 ), -3, -1, 27 );
			AddComponent( new AddonComponent( 11329 ), -3, -1, 53 );
			AddComponent( new AddonComponent( 10627 ), 5, -2, 7 );
			AddComponent( new AddonComponent( 1403 ), 5, -2, 27 );
			AddComponent( new AddonComponent( 21 ), 5, -2, 27 );
			AddComponent( new AddonComponent( 11329 ), 5, -2, 50 );
			AddComponent( new AddonComponent( 21 ), 5, -2, 0 );
			AddComponent( new AddonComponent( 10619 ), 5, -3, 7 );
			AddComponent( new AddonComponent( 1403 ), 5, -3, 27 );
			AddComponent( new AddonComponent( 21 ), 5, -3, 27 );
			AddComponent( new AddonComponent( 11329 ), 5, -3, 47 );
			AddComponent( new AddonComponent( 21 ), 5, -3, 0 );
			AddComponent( new AddonComponent( 10619 ), 5, -4, 7 );
			AddComponent( new AddonComponent( 13 ), 5, -4, 7 );
			AddComponent( new AddonComponent( 1403 ), 5, -4, 27 );
			AddComponent( new AddonComponent( 21 ), 5, -4, 27 );
			AddComponent( new AddonComponent( 11329 ), 5, -4, 44 );
			AddComponent( new AddonComponent( 21 ), 5, -4, 0 );
			AddComponent( new AddonComponent( 12 ), 5, -5, 7 );
			AddComponent( new AddonComponent( 22 ), 5, -5, 27 );
			AddComponent( new AddonComponent( 22 ), 5, -5, 0 );
			AddComponent( new AddonComponent( 10619 ), 4, 3, 7 );
			AddComponent( new AddonComponent( 1403 ), 4, 3, 27 );
			AddComponent( new AddonComponent( 9 ), 4, 3, 27 );
			AddComponent( new AddonComponent( 11328 ), 4, 3, 47 );
			AddComponent( new AddonComponent( 10619 ), 4, 4, 7 );
			AddComponent( new AddonComponent( 9 ), 4, 4, 7 );
			AddComponent( new AddonComponent( 1403 ), 4, 4, 27 );
			AddComponent( new AddonComponent( 22 ), 4, 4, 27 );
			AddComponent( new AddonComponent( 11328 ), 4, 4, 44 );
			AddComponent( new AddonComponent( 22 ), 4, 4, 0 );
			AddComponent( new AddonComponent( 1849 ), 4, 5, 0 );
			AddComponent( new AddonComponent( 1849 ), 3, 5, 0 );
			AddComponent( new AddonComponent( 10619 ), -1, 4, 7 );
			AddComponent( new AddonComponent( 1403 ), -1, 4, 27 );
			AddComponent( new AddonComponent( 22 ), -1, 4, 27 );
			AddComponent( new AddonComponent( 11328 ), -1, 4, 44 );
			AddComponent( new AddonComponent( 22 ), -1, 4, 0 );
			AddComponent( new AddonComponent( 10619 ), 0, 4, 7 );
			AddComponent( new AddonComponent( 1403 ), 0, 4, 27 );
			AddComponent( new AddonComponent( 22 ), 0, 4, 27 );
			AddComponent( new AddonComponent( 11328 ), 0, 4, 44 );
			AddComponent( new AddonComponent( 22 ), 0, 4, 0 );
			AddComponent( new AddonComponent( 10619 ), 1, 0, 7 );
			AddComponent( new AddonComponent( 1403 ), 1, 0, 27 );
			AddComponent( new AddonComponent( 11327 ), 1, 0, 56 );
			AddComponent( new AddonComponent( 1849 ), -1, 5, 0 );
			AddComponent( new AddonComponent( 10619 ), 1, -2, 7 );
			AddComponent( new AddonComponent( 1403 ), 1, -2, 27 );
			AddComponent( new AddonComponent( 11329 ), 1, -2, 50 );
			AddComponent( new AddonComponent( 10625 ), 1, -3, 7 );
			AddComponent( new AddonComponent( 1403 ), 1, -3, 27 );
			AddComponent( new AddonComponent( 11329 ), 1, -3, 47 );
			AddComponent( new AddonComponent( 10627 ), 1, -4, 7 );
			AddComponent( new AddonComponent( 1403 ), 1, -4, 27 );
			AddComponent( new AddonComponent( 11329 ), 1, -4, 44 );
			AddComponent( new AddonComponent( 22 ), 1, -5, 27 );
			AddComponent( new AddonComponent( 22 ), 1, -5, 0 );
			AddComponent( new AddonComponent( 22 ), 0, -5, 27 );
			AddComponent( new AddonComponent( 22 ), 0, -5, 0 );
			AddComponent( new AddonComponent( 10619 ), 0, -4, 7 );
			AddComponent( new AddonComponent( 1403 ), 0, -4, 27 );
			AddComponent( new AddonComponent( 11329 ), 0, -4, 44 );
			AddComponent( new AddonComponent( 10619 ), 0, -3, 7 );
			AddComponent( new AddonComponent( 1403 ), 0, -3, 27 );
			AddComponent( new AddonComponent( 11329 ), 0, -3, 47 );
			AddComponent( new AddonComponent( 10619 ), -2, -4, 7 );
			AddComponent( new AddonComponent( 1403 ), -2, -4, 27 );
			AddComponent( new AddonComponent( 11329 ), -2, -4, 44 );
			AddComponent( new AddonComponent( 1849 ), 2, 5, 0 );
			AddComponent( new AddonComponent( 10625 ), -1, -1, 7 );
			AddComponent( new AddonComponent( 1404 ), -1, -1, 27 );
			AddComponent( new AddonComponent( 11329 ), -1, -1, 53 );
			AddComponent( new AddonComponent( 10619 ), 0, 1, 7 );
			AddComponent( new AddonComponent( 1403 ), 0, 1, 27 );
			AddComponent( new AddonComponent( 11328 ), 0, 1, 53 );
			AddComponent( new AddonComponent( 10627 ), -1, 1, 7 );
			AddComponent( new AddonComponent( 1404 ), -1, 1, 27 );
			AddComponent( new AddonComponent( 11328 ), -1, 1, 53 );
			AddComponent( new AddonComponent( 10627 ), 1, 2, 7 );
			AddComponent( new AddonComponent( 1404 ), 1, 2, 27 );
			AddComponent( new AddonComponent( 11328 ), 1, 2, 50 );
			AddComponent( new AddonComponent( 10627 ), 2, 2, 7 );
			AddComponent( new AddonComponent( 1403 ), 2, 2, 27 );
			AddComponent( new AddonComponent( 11328 ), 2, 2, 50 );
			AddComponent( new AddonComponent( 10619 ), -3, 4, 7 );
			AddComponent( new AddonComponent( 12 ), -3, 4, 7 );
			AddComponent( new AddonComponent( 1403 ), -3, 4, 27 );
			AddComponent( new AddonComponent( 22 ), -3, 4, 27 );
			AddComponent( new AddonComponent( 11328 ), -3, 4, 44 );
			AddComponent( new AddonComponent( 22 ), -3, 4, 0 );
			AddComponent( new AddonComponent( 10625 ), 2, 0, 7 );
			AddComponent( new AddonComponent( 1403 ), 2, 0, 27 );
			AddComponent( new AddonComponent( 11327 ), 2, 0, 56 );
			AddComponent( new AddonComponent( 9 ), -4, 3, 7 );
			AddComponent( new AddonComponent( 21 ), -4, 3, 27 );
			AddComponent( new AddonComponent( 21 ), -4, 3, 0 );
			AddComponent( new AddonComponent( 13 ), -4, 4, 7 );
			AddComponent( new AddonComponent( 21 ), -4, 4, 27 );
			AddComponent( new AddonComponent( 21 ), -4, 4, 0 );
			//AddComponent( new AddonComponent( 3026 ), -4, 5, 7 );
			AddComponent( new AddonComponent( 2968 ), -4, 5, 7 );
			AddComponent( new AddonComponent( 10625 ), 3, -3, 7 );
			AddComponent( new AddonComponent( 1403 ), 3, -3, 27 );
			AddComponent( new AddonComponent( 11329 ), 3, -3, 47 );
			AddComponent( new AddonComponent( 10619 ), -3, -2, 7 );
			AddComponent( new AddonComponent( 1403 ), -3, -2, 27 );
			AddComponent( new AddonComponent( 11329 ), -3, -2, 50 );
			AddComponent( new AddonComponent( 10619 ), -3, -3, 7 );
			AddComponent( new AddonComponent( 1403 ), -3, -3, 27 );
			AddComponent( new AddonComponent( 11329 ), -3, -3, 47 );
			AddComponent( new AddonComponent( 10619 ), -3, -4, 7 );
			AddComponent( new AddonComponent( 1403 ), -3, -4, 27 );
			AddComponent( new AddonComponent( 9 ), -3, -4, 27 );
			AddComponent( new AddonComponent( 11329 ), -3, -4, 44 );
			AddComponent( new AddonComponent( 21 ), -4, 2, 27 );
			AddComponent( new AddonComponent( 21 ), -4, 2, 0 );
			AddComponent( new AddonComponent( 9 ), -4, -5, 7 );
			AddComponent( new AddonComponent( 23 ), -4, -5, 27 );
			AddComponent( new AddonComponent( 23 ), -4, -5, 0 );
			AddComponent( new AddonComponent( 1849 ), 1, 5, 0 );
			AddComponent( new AddonComponent( 10619 ), 2, 3, 7 );
			AddComponent( new AddonComponent( 1403 ), 2, 3, 27 );
			AddComponent( new AddonComponent( 11328 ), 2, 3, 47 );
			AddComponent( new AddonComponent( 10627 ), 1, 3, 7 );
			AddComponent( new AddonComponent( 1404 ), 1, 3, 27 );
			AddComponent( new AddonComponent( 11328 ), 1, 3, 47 );
			AddComponent( new AddonComponent( 1849 ), -2, 5, 0 );
			AddComponent( new AddonComponent( 10619 ), -1, 3, 7 );
			AddComponent( new AddonComponent( 1404 ), -1, 3, 27 );
			AddComponent( new AddonComponent( 11328 ), -1, 3, 47 );
			AddComponent( new AddonComponent( 1849 ), 0, 5, 0 );
			AddComponent( new AddonComponent( 10619 ), -2, 4, 7 );
			AddComponent( new AddonComponent( 1403 ), -2, 4, 27 );
			AddComponent( new AddonComponent( 22 ), -2, 4, 27 );
			AddComponent( new AddonComponent( 11328 ), -2, 4, 44 );
			AddComponent( new AddonComponent( 22 ), -2, 4, 0 );
			AddComponent( new AddonComponent( 9 ), 4, -5, 7 );
			AddComponent( new AddonComponent( 22 ), 4, -5, 27 );
			AddComponent( new AddonComponent( 22 ), 4, -5, 0 );
			AddComponent( new AddonComponent( 10619 ), 4, -4, 7 );
			AddComponent( new AddonComponent( 1403 ), 4, -4, 27 );
			AddComponent( new AddonComponent( 9 ), 4, -4, 27 );
			AddComponent( new AddonComponent( 11329 ), 4, -4, 44 );
			AddComponent( new AddonComponent( 10625 ), 4, -3, 7 );
			AddComponent( new AddonComponent( 1403 ), 4, -3, 27 );
			AddComponent( new AddonComponent( 11329 ), 4, -3, 47 );
			AddComponent( new AddonComponent( 10627 ), 5, -1, 7 );
			AddComponent( new AddonComponent( 1403 ), 5, -1, 27 );
			AddComponent( new AddonComponent( 21 ), 5, -1, 27 );
			AddComponent( new AddonComponent( 11329 ), 5, -1, 53 );
			AddComponent( new AddonComponent( 21 ), 5, -1, 0 );
			AddComponent( new AddonComponent( 10619 ), -1, -4, 7 );
			AddComponent( new AddonComponent( 1404 ), -1, -4, 27 );
			AddComponent( new AddonComponent( 11329 ), -1, -4, 44 );
			AddComponent( new AddonComponent( 22 ), -1, -5, 27 );
			AddComponent( new AddonComponent( 22 ), -1, -5, 0 );
			AddComponent( new AddonComponent( 10619 ), -1, -2, 7 );
			AddComponent( new AddonComponent( 1403 ), -1, -2, 27 );
			AddComponent( new AddonComponent( 11329 ), -1, -2, 50 );
			AddComponent( new AddonComponent( 10627 ), 0, -2, 7 );
			AddComponent( new AddonComponent( 1403 ), 0, -2, 27 );
			AddComponent( new AddonComponent( 11329 ), 0, -2, 50 );
			AddComponent( new AddonComponent( 10619 ), -1, 0, 7 );
			AddComponent( new AddonComponent( 1403 ), -1, 0, 27 );
			AddComponent( new AddonComponent( 11327 ), -1, 0, 56 );
			AddComponent( new AddonComponent( 13 ), -4, -4, 7 );
			AddComponent( new AddonComponent( 21 ), -4, -4, 27 );
			AddComponent( new AddonComponent( 21 ), -4, -4, 0 );
			AddComponent( new AddonComponent( 21 ), -4, -3, 27 );
			AddComponent( new AddonComponent( 21 ), -4, -3, 0 );
			AddComponent( new AddonComponent( 10619 ), -2, 0, 7 );
			AddComponent( new AddonComponent( 1403 ), -2, 0, 27 );
			AddComponent( new AddonComponent( 11327 ), -2, 0, 56 );
			AddComponent( new AddonComponent( 10619 ), 4, -1, 7 );
			AddComponent( new AddonComponent( 1403 ), 4, -1, 27 );
			AddComponent( new AddonComponent( 11329 ), 4, -1, 53 );
			AddComponent( new AddonComponent( 10625 ), 4, 0, 7 );
			AddComponent( new AddonComponent( 1403 ), 4, 0, 27 );
			AddComponent( new AddonComponent( 11327 ), 4, 0, 56 );
			AddComponent( new AddonComponent( 10627 ), 4, 1, 7 );
			AddComponent( new AddonComponent( 1403 ), 4, 1, 27 );
			AddComponent( new AddonComponent( 11328 ), 4, 1, 53 );
			AddComponent( new AddonComponent( 10627 ), 4, 2, 7 );
			AddComponent( new AddonComponent( 1404 ), 4, 2, 27 );
			AddComponent( new AddonComponent( 11328 ), 4, 2, 50 );
			AddComponent( new AddonComponent( 10619 ), 3, 4, 7 );
			AddComponent( new AddonComponent( 1404 ), 3, 4, 27 );
			AddComponent( new AddonComponent( 22 ), 3, 4, 27 );
			AddComponent( new AddonComponent( 11328 ), 3, 4, 44 );
			AddComponent( new AddonComponent( 22 ), 3, 4, 0 );
			AddComponent( new AddonComponent( 10625 ), 3, 3, 7 );
			AddComponent( new AddonComponent( 1403 ), 3, 3, 27 );
			AddComponent( new AddonComponent( 11328 ), 3, 3, 47 );
			AddComponent( new AddonComponent( 10627 ), -1, 2, 7 );
			AddComponent( new AddonComponent( 1403 ), -1, 2, 27 );
			AddComponent( new AddonComponent( 11328 ), -1, 2, 50 );
			AddComponent( new AddonComponent( 21 ), -4, -2, 27 );
			AddComponent( new AddonComponent( 21 ), -4, -2, 0 );
			AddComponent( new AddonComponent( 10619 ), 0, 3, 7 );
			AddComponent( new AddonComponent( 1403 ), 0, 3, 27 );
			AddComponent( new AddonComponent( 11328 ), 0, 3, 47 );
			AddComponent( new AddonComponent( 10619 ), 1, 1, 7 );
			AddComponent( new AddonComponent( 1403 ), 1, 1, 27 );
			AddComponent( new AddonComponent( 11328 ), 1, 1, 53 );
			AddComponent( new AddonComponent( 10627 ), 2, -1, 7 );
			AddComponent( new AddonComponent( 1403 ), 2, -1, 27 );
			AddComponent( new AddonComponent( 11329 ), 2, -1, 53 );
			AddComponent( new AddonComponent( 10619 ), 1, -1, 7 );
			AddComponent( new AddonComponent( 1403 ), 1, -1, 27 );
			AddComponent( new AddonComponent( 11329 ), 1, -1, 53 );
			AddComponent( new AddonComponent( 10619 ), 2, -3, 7 );
			AddComponent( new AddonComponent( 1403 ), 2, -3, 27 );
			AddComponent( new AddonComponent( 11329 ), 2, -3, 47 );
			AddComponent( new AddonComponent( 10619 ), 2, -2, 7 );
			AddComponent( new AddonComponent( 1403 ), 2, -2, 27 );
			AddComponent( new AddonComponent( 11329 ), 2, -2, 50 );
			AddComponent( new AddonComponent( 22 ), 2, -5, 27 );
			AddComponent( new AddonComponent( 22 ), 2, -5, 0 );
			AddComponent( new AddonComponent( 10627 ), 2, -4, 7 );
			AddComponent( new AddonComponent( 1404 ), 2, -4, 27 );
			AddComponent( new AddonComponent( 11329 ), 2, -4, 44 );
			AddComponent( new AddonComponent( 10619 ), -2, -3, 7 );
			AddComponent( new AddonComponent( 1403 ), -2, -3, 27 );
			AddComponent( new AddonComponent( 11329 ), -2, -3, 47 );
			AddComponent( new AddonComponent( 10627 ), -2, -2, 7 );
			AddComponent( new AddonComponent( 1403 ), -2, -2, 27 );
			AddComponent( new AddonComponent( 11329 ), -2, -2, 50 );
			AddComponent( new AddonComponent( 22 ), -2, -5, 27 );
			AddComponent( new AddonComponent( 22 ), -2, -5, 0 );
			AddComponent( new AddonComponent( 12 ), -3, -5, 7 );
			AddComponent( new AddonComponent( 22 ), -3, -5, 27 );
			AddComponent( new AddonComponent( 22 ), -3, -5, 0 );
			AddComponent( new AddonComponent( 10625 ), -2, 1, 7 );
			AddComponent( new AddonComponent( 1403 ), -2, 1, 27 );
			AddComponent( new AddonComponent( 11328 ), -2, 1, 53 );
			AddComponent( new AddonComponent( 10627 ), 0, 0, 7 );
			AddComponent( new AddonComponent( 1403 ), 0, 0, 27 );
			AddComponent( new AddonComponent( 11327 ), 0, 0, 56 );
			AddComponent( new AddonComponent( 10619 ), 1, 4, 7 );
			AddComponent( new AddonComponent( 1404 ), 1, 4, 27 );
			AddComponent( new AddonComponent( 22 ), 1, 4, 27 );
			AddComponent( new AddonComponent( 11328 ), 1, 4, 44 );
			AddComponent( new AddonComponent( 22 ), 1, 4, 0 );
			AddComponent( new AddonComponent( 10627 ), 0, 2, 7 );
			AddComponent( new AddonComponent( 1403 ), 0, 2, 27 );
			AddComponent( new AddonComponent( 11328 ), 0, 2, 50 );
			AddComponent( new AddonComponent( 10625 ), 2, 1, 7 );
			AddComponent( new AddonComponent( 1403 ), 2, 1, 27 );
			AddComponent( new AddonComponent( 11328 ), 2, 1, 53 );
			AddComponent( new AddonComponent( 1856 ), -3, 5, 0 );
			AddComponent( new AddonComponent( 10619 ), -2, 3, 7 );
			AddComponent( new AddonComponent( 1403 ), -2, 3, 27 );
			AddComponent( new AddonComponent( 11328 ), -2, 3, 47 );
			AddComponent( new AddonComponent( 10619 ), -3, 3, 7 );
			AddComponent( new AddonComponent( 1403 ), -3, 3, 27 );
			AddComponent( new AddonComponent( 9 ), -3, 3, 27 );
			AddComponent( new AddonComponent( 11328 ), -3, 3, 47 );
			AddComponent( new AddonComponent( 10619 ), 3, -4, 7 );
			AddComponent( new AddonComponent( 1403 ), 3, -4, 27 );
			AddComponent( new AddonComponent( 11329 ), 3, -4, 44 );
			AddComponent( new AddonComponent( 22 ), 3, -5, 27 );
			AddComponent( new AddonComponent( 22 ), 3, -5, 0 );
			AddComponent( new AddonComponent( 10619 ), 3, -2, 7 );
			AddComponent( new AddonComponent( 1403 ), 3, -2, 27 );
			AddComponent( new AddonComponent( 11329 ), 3, -2, 50 );
			AddComponent( new AddonComponent( 10619 ), 4, -2, 7 );
			AddComponent( new AddonComponent( 1403 ), 4, -2, 27 );
			AddComponent( new AddonComponent( 11329 ), 4, -2, 50 );
			AddComponent( new AddonComponent( 21 ), -4, -1, 27 );
			AddComponent( new AddonComponent( 21 ), -4, -1, 0 );
			AddComponent( new AddonComponent( 21 ), -4, 0, 27 );
			AddComponent( new AddonComponent( 21 ), -4, 0, 0 );
			AddComponent( new AddonComponent( 21 ), -4, 1, 27 );
			AddComponent( new AddonComponent( 21 ), -4, 1, 0 );
			AddComponent( new AddonComponent( 10619 ), -1, -3, 7 );
			AddComponent( new AddonComponent( 1404 ), -1, -3, 27 );
			AddComponent( new AddonComponent( 11329 ), -1, -3, 47 );
			AddComponent( new AddonComponent( 10619 ), -3, 2, 7 );
			AddComponent( new AddonComponent( 1403 ), -3, 2, 27 );
			AddComponent( new AddonComponent( 11328 ), -3, 2, 50 );
			AddonComponent ac;
			ac = new AddonComponent( 2968 );
			AddComponent( ac, -4, 5, 7 );

		}

		public WoodCityMarketAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	
}
